apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rGMv0spsoGj4Vc0M7P1a88leAEi4B1vwL2PxCBlteYAsSje86wSL9kxPpTuVzRJxK7QALBocG2vFeLV02OdLxo7I9kD5QJRtNhMR,iv:1YhFUlmTe+eMv7s6f3BLn/s3B9PQUHFlvCtGHpFuuZM=,tag:gIDM1s8x5e38TqykjJQGzQ==,type:comment]
    #ENC[AES256_GCM,data:mmTStBt0BtpqFT0d+jC3QI0dH8jqwEvOwcbVAS3EnwFrYVdWjV1T+7lzJHtm2QSLxHXqtMAGqu8QA+oDV30=,iv:E2P6OQ1gEW+ufn4Kivr0o2HSWo4bfPRNRViRII3iipE=,tag:9yUYwct5oU6NARMT1rRq1A==,type:comment]
    #ENC[AES256_GCM,data:NmuSzO+OHDjQEBAzTEMhE9cWtO3WT3MRkBdODDqKNMeUi0Uti/CzBbjNs9+45DYT5xse6pSxIHwXDGbtEuBR,iv:NNUMU+tGm5jWyM1duIqd6N0YUOr3hpxYFrJc8N7RIGM=,tag:huLrK/07gwpUAizVRA41Bw==,type:comment]
    #ENC[AES256_GCM,data:1Cewr+3bFJzVRCNtePh/b34vCejrwsl0e6jOqFz3pqZ6F9ijIxmw7CuD6KrXcBkQF4Zuv5TmaCL4WLrGeZTFohKvd83zig==,iv:NWpjFa1S7s7Tq7iw+XQFmtDRGEhTaKqWkAfJ7GFz5tA=,tag:/qa1tjm0eAMu7cBDFj7Xeg==,type:comment]
    renovate-token: ENC[AES256_GCM,data:DqrHZGbQiUOpRw==,iv:aXvxSpr6mG5xmXDesvU61NS3fFxrJMtBlvAvY0Jnvvo=,tag:8vV8eaTqzeYndITuRfkoDQ==,type:str]
    #ENC[AES256_GCM,data:peMNXBIQpNJ/d4Ra4dp4XhRa49+m5IA4lx/z1zEABldNhwm4SROaQI+ug5UvQvsVYXcPIw+Nb9G/aNI5tFXLLhIVxblC9m9aadM=,iv:z6KUZgcVpWb/dQDOzUOEbKz1jeNNuizTKrs5u1F3KoM=,tag:ZsI+FgcQPvEBO6kP2hxf8Q==,type:comment]
    #ENC[AES256_GCM,data:Th6Lu/JlXa8mqTDbdAKPPU49qhr80yEt/97f0frvNX17TP3UVbbcOfjSkDVAdBs3XDwvxoiXGiY4SDuXs3Nv6VN34Q6aEhOwrFHe,iv:7BKPB4/THejXc/falScBOxauHiyumFTC9fC08qNUfvc=,tag:WapHUqgmEd5oOpe87cIu9w==,type:comment]
    #ENC[AES256_GCM,data:i35rxQ21PQg0NMj26eMxYu0GWh2+,iv:VH/sl8wdEtY3Y98yVtV9GMvQu4vwTpdIJZlYhjwZ2PI=,tag:ix4ALw03DmMElXzmgcvnlQ==,type:comment]
    github-com-token: ENC[AES256_GCM,data:2VEYWRRIPFIXmQ==,iv:3HxsFW3fkZgFSV+HnQumUSDvpFjG+Lmf1HC5LPjyaEo=,tag:SGgmOr8TrI5vC+bZNZNfvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdklWZHY0eFEvVHhVQTJa
            czBIL3FxeUtKMmsxY2w1RGVxVndqeHhVOHg0CjFlUnpPVVRIa0IrWnlWUGtYTWtP
            UE16NkpCcDBEU0UzaXZobi9hUGVJaDQKLS0tIC9PVCtHUnVrQkdXN0FmaGhMdUJy
            ckNMZEJ6UWlha3ZMU00xMnc4MEJaWGMKV7tTWLdyj+nDZNbjy+w7dkBjiEiQtUpt
            jgALUSl0GjTHYHpWPS5kWso4pdnGy2xGUcdDFP0ZzvRc72yMvUB4/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T17:01:57Z"
    mac: ENC[AES256_GCM,data:p65Uc7potLRIY/tzYDvn7+dya11acOci4NlPR3HcPVnevqtskSxf0AlvyTxtqy7Y0yklNtNtVhVHHj8u2pRL3pLc/C1vQ1ouQH3W7Q+XinK/Cv595nusjknaH9keaqFDAyHuDUq7xLiaMj7z17k6mLm7iKf669b5cKVUmXuQSAE=,iv:QmAvTUSha9LkEHEkEAa74syrzRFPsMEU012fQPq1sVc=,tag:MgJIZ/Nquj4+U9yiivrA2w==,type:str]
    version: 3.13.3
