apiVersion: v1
kind: Secret
metadata:
    name: platform-repo-auth
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:dIBFZcT7lOG/y+9Y/StXLWTzr6c6sN5WaDJ/p6BxjM9/rtMOjn/GxCt03+Xe1WqGnNyb+gnoJ7GQdbSNl14sVXr1XlJ02ChwcSJ/H3xihOo+NT7q1qA6Ji5Uug5LUo9bqpSoQxgzTMMeLtC5Ol3IJ/hQyL3ljsKO2jOOodSFsgBnTGJpZWAVft+w5bIqLX6eNlvwWDRrsm+S30OF5JKyhpMi9xDUPxeEp0yNfzhLq3rFTlknLp5WUYvSpA+yXtvXsftNdSvvi+s0G+i7k39trU8GrmkM0Or/LgQTgs4AkjBzJLRnm/oS0Td9loY9JCyhLy5ecR/lbfUoIo+2MIbtYzUCwYfS9LfL3x4HNZrcICrczzmora5Fw5jKBjcfp9+Rc43pelBO8A7Z893YbLm1cAWawfmdWOuewrAyLuIgd3J+cuxX6f7GLfbTEUSyoXsZ+uyTmvoaDgO4v/7lqodVpqW84WiPZk3RfsKHZV/vHFCcFyPF9mvwLYN+xxCNI0IEKyJ0SUgfC6hOIkmzvyTWNP+BeIkO/8FzCsgthXtc7Ff8yMw=,iv:UBKwVF+t43s72B6Pgf3YieL+Fk17UCNBN6BFJd7ag6g=,tag:ph6JKJGNLcoJ9JCzWKOj+A==,type:str]
    known_hosts: ENC[AES256_GCM,data:IxwBUhnK7apORaP9c/gbh+T+A5gEohhV2knCpLvhe2ORSaE+7KzMfwcR0y5DjxBeGmH5P/IK5v0bz0rqxPoILrJpOWnXvt/MfcO0lUnw8+03R1ecsyAdbjIvk6n2DRTCHXmD9KHjhKDUQMvLi6ySq5KZ5AiKKqhZ/2LKXeCYPP2qoaco6KBobmczBKcDOijx6xfoioY2fWLdFkk3OGGHizGVha9t5HIz79SbMrqRe7JAS4/gwirY0lBxzy+aTj2qy4S8orgywzuVyTENAGR855PmKaEdJs7LDgBCo4HwJ/LOnGmpoJ6XchFjdYPrF2t6rbo2s9rQzA+Lyb2kGugjUlhc19rPA38HYfIJutEG7tOUGApF7VLoB5TcVmiyL5H1EWH5eTyCSGdAEss1R8g4ApIJ0tMjnqqPRXrszUov3OmUk2XQXSVEQZCQ5TmjyZFtO3fa9E94PZ1da2plhG81PZVbLJGVsdFYNvkdNmTc1iTCJdplcnAW8LWZqXkHlMPCwSVnGAKOrOxC0dyh4G2/kZHEr1XMtEkKxjc0H+DHXHkHgXXCm6vZPjjISDXY4hyg9LeF4OcB9FR9XiPJhMk70RGcGrmvsxiVgS5qPCrMqeWz0i1kjwJrySpmafeQM4NQGyJ8oSA61K47XpBcvwB0XfcWz7zo3pofCvtbdBwwjix9pZBJfL4/eybubjVbPwP7tfyPXVmjowgCuHZYlGXlWXpCcwUBps1LR84ZlKW1dF9YKqOKD9MfTBYlK9/Q4H77RAYrzTadjfXXKal4Zf/0jJg0lU83LPv8WaD4YMGV6iT2J+DYajsEvahdOO4O8kkP07x9Jg==,iv:TZhk6EM5n+YFETk6+KU/QMS3ASk7uNEdLxACIvjntdY=,tag:EOkyniNWXYo0KzaYGcNR8w==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Sld4czJLcnpYUnVKWEYz
            SEZDbTM5a2ZsNkxzMS9xbzlFMlBXVEc0UWpNClQxdUhXLy9FVDJONlZ5U2pYMnFD
            NTUwTGYrdTluQUE3aElWamUzbHpaREEKLS0tIDlCWHF6cTFyVGtRUnRyRWtCa1pl
            Ny9iNGVSRHJzUGJnKzFNVzd2bzdzcW8KZ4CQq7nGlbhOFH3lEStqwOveHfuqKaLu
            qstlDqmWog8phd+Js0f/mEPYqMFnGJaY5qk0fuW55p31D/oIOmjHow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T18:38:26Z"
    mac: ENC[AES256_GCM,data:k2TZT76UVQUM9TEC6OTBf9w1mV0vRsBvzU+pPGCd44Pf7LlTr7XshlzQpxP1tArYkVtW1IHSjEiGAee5URwLoBiJWeifDy08vgP9t+Pgys9PTEyZ3pqUwOM/uPytt3iewo6Ai5ylrHHKG6NzpYoLkvBqsReIF4fSdktt32own/Q=,iv:+Lmk82eOfM9aHG/xbAJ0zfHczHCiGmQqt803NPgfPUY=,tag:x7BV5xF2sjROMr+YqGPy2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
