apiVersion: v1
kind: Secret
metadata:
    name: zomboid-control-token
    namespace: zomboid
    labels:
        app.kubernetes.io/name: zomboid-control
type: Opaque
stringData:
    ui-user: ENC[AES256_GCM,data:RAnU,iv:e9qqjtC7R7hSRr8GYoKHYZDvYP9f+XT8yJl3EawNcbI=,tag:P0m/d0k2HVuOpzoeZjj78w==,type:str]
    ui-password: ENC[AES256_GCM,data:vM2s8yhxEQTYpeJJk60fwm7l0Y9UW94r,iv:F7SdSGF9EgV733XC/V39VTgIHRsFBENPRghRls65NKw=,tag:HuaZGVSVXU8H1FzKhTNJkg==,type:str]
    control-token: ENC[AES256_GCM,data:hORYPdFAGiXLsm056ghylOfjK3UNDmKzmxCicYMHYWsKsIh4+c+ho4nzGw==,iv:MylvChxTxmdX8r4V3BUQkRcFZNWhsCP4BnkKBRavyMI=,tag:7EEWI43pW6mprVAb24g5Iw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMG5leFpiTzJTdFlyU2xq
            Zjc5MlpleSsrOFBBVW94Y3NabmZrWGI2OURBCmx1QloxS3U3YmhZbXJmOU5icGo5
            SkU2K0pGMi9PbHVCWEI5dXZycVA1VFEKLS0tIDJ5eEY2MXI1Rms3VE5XakhaYVNr
            SzdtUjBISkFmVVFyaXRSK21mYTNpS00KSl8tT42gkvtidP0vJuUA3gAq3Bd+URhU
            2o1Va1zJuFCoCM+fsKdSvTOgRo4eeb2eNr42GYg+aUE+RuCLSMIS7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T00:56:13Z"
    mac: ENC[AES256_GCM,data:GETaJ57s9A5vFC/phvTw3xMCTY9xTcGJvHNDUe+pFO+RrEU+PP1XB8uDh58eqnpjKvY30oL5ZscJjL8kc/07QQkGu6A0RvVomEsk24wXmvOmoCa/A+wj+a26tRjdwJdAEU0lnvLh1bnVotSm+vZA9yu8bG99TBgrUuuhzrJbAnk=,iv:YYAVAGNuYZqqfQJcJho4ztCW/tZST/cSzfzDCVIP1b8=,tag:hfY0IljlOf4pX40LxeE3Og==,type:str]
    version: 3.13.3
