apiVersion: v1
kind: Secret
metadata:
    name: zomboid-control-token
    namespace: zomboid
    labels:
        app.kubernetes.io/name: zomboid-control
type: Opaque
stringData:
    ui-user: ENC[AES256_GCM,data:g6JwfOcTviQPdA==,iv:VPcs1PWfyiSVq8K2zIzdc/bd9mIKHA8IaDtwkSUxijc=,tag:1RpXnJoJ/nZBS2W/6jGowA==,type:str]
    ui-password: ENC[AES256_GCM,data:genh70qBk2dNPLbBVQ==,iv:1UwcTm0drlgfoRYP/WPyJSyPiPYgfq2x6qTVARr92cc=,tag:xd5iQ7V1F7sSn7/n/rvjEg==,type:str]
    control-token: ENC[AES256_GCM,data:M3oFtemuTKiH9F6CQj+gsErmVMaCcfd3377o36dLsCSSlaulkzoKFs9Lrg==,iv:PpiffZE1JY3Nrub1zzmnA8RHn8kiSB5ZwW1q0vqqZGM=,tag:J/93X86Qg7w8Vs67hAZtIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS2orY3pObzBHT3loRFRq
            TjloVFRQQ1owZE5xVUVNWWNaTjZISlI2Y2p3CmdaRU5VdjdwUDUwdXB2WC9MbnRR
            SUN5TEFGYTlwUUNlbjEvSmwwY1pIYjAKLS0tIENmUlpsWFZtTjZJU2xwY0szL01U
            RG5VNWJjOHpaMjBKSVRheUhSMFh1dHMKq6liTttwWLSHxSzvmKovPoO8PXlKTv4R
            AoPi4IH7d6tIm2G7P2dKXlu/0wlOuSO41Nt3BjtXmnV75KRpfBhl6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T01:53:36Z"
    mac: ENC[AES256_GCM,data:8cloDYnvZa6DyFwqS8hiiqm29Vp0uBdi2D9m37E7VYrAaR7LaRIVvFjMzlY0q9Qh0n4/NiyNgrYouiMRYkqQa6x3rv2+W28wt0OwFnBgeq8ntTS0fe6CTbBgI2zyHBRhfPz3ve1S5gbYaHivFsUsa2F2zhqIscjmSG2d1CPXMuw=,iv:fihpQVtkFlmT/R/+/urGgftRftgBOvvFAA5WKj2+GMs=,tag:bIQ9ujbtG98GFP20yvJ4kQ==,type:str]
    version: 3.13.3
