apiVersion: v1
kind: Secret
metadata:
    name: zomboid-control-token
    namespace: zomboid
    labels:
        app.kubernetes.io/name: zomboid-control
type: Opaque
stringData:
    ui-user: ENC[AES256_GCM,data:3S0qudCRG1V4Jw==,iv:DdxDbdr5YiZyCwakylLcndh/oXpUoXZfXS/Mo+cGHRY=,tag:1tS06+A/iPMfPMMHoB6bpA==,type:str]
    ui-password: ENC[AES256_GCM,data:Cy0wK3NOAS8=,iv:USOC5EtNtctsmW+62/F+CbaZpLxnqarhps+cnR1e0Yg=,tag:RnvfDY79pBO/YeaHwhyplQ==,type:str]
    control-token: ENC[AES256_GCM,data:fgCcZwUNFpJXAHUuiyEm9x4fVDw+8E6EGhclMmgUT3nv0KST+2Oj6mvCCw==,iv:utmA5qe+ICugMUOT1Fw+Im0L6h18Kakfiurx18cwrIo=,tag:ZmFOYg6EQDhBYRwMkWk6yA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRXROazRUbWRONnNQcHI4
            dytyRTdFRlJBUnNuTnprdjFzeXJ4V3pESGxFCnF5VlloWm5td3hXTGxIL1lGOXJK
            Uk8vb3lFU3dTUUxWRUoybjRvSUlCOHMKLS0tIGNjMU95K1h5YXI3RFJUWkJIVnlC
            NDE4akhWMDBMNkhTUUF5T1hWSStlRzQKbXfWjR2DUDt5bSDS+B6WoaOuKCQYlpmS
            Yv1QP4qR+zKngguf7NvMDC89LTl5/haB3BC4pZcjplGQwvZM/rl1ZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T01:13:06Z"
    mac: ENC[AES256_GCM,data:Eb13MZGe46nLVuzOKa78rc0r6WTSxGfJuz7hVJJV1suXpJekshcAI9if4UR+XLSD3gfqQgTDBlDOlo5qXs7hjpUwZx7vX5PQJOtxYbqBB+SxBiOgylzAocGVbOb8UGMrNqIgYm4JLr4uP+PMvy3hLb5OThPbbyi994fZ4Ci/VaQ=,iv:3Jgow72mL8YOaEZv+zV82pTq/Cpzfr88xghLu+IkWcQ=,tag:I4DgSH2dq3Tx1OJqXs/Z0A==,type:str]
    version: 3.13.3
