apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-tools-data
  namespace: actual-budget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uncomment to specify a storageClass
  # storageClassName: local-path
