apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cal-data
  namespace: cal
  labels:
    app.kubernetes.io/name: cal
    app.kubernetes.io/component: web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
