apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster

  settings.yaml: |
    title: KB Lab
    headerStyle: clean
    language: en
    target: _blank
    background:
      blur: sm
      saturate: 50
      brightness: 50
      opacity: 50
    theme: dark
    color: slate
    layout:
      Ops:
        style: row
        columns: 4
      Media:
        style: row
        columns: 4
      Dev:
        style: row
        columns: 4
      Home:
        style: row
        columns: 4
      Finance:
        style: row
        columns: 4
      Printing:
        style: row
        columns: 4
      LAN:
        style: row
        columns: 4

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: home-k3s
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: long

  services.yaml: |
    []

  bookmarks.yaml: |
    - LAN:
        - AdGuard Home:
            - abbr: AG
              href: http://192.168.1.193/
        - OpenWrt:
            - abbr: OW
              href: http://192.168.1.1/
        - Neptune (Fluidd):
            - abbr: NP
              href: https://neptune.kblab.me/

  docker.yaml: ""

  proxmox.yaml: ""

  custom.css: ""

  custom.js: ""
