apiVersion: v1
kind: Secret
metadata:
    name: zomboid-credentials
    namespace: zomboid
    labels:
        app.kubernetes.io/name: zomboid
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:J5kSDXXAEjlJJdZKX6lmfGRDB/Dk5qTc,iv:BzIbiPwYSwgVSPwxlVWrMK5THu8S6dstETKRjCzLkag=,tag:/ytkUNkSnFgT/hNnLFuPXw==,type:str]
    rcon-password: ENC[AES256_GCM,data:3fbQjbv4VEB8EldFDVS8/j8uKUqyragx,iv:Y80mHmhMsz3ZqiJpS3qEtWiKFFDSwQsnuy5SP2INz7Y=,tag:4JRXhz0H2v6BXU15SvxiDw==,type:str]
    server-password: ENC[AES256_GCM,data:GRv8X2Imv57mTzXuxtxK26Zb,iv:Tre9Q+WhgiVVyC74MPTRKvQ3adz0WQFecnvRWFihwb0=,tag:jYanYbiQCX+I+Q7VpTMIUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdlhZWjYybzQ5SlZodmFv
            SmRyT2J6dDlEbzA0T0VEUG9QaE9IQlc1Wm5BCmwySGxRNGRWSTNiYnhXaDFFTzEx
            dUkyVXhBZkVwTW1xWTF1cERTVENJWmsKLS0tIEcxUGlFeWpMQU1DWGMxdmJJbzli
            VFFXREJoOEZJd3BTOTZkY0wzMTgwc3cK6NKzHK9cIrTLe8pLjTi1WAyxvqW+36wo
            AobECja/mMF6BvsDkp8gHkVVQhobG4e4Oio8sao7Cxf0QQMS4I8u1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T02:52:09Z"
    mac: ENC[AES256_GCM,data:A/zcbQxlt5OG2HCBrx9PYmof57W9neXZgfZV+IqTNyzPXokUV+DtOQHgKXG4mTzCmXHLIuo7NvcCxIY/b6ewKiGXDOvc7Ghlmzj+N6n1xqqrQIDgwiH1UBWk1H7L+MBr13T9456rzvo7Zy3ZAoFehXhxTfUTkzzbssQWopk2QG0=,iv:A24llx9JMgTH0ot1pjzTPkAF8G3d6o6YqP1fhZfvrZg=,tag:NcYTuTlqjgMuJx1y1XFmLg==,type:str]
    version: 3.13.3
