apiVersion: v1
kind: Secret
metadata:
    name: zomboid-credentials
    namespace: zomboid
    labels:
        app.kubernetes.io/name: zomboid
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:8+GE4o2bEuh0+RmVYQaQCfIXQ3A+6NWn,iv:ujfL7RvtZ0LDUhs0aHyzC2OOQJTjyFadFLkegL22sTg=,tag:/JDUDNnOKk+BiX8/FlRj3w==,type:str]
    rcon-password: ENC[AES256_GCM,data:5oWSMBG8Tgf3PPpQq4jUL11ULvXtvasi,iv:6LyNtLe9abk8oytDYOS3DS7jRD7UHX6kXlFAtAWyMQw=,tag:uVJ9jzzG7f6UKopL+qBMlg==,type:str]
    server-password: ENC[AES256_GCM,data:Ev0Wx142rLw+i6uRwvp7SYyENA1S/jm/,iv:Vx9sVuNhlyevgNHodVscll8uvuJqv72QsOlH9YrXyus=,tag:EKFBLwqTx+8Gs+MdO8QPbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxejRaVE1oZTdrT2RNSmdV
            RFR1d2QxWjZ4RHBTaktIL2VUU0hvMzhqVVY4CjFOQ2R1aDU5a3l3czY3cWFadnhF
            SWhwTHhZaFlsZ0JkTWoxcnlUOWF3b3MKLS0tIFJiS0VMN3hCVmdhaWY3OFplS3U0
            Nkxuc0c2L09VZ0d4ZG0zOGJnUHc2cXcKq7+cFtSjX3o3zmEiTGTkXQ0Eumaqmcrk
            g96M4anZp2O5cHYJBmNKtvUI48ZqCV9VD0Ny/A8vV9X46RkyoSMB3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T20:42:45Z"
    mac: ENC[AES256_GCM,data:DrNMjNBqdnJeNC6Ci3hD4aoguqsgEY1R0H0tpFmr+n8c9/Mg6UIrCXFVsUKrKszwwpSoeOubxOat6/bReiuzH+MHpn9LE7uqwTXnpy6DwUhTkF/9lkzKP40PeZiZY3nHGAGzt1rCi4xq2YZFjUVc2XvwTnl/XI1YTbl/aHGli0c=,iv:nxdpFjEpCa3QnAlEGM2Y8I659mqHMnf/imHMRCa1tuU=,tag:wmPxFFgWxr95AyMu3NNRJA==,type:str]
    version: 3.13.3
