apiVersion: v1
kind: Secret
metadata:
    name: backup-nas-credentials
    namespace: vaultwarden
    labels:
        app.kubernetes.io/name: vaultwarden
type: Opaque
stringData:
    smb-password: ENC[AES256_GCM,data:QtfVgBgaiq87ESXB6B6BtJbrp3G6a6pmAYUariK/re4=,iv:aI8rufFThTGboH29oj5aX244wEVrtsEpQgPmkMZNImw=,tag:daUYzEFLk/AWMY6mXyZaqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOUZaK0JIU0J4WnF0T09M
            ZHVPYlF0V09UNUlQaHA3OUgweWhWZlhOdXdNClFZUEtaaUVTdGkzMnFNNUdnUFd6
            RlBiT0Q1dVVWd3ptV0JFL2ttQ3VTRzQKLS0tIHpvK01CZFNlcmI5OEwxMzZIWGgx
            S1NsQlRjVmo1L3R3LzNLaFJCRy9SLzgKnChqQTe0c9V3E3ROxDPZUz57qWm2dZJl
            Fy2oBgopIkqP0RMx7VB+SRe0FgtU/uBtWPw954ykxnZJcBLoqYIPOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:41:44Z"
    mac: ENC[AES256_GCM,data:0MXdw2YHjp9bNmaZ6qZy2ybQ0h4xC/ah1gX+gxddpqqxGXqIGlq8FIQnWTLEvruqJvuTH/yFgKozh4I6eAUVCpSd1ZBws+jVxFApvFUEfWHCzHC3lMGhOSB5kCvps4uEzCIPr9AW621ZAY1usW5h939bmBd3zZ105Gl8HFKWgEI=,iv:n9l5J1UXNhSJDttAiMEWevkUZm8plq3WCicZQXFVGxU=,tag:qTzVbBXQSL+wCAgBc3LaIw==,type:str]
    version: 3.13.1
