apiVersion: v1
kind: Secret
metadata:
    name: scratch-auth
    namespace: scratch
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9Hj42GMOkuF+09l56sbcmOXIql9yZDv5FSnLf3pkz9E1QKFi1I7z7+2rswMOUv0k7vOEVfIF2/PR69jnYJEScXDEFgpZVaRJJSfbt5s=,iv:cSte+f/GiP/hbXJW0RsWmWgw7mPfiw+ViuiBJDGW5AY=,tag:FdbuT0TwMQM9cQaVA/XHQg==,type:comment]
    basic-auth-password: ENC[AES256_GCM,data:KdMz/P646Ic=,iv:BHW12j60TWQDL485VVmZ5yubNQc2QbHcXROeyKHzYHs=,tag:nAjDmamz/FqX7cf7wRqzwg==,type:str]
    #ENC[AES256_GCM,data:A0PMsaCAbCViMIYyVo5scyZC3Bz+voOC0iusjQQbYFdWDyxoXjsFGWdz6Eeianpbt7UfZhh5nTUSt6Fur8XzpCisj/SndpOY+A==,iv:aaxcKq5FFF9BjipLmR0MhrwbrRVgfmUG4zIwH7idooc=,tag:FsVLSQrwq18qQ1Dc8WA4cw==,type:comment]
    admin-password: ENC[AES256_GCM,data:Fo2UKknn0o0=,iv:b45OwhxjmFXgXru72agRguAup7QQEdld4BRupqLgF/8=,tag:K8ybLK6bpd83QRpm1kLSxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVkhsb2FTdDZ2WnVwYWtw
            MkYvWjJGWitpU2k0YllNQ0VsMk4rRWFqR1FJCkwrQ3NXSUpuLzlEdHNJc1JUUWVo
            RHR2dVRFZytIdU9QZ0JiNjhzajRSTDQKLS0tIFZmMEJ3MFp0TGJmL3VzZjdSNnl4
            Y0JYcmsvcmQvTUFXUDl0Sk4xZ1hld1kKRZ8qCpJKQM1t0y7qhF21VgG1Aysfqf2R
            hufwZce6xoeS5lNh3zdB3mPytC+z+t3Q5GNbrAaNYgP8euKQWcRZMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T20:40:14Z"
    mac: ENC[AES256_GCM,data:t6LD6gOXFcU3IkUYCfWyvAaO6PafhQXaY2A+hyzWVnsdlsIYYT219sMGQJlMKK2wbLMKyLSSs6pkcUR8Za4fuNyL8zEbd9wfDDHXmcQQH7QqBKdKZcXXm/Z4BdIgYtzOG99EYi3p51F2ES9r7HuHCOWOdFdEfEl5K2T27jGrdQw=,iv:PaF5UtytiN90/gCHIevAmvU3/jdP3rq6n+LY/m2TKTM=,tag:VgVR9VYj5+d70xHK93fkJg==,type:str]
    version: 3.13.1
