apiVersion: v1
kind: Secret
metadata:
    name: headwind-fleet-bridge-secret
    namespace: headwind-mdm
type: Opaque
stringData:
    fleet-token: ENC[AES256_GCM,data:CFHh/x2osuUrA7rVExWhVqR6ZwxofVakftOwqeLvHL+LQ1+cUeBdSg==,iv:QSGw2aPQa0jWMqbLcS6LXxsgjNPYA4UXlHlm1s3czGA=,tag:L6MPba56rL9WZ7JjPHsiHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRFNLSHltaEY1a3lFY0hz
            QTlBaDNUaWhzMkovVDlPbmFVNHgwUHlFdVQ0CloxVVJDNDgraDJSeW9PUStSd1Nj
            T1pwMC9xNVhGam1oMVZSNGpxWmRxdkEKLS0tIGgxODZFWmJvYW83QzVOWFU0L0Y4
            K1F0R1B6WW4vWGRBYjFBbVNsbDc0K28KuqGeWohrJYJLAepnHTkx8gJR31y1Saxa
            MM1in1pzRJKbL6ft3G1dIBi/C2FWZq2Fcgyf1/ABc+PSzAQbMHVxFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T20:33:25Z"
    mac: ENC[AES256_GCM,data:ExT4++BAwfdWD+lUrTdiMEY9yYGO9qUURf/fBmve1UhmPZtbddrlpPFVfeRzmXN0n6w9nTBohacElbFCgWys81soAUIO6G9mG3HfHeWl/6GTlGHn96RQmgzHLgRyeNR4L6yFD++hlBovwVa+NuqaYNLtXY16Jnl+kFn9oD9URHo=,iv:Ju1LR3FEw6+vjlOv9k3h2lDd2yxP2EM3jOJ2a8b7MOI=,tag:RWaKmDq5b/lcAE9s3/+8PA==,type:str]
    version: 3.13.2
