apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - registry-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/openclaw/openclaw
    newName: git.kblab.me/kblack0610/openclaw
    newTag: latest

