apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: openclaw
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:2EmQ27RbiQn1DShjVhvInqcWrI3edIF09M8XYjgyyhaMxYGw/zpCPT3nT16i9RRQyaj1i3RIfCNNvHof1mQtaWJk7zax0buK3z4NvaJogpCDxjiETPmNgelkIzU95/lP7U2SYpylikqMf2MKW7Y61Dg+Ac5EYbmc7BztJvSmojEXndcrpVtWDmRKWNZvHlAOU3pHXmuCbaxJmsBzQANqhJ1aylpEMqJ5cTjtW59PJ+Qfvvu9SwNN5g==,iv:7Ozbgk7pO6KDkGW4XpwtQfs4ymksT3Oq8AURHGXfwT4=,tag:vUBW7XQDvNvtUo9to7zayw==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dStQYVU3dDVVbGJPYSsx
            VTVXNllIVUhyVnJsS2hVVUpNaUFzRXhMdlRNCk5UaUVHbHg3MW5ZOHJ2WDhtcTRS
            SGdwNmtPcU5ZNGVIOFAwcVBuMkNTUGsKLS0tIEpYRVBnaXZWbkJiSmNlbGthTDda
            WXlRcnMxUzRkNWFSVXJzS2E2T0wwbW8KKVuyDjaDUQG/XfeU9IRv0YEeUYsaSYst
            hxS7VSs2M5v3vBRsPOQcFIA+FCBjMrFn3UWHr+Eoolr7VlxewtgQQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T06:09:12Z"
    mac: ENC[AES256_GCM,data:tTsVpXdXZkng0EqU0XXcjm3StM/joClCn9EsIGl1ROlogiZvSEY7e42Ld4AWChjx0FJZFsafl3NAd/bgy2Mr+ihvRmr7UNFKYhtIzw5tLFH+z6xw00nmUc4SaSJfJllqLzZCJKOiYkP9DZ/ScFnGOJZ+1ZS/W2pvqVJgUmf34KI=,iv:W1gLL10o54mQfU1k5Tb23AUeHY+9bIuctZ0K/+4lIkU=,tag:VGcfby91ets/Ka1KxWA/7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
