apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
    labels:
        app.kubernetes.io/name: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:C4mS9ec0Vmf5nurfqwO/KONRSru2yfumrjPlGueVvQNYrbUmvmcJeauJunldW+BB,iv:3bzs9D+H57VyrLa6c10FIy2PB0J6D9dVY80fpuOBmoA=,tag:Nf+Y6iauJuBTiTPV4L8vfA==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNzVrWWMrSzZHRU16Y1lw
            MkVpOGhlRi9zZ2RZZzdFOGR1TWJScVZSdmxjCk1Pc3U3L2hGRmJpazVwVzFKeFZQ
            SmVyaWo4Y2pEQlBhWmxuRXI3RStUYTAKLS0tIHFEdnp4OEpXRjhjRWEraHc5RnZl
            MTJSWUUzZHBRZnVnOWVlU1dJMU51Yk0KxVd8ZhF2ekmkF9DFmFFg1jaSRAcSIirJ
            HwIf4z3aLsTSaEr3p8bsVeq6fuMGGqdqYu4dZfBLkcZe/gaXJJIh+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T02:07:09Z"
    mac: ENC[AES256_GCM,data:ETAHM1K9/MmJw3udQogc0c5WW0X/s+RkLlGX47LdYtOaaQJUJC+B7QZKbX/KYX8zjUoChkznenVodC7iOtmsdMGk5BxGvc7lZPrDYX2GViGDglRIn1bYDXJYDikmNZX9EAD/QQwi8u+eV7+ndM1zbThXA5yRrnNgsuqMte1I5CE=,iv:uoV7CrgWmrlX4jqRaHuspTqX7FEI7rw6ntVDMXEiGt4=,tag:nJoVPCs5ZOw0V5VoNXGl+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
