apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
    labels:
        app.kubernetes.io/name: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:guaQGpWOYf+llu4aE5WqXalH5KEQVhZ1+qp0FfePYGioyV5BwNMtyOYB6WKR6Fnx,iv:ObdYRakGwa36seGXL7mdaUyQYHou4E5bpqaBbDGGUe4=,tag:n6Zk1i1OmLupbGlHSqW18w==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:1wmqymcjVJ8dflWU9nMciLmw1Sd6ZAqexHrqGeCBsEVrunKrgLXk9FTFogifWhX5,iv:K3WUFPSkZ/lIuCpRFDDvXK5sqM7UXZKeR1H3Z+zjp00=,tag:HIBRF5SV6Tc67yNLtpLbBQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQVBYSTMzYkVxVEY4cGpT
            TUZueUpCWGV0MGl5ZktkWitYb2ZUdEJPMkVFCmxHMHMrcE5sdmZsODRUWitOQXF3
            eWw5WUhwRzFlYlZFdXhXSDhUa0R4bjQKLS0tIExyOUhMcGx1R0FBMWpQV0lScTFy
            alFtM0V1UU5ZTkZISEtKTnU3eWlGdTgKKvPSWxuPGN7cVd8YpLKKlIh46DploiVP
            qDjJzv031VFa5FxpVXBzRWRvDVZOHGEQvq7+9luXcPuaenDt9emYQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T21:49:46Z"
    mac: ENC[AES256_GCM,data:05xmnOlcwzdnjy+0XVapItkTFXS/JIhlalmo1746avnPtvQJmuL/OlDlddzaFUWovZ6cVEjQjm0RPkyAmpey2bLFLzf1Igy8LR8wadvYdfkyz7r/RwpSSuH4mpYea2g48mgsUbbpX9mGUMZyj6FQmxZmfOc8R/LvLWyEpDF4UHU=,iv:zAeTQQmJL67rukG6wN5I0PJ4BzlugflQhXUCXSNcq84=,tag:k5g2mm/7b7JqgTIWQ0lC+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
