apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
    labels:
        app.kubernetes.io/name: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:guaQGpWOYf+llu4aE5WqXalH5KEQVhZ1+qp0FfePYGioyV5BwNMtyOYB6WKR6Fnx,iv:ObdYRakGwa36seGXL7mdaUyQYHou4E5bpqaBbDGGUe4=,tag:n6Zk1i1OmLupbGlHSqW18w==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:GDYWg2yv8ngyn4i/H5omtTe3C9zRep2Fbw==,iv:SM4c3R26dFSzzaNu3A7QAFt/47AEJ+l4WAXd8VxZLtw=,tag:vEY65yeqJXLdjCjK9XMAGg==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQVBYSTMzYkVxVEY4cGpT
            TUZueUpCWGV0MGl5ZktkWitYb2ZUdEJPMkVFCmxHMHMrcE5sdmZsODRUWitOQXF3
            eWw5WUhwRzFlYlZFdXhXSDhUa0R4bjQKLS0tIExyOUhMcGx1R0FBMWpQV0lScTFy
            alFtM0V1UU5ZTkZISEtKTnU3eWlGdTgKKvPSWxuPGN7cVd8YpLKKlIh46DploiVP
            qDjJzv031VFa5FxpVXBzRWRvDVZOHGEQvq7+9luXcPuaenDt9emYQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T00:01:47Z"
    mac: ENC[AES256_GCM,data:P3bx9RerqWWAUGI6VYVge7/qrhPCyqpY4a1WyPdQFN6YyufqW09PKKWyuC0MqbeqfdiMBKjVKlTsqI9EmaQVhyKlRo2b7iAigQHb4IkgrKIcID3cIgfIytNtdCyHSJLZUGRHSzSBkI7R4yat0AG8wlakbyWurQEuoVJMACCTQD4=,iv:fsoy54XngFpEA6LB0EkcAdu4Yy6N7s79G4qIa3aFM6c=,tag:rxGaoT8e/YppMKoqMuNXpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
