apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:HoxLY251huwU+CBn3McMh7VBM1j6Faiw3/67TL3Z4ZOj4VwrHUtqtI8NRSuVP13IJwYiDktH2gE=,iv:wJ5IR23+PunUONciTwBVcIe2giuXyUV9XbN8mQf1bGU=,tag:izjTHYJmZxb673G01X8lDw==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMlFJYytqSm1LYWJvTmVx
            cGFxcVZtaFFzMTJyMVRxaUhrVDhsbGpHK3dJClFWeEpGTlFBbGZSbDE3R2V6M0k2
            SENaUmxNMUVhalRRclF6Yy9wZTNUNHcKLS0tIHNlTWRYRnVpR1JYQkxndFg0Ri9i
            T3FiQUV4dGhwWjBwSzZoK29ZbGpZcEEK6cZrswYzas3el1Zqrr235uoblP/chfyB
            0DLJwVb/v+dyqOiLxGFxcKailQRMCyk4ix1NYkP8G6r3EqJiIn9eCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T20:44:47Z"
    mac: ENC[AES256_GCM,data:s1YKuVe5+iruV4kYgBf4a4KT2dzbRVV+A0ru18E6jXOKbPfLEfSCJX4sV9ZwQVLlcwEFQVI/K/sobDV/Na7KZ4I4AHPZ0Zxs6+o9C30JKy18VCpCAxw6flxsBJPy0GhjFKID0K0ySCj3NyectZcA6Nq3BOCyfgFkBu5gWjoTjSs=,iv:jXan0iSYibPw0WqAQxCCZLpnyCMmOxilwg0QdhYHQsI=,tag:8QvKLbEPyv2wiJGmJ/RgIw==,type:str]
    version: 3.13.1
