apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:xypq1xdvCht2nB5u6T1wHSZvRpDbpwQCY0ZUyhG8TuWwxlbxO+P6DqDbD4yIxnYkV7saTrX3yFI=,iv:ybw3If3sHonlBhV4czSOYZvACoTBerUmfPJzq5aprks=,tag:vBWpqBWK9iPTizEkCmNTDQ==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbndZUkIyTGFLRDV6Z2kz
            WittOWVuRUhoNWtocXdUTVZsSG52V2VhdjA0Cmhodm9yUlZJNms2TEJjVTZvOWxx
            NGc1aGl5NVFldkdxQ2ZUc0RZTFRXMjgKLS0tIG5hTG1XeUIzWWlvTXAyMGpjRDNX
            MnNPc2RlWERaWHdubGZDcCtmcFhCUEEK5OzDM6S+KVPxlXdVwisHle/ROyCJVXQZ
            /yzyQpJVGwQauT40bDI9Fu0Sy2DT2rxP8Z550pqv3cXeEFLgc6SGvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T20:34:55Z"
    mac: ENC[AES256_GCM,data:KSpjXvf8tWOlcd7a8nvWN6rCWo/JjfymEKImknJOxptfyk7CCefFQcASxZ29Z3cJNsaPt4Pgm0u2A+Qy/CvkNTfarlyPfaiYlUTuwHWOQ2GE+rCUkEw5ci/e/Scw8b+vOJh/YYJJKhLqapsNuUXyHixrqGKLw8zEzxj8FAgoWGA=,iv:K+mvkNMsBxFco7owEII58LdkuyyiCHRHsHKDOsQc6E0=,tag:d7My4KBRy0xgFfHuhpiblQ==,type:str]
    version: 3.13.1
