apiVersion: v1
data:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:6VHi+7uhl7WxH5ar/m11MWxwHnxyakF4SpdUIiwZMlMIsWGPavNVM6qyA++md85m,iv:6Fbga1H5KXOL6R3scmgdNnVyKPBbym6BRU0xDT8VfFw=,tag:D7z0m3gdxHJptnQiO1Y7Ng==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:xg1sBi9wrJ9ZV9wbd4fRd5msZ7it6pcSDhxCN8SgxKg2Z2HZFt3NlZ4FeJPtOemdnjzerK7E2us2JS/BH2stjv0p7mhDejsSwqejQw==,iv:gfyngutFtU4JJAUioaxh48f0QM8z8JLkNWhk2jEJ0uk=,tag:dGWcmd+hDTD9B5AqJ4j9IQ==,type:str]
kind: Secret
metadata:
    name: grafana-forgejo-oauth
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVlNxSVNiWEhTVWpYcHBm
            TnVFdktkUklVcUd3Sm51dVRNejBaaE8vVUVzCkhZaFRCM1gvYUpGc05KRlJ4N0x4
            N3hRMm8rM2NseUdiTmZaZnp6ano0bncKLS0tIFBoaEtHODBzNE9wMXN1d0dzOFZa
            RWlIaGVjKzFKczNwK3hTcTRCc053akUKIBFXt9+vWIkKtTcg380DupuC2qvDLpuk
            BxhqIhI9nGdA18Rua8eBHBzJZoBKOaa7IrNEAOy0H3zZGpgaLqgwCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T21:15:34Z"
    mac: ENC[AES256_GCM,data:r6AZ8XeUTYAVifRJj1yzCNafSxoKRHxBWlGTUrbz0wm7savc4gV782Bb8ynvZOCcyCaDjah7qqdKQuTtOzYEehpHDzylozrTMdouEPvx798hsvlaWHCWR47vNnqzmmUsdgR3EZbyvhcORnpDkNcqVrBKKjRgQjcj/0d6NxLvavQ=,iv:+SlkLcl9RL7flq+dR7A2YMcxcfHxg7mIqvHuoomL2mA=,tag:q6u5obp833kpgOWGVwXasQ==,type:str]
    version: 3.13.3
