apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - middleware-ip-allowlist.yaml
  - ingress-grafana.yaml
  - ingress-prometheus.yaml
  - ingress-alertmanager.yaml
  - prometheus-rules-app-health.yaml
  - external-mac-nodes.yaml
  - external-standalone-nodes.yaml
  - external-iot-nodes.yaml
  - dashboards
