apiVersion: v1
kind: Secret
metadata:
    name: notes-sync-bridge-secret
    namespace: notes-sync-bridge
    labels:
        app.kubernetes.io/name: notes-sync-bridge
type: Opaque
stringData:
    FORGEJO_HMAC_SECRET: ENC[AES256_GCM,data:3ZvAgPYuq5tMIyXGijNldmoCgoopZoHwWZ6hWJ815Q4D8HCzGt7aknHfTi5QpfRUOhZw2wF+MPipiIlBBOIlMg==,iv:bB1Xd1zco7Dk6xajxzMimCgtaa6HY6wyYX76VASbsfs=,tag:pyZjQn8xiPaHL6s6KO0Djg==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3ZFWldreEtZUEN6NC9y
            MjV2cGwrWmlZTHBDODRjc0w0Mk53cFZnSUhvCndrREg4VUxXc2pRbldtSXZGVzBy
            OWNXRXhVRTNGMGs1b0gwaTd1K1VzWW8KLS0tIExWZ1JpekhBdGQ3WnJNNTBZM3pL
            RndIdDdmZmVweUwyaHI2M3ZUNkN2TFEKYj7wHXJW8qU/wnZYjNSADzpQA0TMcT7L
            kG8B+W6nKEiSYNxxqlU4o+yy16PTKwSsGVANNpjrgq4HWvGka4cuUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:44:32Z"
    mac: ENC[AES256_GCM,data:m0IfduvoeiyPZkv9E8zXvlNw7nfhx/XxsP/+HiC1qZi5sKFLpA0LHazJBnXuLgpM+ON7cssyayGtYHnVKRCKYejF5aWSYLhHmiyFQGG5U0ghq28nuEtc7yvof8Y03NO/rrvZchXIYTZdpvfgx5VDfuT/uRWOZkokHa3FN47zrCY=,iv:pTgbKq97s5RZMkM3/0YKmcI6EfwLrxcZZ1j+TfyHikQ=,tag:84VgSzSDtg2WhF/qkjg98Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
