# Local secrets - DO NOT COMMIT
apiVersion: v1
kind: Secret
metadata:
    name: headscale-secrets
    namespace: headscale
    labels:
        app.kubernetes.io/name: headscale
type: Opaque
stringData:
    HEADSCALE_NOISE_PRIVATE_KEY: ENC[AES256_GCM,data:yMgx1+9Fjn7Gv4NQEdgK+UzJR6vJ5da6VM9Hu1np+zMYvs/G2sjTDiUeGz48ioiRaJrSsFmMcTzRHkPe/q6rDg==,iv:A9iSL0+7/mqBPXnnqrCthoegvBMKXEjEZTZAwuBrGYQ=,tag:yITc6juQCVq+tQ6mcHpNag==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTVlHd1gvL01SWGR4RTk1
            QlM2TzdvUExIdk83K3JFQWluenFqQ3ZHUWdFCndNbDJZL3kweUQxUzNrMmk3M3Bl
            YTZTTzBSclhLaWh6VE0rRlB3MEVzSUEKLS0tIE5FdWJkSkFNV0FLL0ZCTG9vZk1x
            WUc3SFZyekVPTXc5K0lhcXBMRDZoQjAK0/a6MEpVlG7pXjcxEy6L3jrxipdQuTwU
            ibauqZ8rzswESEmOYrJIx/KEONS8pDirXUQpgNBEVYyy46V6AGMJ/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T17:58:42Z"
    mac: ENC[AES256_GCM,data:OqsbLORHfDySEahODYbox0ohxsgBKfnjuX+BN9iZa25uDTYxXXFqmtLrF3MX0bIy7djx5zuAzd7GVa2nNdqQrKMYGMBjI5YEKppIwj8cBvwmf97GmzED4v1Bnc9ASoTwPE9hyjO9BOAFBz1DUdyDCIFbLcPIG7bBgxT6RZfa9JI=,iv:mSuQf6Wu0YSYyhfHfLfibuFylPYLzV6aDy1ZkVBKUcU=,tag:ooiP6Bsz1i+bkfaMfYq1RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
