apiVersion: v1
kind: Service
metadata:
  name: comfyui
  namespace: comfyui
  labels:
    app.kubernetes.io/name: comfyui
spec:
  selector:
    app.kubernetes.io/name: comfyui
  ports:
    - port: 80
      targetPort: 8188
      name: http
  type: ClusterIP
