apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-secret
    namespace: crowdsec
    labels:
        app.kubernetes.io/name: crowdsec
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KxOPOxxpobedBMe6uuzL6v/9aC/NnpPTKRa42lyXI64PgV9Dgg2cYa7B/d81+CTWAuh/tNs/VMjIwqJywiRX8nPSQPgm+wQFGguwfZOzS14=,iv:tLorPVRZlv2Y8a0CfkONz23g58P2ftTjDVQ/88Qr0yQ=,tag:T+9bHHIcjc+8eC9h5d90XA==,type:comment]
    #ENC[AES256_GCM,data:NW4HfJfsOCInQ/Y4LQfXdWOnavCEumYCjQzfiyWlumOcxzLjesbR,iv:XIzEdCXnOf3/H0Guj0BasMJ0Eqfi7Scs98oymNDm2CU=,tag:e3t4sDT/m/31pNXGJn7vTQ==,type:comment]
    #ENC[AES256_GCM,data:hF8fscL7/RL+3LFnL6kZPSrT855oyKaaX0qJTMA/b13lPv3y+pka7wnrGc7ezvD9XbgX,iv:nsjw065/uDBT2S6Ruvv7Gq1GcVD9THPlbD9f3FowRKg=,tag:Gc3z53MYw7xnGe3AUVoQfg==,type:comment]
    BOUNCER_KEY_traefik: ENC[AES256_GCM,data:egVU+/3vkW3dmIoGpRbxP+RT4qm6UiVkQcQ1kkEGzfz1seM19Aki/m+sh5Y=,iv:ZRLTINEHyD9CyntZFwhuvrB2b06QwSt0TZC1gTOVbCI=,tag:mgU7UYh9c12/pbe+W9m/PQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VExkWDROYnpWRUVPU3lv
            dCt2V3N5QnFBak5nOGc0eGUyQzN5WnV0dWl3CnFhZnZIRGRoU0hoM2NTRFQ0OEha
            K2h1TUxWUE1vSUMwYi84cDFXMmFJS2MKLS0tIHZES0c1cSt2Y0RzMkptbTF5U2tO
            NGJaalN6ZDFqTVFqRm9vbkxGbURDTFEKTijEADx7KyfwpHFW1owWQGL6LReUrp4p
            2WGnKtFcNctTPWaVTM0q3nejuvAHBx+C+JsxK+fhMZKKsrPHDxnufA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T21:07:10Z"
    mac: ENC[AES256_GCM,data:UJwddiUPk1ki9BbXd2P9CqhPWQ43FddwgsbGHf5kVkLHgxwQ43ajBJLzIJbURdIO49skVhfy9f1EWwd70FBR9YYnmuDCEMSqx/a0TDQdVkfFi2lDBGA1MKStJA5QkEQ83h2NDSiG3DJFTeZttUbACmQhfQqb53YpGKBDRHN3uIM=,iv:8TC20mJh8mK+keBRdsIoQZA2SiojPexHeRCxRzRC9xY=,tag:dqJuYOKhGcdPZdcc6yyz4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
