apiVersion: v1
kind: Secret
metadata:
    name: langfuse-secrets
    namespace: langfuse
    labels:
        app.kubernetes.io/name: langfuse
type: Opaque
stringData:
    #ENC[AES256_GCM,data:qDP3BwWrWixUcercFUOlJLKfcKa5g5g49iJGkgWpU/w=,iv:yJ7lhG1xPHcceqg25lRaG/0A5RFM6kCOHR+Yv6XgHQU=,tag:A24HSZUL/T3ISdMGjVI0gQ==,type:comment]
    #ENC[AES256_GCM,data:okP9QdSx0p28WEVir6LzkvBpzt8kcNqdKTikrdUbjkVm+DG3rOQLkLzbWg==,iv:rqyLPYMalFav0V0qE0lprYMvKjdtl1vpkt91dGjy144=,tag:Gxb+jw6J6A7mewZNUqkmyQ==,type:comment]
    #ENC[AES256_GCM,data:FPlDgihnV9sq68WrUrD9YhFPFuiWnlrhYrxIrOCp5xmqJRxM4mtaOXTn,iv:5kE7kXHtNREOvKbeMLBAftsh/XOF7UnZmT2jvw08IfY=,tag:FAI4aBBrETV7ATIsgVRAIQ==,type:comment]
    #ENC[AES256_GCM,data:Y/cpn5HOmGFPUcAfxo/1wn7Vkv2jxPZhxUuHQMq/kxtvBCGZzMAwD1DVNz8SVEiVQNYDkotOdTRBd0plNafASjDS5vYgO1yl50cK,iv:UvUMh83bpEGV+uHjuCRGdDrngH/eQEKz2F+n+SrWgq4=,tag:fb+K6IwMkVoRiccbf9kQjQ==,type:comment]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:8RWom/WTK4go0Cm3mkRGsM1g/B/FlLpzeRgthK36S6/HnS8Msx3lh1ih0vo=,iv:i+8Mcwz07CXxLuvTtWsMrZxUB38vBF8h6Goc7uup7a8=,tag:nBT76Us6qV4wo5tpuL3ajg==,type:str]
    SALT: ENC[AES256_GCM,data:TZssyGcgy+rclFlC5z0EQu8PP8vELAqMmyHfzxXUw2YyndYaWtiAOA1jRFE=,iv:WgjIIkXSVrGy60yt/gb5drCoIa6k7hN3bdOiD/9Dc6c=,tag:MJwGwwyxK6DjP/SYvz6epw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:jSIwMrptQTQy1dzXJ232KU2eK6coeNljZZ3jWp3jeIwD4n9iN8tFw/xRferz4BSqf6vHTKcVajElN3rErLYuVA==,iv:ZRdJuooM2pPw9YjQrtzKtw0yL4+gFOb700mYmjh4KtM=,tag:FTwCoewjz3KVJc7L/qFJHA==,type:str]
    #ENC[AES256_GCM,data:Neiv9VJ4VryXxAjcqz/lMIQozC7aRwFPYk6/IhfYz+1UTl6drugvRWSscYxjtrZiYLjOsGVStGyK,iv:TM8K9+lVX24r6UK7e/fFR3Ra4tcM9utCH5W4mImOBA0=,tag:Am/40F946slT/2YR79Cf3g==,type:comment]
    LANGFUSE_INIT_EMAIL: ENC[AES256_GCM,data:g8QkJZYmyF6VsmKG,iv:EwlifmmoZ15kv3FuOhqPRsX0AH+fTEZESnvotr5ZSag=,tag:iUNK7MyDSoqx0AndaAkeNg==,type:str]
    LANGFUSE_INIT_PASSWORD: ENC[AES256_GCM,data:AuMypHH4fKX/jkJoDXlsSkDTwtBGKS4=,iv:ft82tkB8/+ItW35YE75//VmhVpv8gB38CHf7niiaGxI=,tag:eVP1U4bz4iDTEp3f5yXbuw==,type:str]
    LANGFUSE_INIT_NAME: ENC[AES256_GCM,data:qwI04/pO+A==,iv:a/fDMRUfH9vXZRBsnQh9C8WTghdpDix11K0fyS2dC2g=,tag:OP1OVPOX5V7wbLTistyTJw==,type:str]
    #ENC[AES256_GCM,data:QMFEUzMYYgIhfAB3Wk+zTM767+JNNWiIKRQ3JKftyCYblzMzBUzZnAVI4gxsSlX90g336y8YOtaooPtfwDPfK1L/Gwc4SsIWZ7Bk/TQv3Co0hmBh,iv:tozdyTajEfpd2jnMI1bsjQKYYYKltDaqLQRvoqEON+4=,tag:dWeSzW7/TOihPFTFoqUwmw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:uJnxTUgL0lyaXxehKSArUet0U4Sw6RKCCIUUJxb3,iv:FWJyCxApsbnlCB4K6+FA65KQjZz3KF9kqo8GB7CMFnE=,tag:lm0XnSd0qpgcPSEKl7YegA==,type:str]
    #ENC[AES256_GCM,data:3yAc88pdeQMtmQACXTL9JNvHIQixSfLqX2lFsrsSAu5gmVVK8gQslul1Sa17tek=,iv:I5tzvhQ+4ODiUO7QNjieTNcNEJbMpDOi/G8Gr334WC4=,tag:FmBWYjiF3nJw4CEc2AqbOA==,type:comment]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:51js46CkyLKXNIbDXt1I,iv:Sa7h3Hzevc42AOZ3u/9QuYKweaGSljGZTRbsEj4Gr/k=,tag:9dfo0xuS70StQpzIR/SLfA==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EEgK9z7UkzHi3QEpnM/BsBJQmvMK61nN69N6cHC2qx1pM9JX2atOKQ==,iv:KUMlpBGBng6KFlIpsdvdg3hd/UokmAmvkgBneaKDsIA=,tag:fNcFT6kCFutn+tYLasMGtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETnc4d01zL1pZTVcyK3Nv
            dGNMUUZ1azZUcGxvbjN0ejBIa1JyZXNvN0U0Cmx0TytCS3lZTXFrd2VPWHV1R0Vr
            UkhxMmhQaHVybUZTam9Yc1E5Q3BhSlkKLS0tIG45eTBvWlE5aFRzbGhVa0xpWlZ1
            bjhLK0lnRE1GODFuYUhJQ1ZqbTVKNk0Kf3NUPV7n9C37vkkE+tLLwhAB7VA1GqtS
            Xq0QOVPiBNxURZliPbAxxm7SgG5w7qPmFBlohHPyZaYf16Rue4plrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T14:19:13Z"
    mac: ENC[AES256_GCM,data:sj7vpzjeaJFG9ggQaAJuAEpweY7u7u7IY/XktcTLRjL11kQRrH2TpYgNS7bIIEv9MAlG84QRIJZnf7cdf+kUi7GUxiEi3XZRHZYiJX/nQCTGzADyHcC40jhZGL62L5xv/CSak0P3ocx1MKnmiulbRcTVlzqFxWQ/Jwee5jslZfQ=,iv:gzRPWIvpYTd9vUABhoRItwXDCDkdT/n6vzS9NOP8Ybk=,tag:7R+AuEGSwqyGfaivagXOAQ==,type:str]
    version: 3.13.2
