apiVersion: v1
data:
    token: ENC[AES256_GCM,data:zFojDVsEIjyJ3OLjctPQRclsoSFD/Aq+osblYoQM+QHzb9OEKUW4s0w+PEg9WL9zaZmXobLSxj980SdsDdlCER/EWlZl3oOeb8i+79ioIu4y19XraSK+h/gIUkkbGafZ9skj8jcv537S5K+MHN6rezxZhpae0iJtSxuLlY4yRlsTlUUucVR+bvg10ifXf/rI+LV7kxibOsh6NVf+fuCZ9F3h3FFB0kH1qqwIQUA5HU5ALi1Onj6nNkTZcMpS2kE3zOaglUHXZwK9d375Er+KtSTJm1ZIqfN65uP+Focqsbs1Y4ng5aBFfIZimgCUn9oe,iv:uDiTgJFqvXxL51z6mXZJ4ytuLxZN8BilEDYNHMvz7Ac=,tag:3TQKt30MUhHUcnYNCldRUQ==,type:str]
kind: Secret
metadata:
    name: cloudflared-public-sites-tunnel-token
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY056TFJJV1dkOHpYTFJD
            US9oSVNQcDV5dVVrenUrZi9icURZc1diMnhzCmVtQmd6NzFoZ1AvZEpYSjdIaThp
            Z25ZNEZYMkx4dFNPalJFYllIb215dGMKLS0tIGtiUXFNdVJoeDcwa203UGpmeFJY
            YUR5dU53ZnNXNGVOM0FhSmd1QU1KblEKm6Up6NnzZRZvoiUbQU+IDkeIv2TwSUis
            Yeg485sBj8eXWIs7t23pPgfN3JIVbAk2uamtHgdM9fauMma6lh8Glw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T03:19:07Z"
    mac: ENC[AES256_GCM,data:6CyUj9gQkDNLVEJuLy29/PRVWNGqwtDhzE5ISKxDs962avvrEuulS/sMm9nl8/4ms38jHUiw1Bb/BtbNKIIE0NUg8vy5hk/AmX3Cb8ZhcAytRcHDnYBBJ8XmvElw+pUAkD8BrtenA5bm4ZZK0TRGZsmOGb23beifjzgTdXsfAqg=,iv:iFyyAYLiSOBf0VFh6C7zHDNN9kg0Fs8H70dKqKe7l5M=,tag:LOxK8dbv25mT6+aLUSypiw==,type:str]
    version: 3.13.1
