apiVersion: v1
kind: Secret
metadata:
    name: gatus-fleet-token
    namespace: gatus
type: Opaque
stringData:
    FLEET_TOKEN: ENC[AES256_GCM,data:EaA9LvGZ3QyPRjvAqUAHBdQkKdtrQFQHiGHIzXiPTgrGp1Gy0QvHvA==,iv:W6m80//IKbT2wWAuMyTeZ5gzxg4hkdqFH3SYNkOODcs=,tag:rzO6Ui/pd6WUX3R99t0Ffw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UXVCT2dEbTRjd0lhOWJI
            K04vWkF4eTgrZUFmMjI0K3diRHZHZENQWkg0ClRDWXptbU5FczFBNG5RdW1HZlA5
            L2hsLzUrdjhkekVDdUl0aTFNUTY4YmcKLS0tIHdJb3BDeWxvOG03TGt3cWhXUWc1
            NWdwNFVsSVdjUWc2c2poRlI3b3lkYlkKP+4Um7Z6QLvfaj/9U0RHiswCKuJyCG19
            x4YP5b/NgUKS9c7u6DxCm8kLJJ9hWM0f9dSWGMtn/3xNCno43XgBHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T23:59:20Z"
    mac: ENC[AES256_GCM,data:GfJdSA6znPzuCKGY98BTC8mUD5r6tYCQ1lweKSPpJ5CH6ilNBa9iH8Ttc0t47bbe1TJi31Hww2ZBy4vQvZ7YgDDpOQf64hsNaRai2tcjHfBBqXYT0t81mHWPCadrDzqYNeND1OHUPEAdYcgMyH1jBrj+i3ZAh/IB54HxHjYsgCM=,iv:fzvZ0ss+8U3Sv8mEIwLnhOeP2do4mqUEvj3H0BZ1tlA=,tag:Pc1Qwjxp0NzYiTeHj3cu2A==,type:str]
    version: 3.13.2
