apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: placemyparents-preview
  namespace: placemyparents-preview
  labels:
    app: placemyparents-preview
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pmp.preview.blacknbrownstudios.com
        - api.pmp.preview.blacknbrownstudios.com
      secretName: placemyparents-preview-tls
  rules:
    - host: pmp.preview.blacknbrownstudios.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: placemyparents-web
                port:
                  number: 80
    - host: api.pmp.preview.blacknbrownstudios.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: placemyparents-api
                port:
                  number: 80
