apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: placemyparents-preview
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:MsIyzOXrr+OT4eVIF0H3N9gpRAXRYBX8Cx+h09JqXjHFbbom3yKox3vi/qHwaXLpQRzX34+TVQzUO/zC32+bPidq17hiG2WMM293fEB+7wA5KwvXzw0X+4tmOJi4FpK5/ur48cx254kaWX9n0uxKfDKYl7PK9d3qSGSYyK05AeQY/Wh5vXsDXwGq4Ud1/3t4zneRDgPRPh2tZSkAT+OGVj5Xxu/T8t2GwvYSXOsnuwWctgESV4pQXA==,iv:oMxFPwG/bdExCphQaHB6+c/QlRfgb2WjVXFtC/7P+Ig=,tag:sAOtYXcflxmOBs8UQa1e8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJczMyMkFkeVMvbnhId25W
            YjhBT3NtRG0xRUhHMU1kZXV5ZUtXc2VLVEJNClYyT2N1Z0MrUlNhL1htNDlFWmxL
            cVRSNEhZR3pyM2owcmdvTFc5cytqdGcKLS0tIHh4dkxmbm5TM3NPekY5MDNMYm1w
            ZDE2TDc4Rlc0YXVuMEZXeFQ0dXRCem8KL8IgfKihed3MXR3QFJa3Vs+nu/YLfSFg
            jfl2vj2F6Wh+HEkOyAIHHRstvySrmiIf4/9k7BuySDmoAieP3+giQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T15:22:13Z"
    mac: ENC[AES256_GCM,data:jxfFnVBTW0OxdJw4sC5J9jmd2121eWl7/AZBc4fnfBDoHkuduIusaZgydbh1cYyvquI4rBHRmo/2pi5Z+Vq5wDXqjQt6sUQDAddhznDbsXLddT9FWpm3EUz5hgos7D6Id+xldcFb6piL/ChzXNUHdo+ZJ1s3hgETgNoHTYyThSw=,iv:HQNnD8St34j/HdHEs7YX/pxhw95lA9ReuzeSCzvm/So=,tag:KPbsbOIR29AenO7df8/MOQ==,type:str]
    version: 3.13.0
