apiVersion: v1
kind: Secret
metadata:
    name: placemyparents-postgres-secret
    namespace: placemyparents-preview
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1tYxuYTxLVAJfP3Y4Kg=,iv:9FG+7M0QRqIDM/gpKkAwt303Ek52f3L5pCzYdspKEr8=,tag:ELlGLwD6/hqey9f7hCwYtw==,type:str]
    password: ENC[AES256_GCM,data:UJJjbJpPprhGfdr4fM/xaYn0dAvV6szvWm9B9YenCrLzLuCeRi4Y5pq9I+Duxkns,iv:cnGeoV0nWM8aOBcy6y8n6Dq6Aqzg8Miot2MLhiDsX6s=,tag:QzPRNahGVGHuw7gtQiNIaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSnh5K2dzSXhoVWdBMkRo
            cTN3V2pyY0tTdXVtWlNMNE9sWFM3V3RoUW4wCi9TMTg5bUowV0c3VWI0UlluOUZZ
            KzZHUDB1M1loRVE2Y21ONG4rWU5EeVEKLS0tIGNkUjNoT3Joc2NxU3ZibmtRc1Zp
            Mi9NVndBVVpyNC9OcGdpUGdUZCtRTmsKwzhqd8A2EwMi8GKPWpv9S50jaYTJHwwP
            IBJFTyDNb8x0EKUnl1NjRoXX0a52IunbtgKU7z/HYEH3aOw8RLW6VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T19:13:16Z"
    mac: ENC[AES256_GCM,data:m4DCVGWo2iJge6s+qERN25b9XlLC6zpZqzgSFtumqm9JnfdOlrA7fxtZ7ruW/zT3/ftBMLANl/J6TplxIKKsi5VpGYxQXTwYb5Iz6j+qpqgvPZEf6VgDRTCYQsbiHOlS4H4oKtCHzvR00TXCA6VRpPE82sbfhuJ8gmQY8KlEnEo=,iv:rF9DtjO+hFbEQops9M29JROvb5v9jEHQpfudk1ZHBMs=,tag:9MTaMJO8Q2JVeVehMGKZMQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: placemyparents-preview-secrets
    namespace: placemyparents-preview
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:39AnHPNMc2BCWARPD2vIozhKkjqcxp2qVpbIF0WDhGbUnqIkhWW4aUL1U1HYb027Uqkln6urkjWx6ureTUq3NJN7Fwt88jhfu7AqxM+xaxa+2sAxkNqLTj8YRbRT1DeQ2OqBV9wIfNK4X6l107+4qW4KsFI0Gqf63a8Vi96Ju3vtIsnPu6u66sHe88GV2Evvjtk+2+yJAMvDkDS8XMIKe1r2mPBPmJUxcA==,iv:DwlitF6t8u0/cgwlHFcGezvX1gu5uU+9naRyc/5DcjQ=,tag:FyYAFLTB7hyGXKpuDa8xmw==,type:str]
    jwt-secret: ENC[AES256_GCM,data:caOaTRGRAPrhjbyNeYuZD8+QOA+ykijzPfvCGLXFpcoxZIcwhWtKotspQFRfO/0aY2NyPYVvF3uorTZVD0CmMw==,iv:sK4VpOI3tbug3U+8/5XcTAsbjut3Rxs0cyQ517lJ8Dk=,tag:0csMt4my5PLcLy11j7axvA==,type:str]
    square-access-token: ENC[AES256_GCM,data:Kjo+AiRCLF1ki4GN7s6UgznihfXgp6eKZEu9Pum+8r8eCA1wPvZPbLkpoB6ZS4reF8xU0Dr2Mod3vt+3rL5Bzw==,iv:4HPpycupCcmPuate36GH+4E/6hd6UlzJV2A7mWrJqJU=,tag:sw23lRfc8XTz/IfUBq/LOw==,type:str]
    square-application-id: ENC[AES256_GCM,data:rUIAy8oq/hW4o4F+kqZziFhvfaLQwKTWr1y+NSt2frBv/KmGaA==,iv:qpeQ6mFKdH65aYese27TYD0TVXL8mDt7JwgwMp+Bvl8=,tag:/R1p7RFdju61PwJVidMQbw==,type:str]
    square-location-id: ENC[AES256_GCM,data:fqGoO+q9iIQGKj/lTg==,iv:CS1CBXBKvSPlzi6UoWqy3LD8X4tNuzwFIC28yKQEzzk=,tag:MNHtB1bj7pE+HBasjQiEJA==,type:str]
    spaces-access-key-id: ENC[AES256_GCM,data:BLwxbfVkXsn8XUMwPHzZ2Q2KU/0=,iv:2b56YWxKd61v4x/ffOYv4lUCn0pPj8QoztTJFlrjn2s=,tag:8g2AgnGNTEH7PkqhndS/1w==,type:str]
    spaces-secret-access-key: ENC[AES256_GCM,data:Tv7rP93bbOB/qU+3x2oOoow5DjFryabXgE77ExGydC6K4Elia1qHShK5Qg==,iv:/mjNK9JXV/Y/AlGS+5oMheDxW2Q3o6DevPwq+Vfck28=,tag:ZW9CuCGSVIWW6FaTdlubAw==,type:str]
    google-client-id: ENC[AES256_GCM,data:3+A8srADZ5RzI6Ky22iHma/3TxDVQIWaPuHNKbfpet/FKvZtlSXS/ES5/yZcJxO4Vb0HZ1/XOaz6if0zfjt+XXFplG6NSJ0r,iv:F/UPMCYpUU0LtTjd6IF2jr9A41tZxDKydeJJah6++hs=,tag:zFyYMWT00uqYof5PC45pSw==,type:str]
    google-client-secret: ENC[AES256_GCM,data:KF5LRnbJZ1SeTSn96mcpW4jKfSdhCvNJttP3kqKtLr8GQZQ=,iv:RjxiWfomDJOl09c5mPZrl2Nl1vFw5+rMzNdsAyFiZgU=,tag:IZBSfgd/Gs59sBNoXAy8aw==,type:str]
    smtp-host: ENC[AES256_GCM,data:K6YeN20nV0IGNv3mx7JN,iv:vJOBVvBrb6+DHQdRGO6v14KJKo5dEDDr4OauW8ZZobc=,tag:bUZYL28yseNWtpZXAd5wXQ==,type:str]
    smtp-port: ENC[AES256_GCM,data:KdaG,iv:z8FU2NPII0A80YLnwlRkk6TAMa9sMK/1+e6oIa33i3I=,tag:c0Koyo1XPb6nJ33LP+jrVg==,type:str]
    smtp-username: ENC[AES256_GCM,data:5IGNYX/B,iv:u326pXlimWXzedLU4y8JeO/k86aYcZ8sM3MU+CIwCEk=,tag:6Xoq5TmR7u3hWQO7LfM1yA==,type:str]
    smtp-password: ENC[AES256_GCM,data:sdz8Wr9hoDuBookWAdRfwjYArnKbDUdDoLc5ir+UPBh0wnj2,iv:csAGvkkVYC/AmNFZkpIrYSg0iZicO10OIsEtA+OtNhQ=,tag:CINnxPGTSOjsTfTQ2d8v8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSnh5K2dzSXhoVWdBMkRo
            cTN3V2pyY0tTdXVtWlNMNE9sWFM3V3RoUW4wCi9TMTg5bUowV0c3VWI0UlluOUZZ
            KzZHUDB1M1loRVE2Y21ONG4rWU5EeVEKLS0tIGNkUjNoT3Joc2NxU3ZibmtRc1Zp
            Mi9NVndBVVpyNC9OcGdpUGdUZCtRTmsKwzhqd8A2EwMi8GKPWpv9S50jaYTJHwwP
            IBJFTyDNb8x0EKUnl1NjRoXX0a52IunbtgKU7z/HYEH3aOw8RLW6VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T19:13:16Z"
    mac: ENC[AES256_GCM,data:m4DCVGWo2iJge6s+qERN25b9XlLC6zpZqzgSFtumqm9JnfdOlrA7fxtZ7ruW/zT3/ftBMLANl/J6TplxIKKsi5VpGYxQXTwYb5Iz6j+qpqgvPZEf6VgDRTCYQsbiHOlS4H4oKtCHzvR00TXCA6VRpPE82sbfhuJ8gmQY8KlEnEo=,iv:rF9DtjO+hFbEQops9M29JROvb5v9jEHQpfudk1ZHBMs=,tag:9MTaMJO8Q2JVeVehMGKZMQ==,type:str]
    version: 3.13.1
