apiVersion: v1
kind: Secret
metadata:
    name: placemyparents-postgres-secret
    namespace: placemyparents-preview
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Hk1sl9wCP2T/rwvyL/U=,iv:fTldsWaOkGNeJEt7x8Z48z+xAUcxVgU9SS/bEQ6CQuI=,tag:A3jXQxCZbjqcpLFObFqucQ==,type:str]
    password: ENC[AES256_GCM,data:BnVygkaht0oZxiPi/jXQxVuDc8FplhNwBHDGKruuwE6sZ5l+lpx4EfzM5mvzo+mq,iv:56zEKtDS6mDwn1EDsamCcvaFPQGNuwIDj/1egiuuElQ=,tag:V7NjdQ2OjtYrOc6UumdDkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNGJlL1ZNMlF4SkxJeFhJ
            NldXdlRzckNhWmZxcjZjWnFBOGNOaS95M0cwCld5c1dvYjg2bWpJQUNjZ2Y5NEZp
            MVRPcWxNT1EybktBQnA5Z0hYWnhhQ1EKLS0tIE5HVWJMZmVtcHcwVEdrVWZhOGNW
            NllhWExFcXBJbU1vKzgrSmxicnByRnMKfehK9xc7Y6A/iK2MymHkMEFczO+OJYck
            J5efvbMyWFwkvDfDW7oVXJ52Aq6OYjsFewSc3YJF4lSOYH9B1aLq6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T15:22:29Z"
    mac: ENC[AES256_GCM,data:j12Viyo85HIork91sVLDEjGY3c9gF7rFaZ7+EZys0YvVjuDpyFlh545Urr5/9Do0xZuQXipoj24i5vj3uihBTAcKaTBU7ZCN3FBzdVlaraD564uN5108+cCEPxhVJosAvyKZa3f6mJTRRDTonrfBQm0mZeKqeRa3NIqd5hEuBVU=,iv:iAa1dBa/oUrGolv75FlCuZflyb5TCCJPTbdhfLTbZ8o=,tag:n/pyJJBkJKCH7J9s1Uz1xg==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: placemyparents-preview-secrets
    namespace: placemyparents-preview
type: Opaque
stringData:
    #ENC[AES256_GCM,data:SBU+NizSyWBKmrFQ488Yg1d3J3anboVsx4JZPkLWdEgDcRYclE5XHAXyPNeAAAUrs9PE+eRqjIMKQCTPUeqlbts=,iv:PM2NWMmOyS0y0U+3WMU6ErpuUwXfoASnp8uQqLV7BdE=,tag:D6HknTife9b5pJbippr2iw==,type:comment]
    #ENC[AES256_GCM,data:IXbQ/HjgO+mWdTMaicTkVdJ+zMaUwWfPYNpoHu+Pjzz2MIQEcvJa4aWpzl5GBPCgEMBEt+9JkOZwiqM5j4EtffOuiA==,iv:cry/k/fLV5uYIY79/LoJxvLYeme3uzKq/iD8WbfK7DY=,tag:Oh5+WupeVOx5OO06GfnAwQ==,type:comment]
    database-url: ENC[AES256_GCM,data:k2iYwC5T+3Me0Cd60iyBq82LN/cdk8RGF9gEieru8uOQj5WMRYQauTCZoFGjcPrebSb6V2l+H/wmRuVnxk+3yBRNw3eBgaiMnYk1DCT9MrHqCT4iJcJmN4PJKglF7UZvlIrJo3wX3oEEv0qsnNqxXE9Jb36v9qfLuDLP1lcU58icOdW9WdS3EYZbWoLVea+Ww1YU0Fh3MJVskF9KumU2PIS/jMQtiTtbPQ==,iv:+cOra0wYqitKNkJZrSe5bfdbCQTkzPKBRLVK4s/X+lE=,tag:UcZKss5yr4nWyopmzTt/iQ==,type:str]
    jwt-secret: ENC[AES256_GCM,data:tWtc98YDwDFxjycavmwCO8AFoSWKf8KUNhxjJA59606dNXMkojMjSq8+MW6oXvKJblnU5VQxswaEqXFuk4Y57Q==,iv:OhHIIGaVvnSKbRFc/u9k1dhlqvZNujp9+DkfGEVJCSE=,tag:6oV+ADy4SYnCz9dh4qeUCA==,type:str]
    #ENC[AES256_GCM,data:LDMZOQu6RZQegmozcjHOUbbQQBW13DTiqT/eA0NIBxXLEzquxhuNg8UNHIIxRO+bGeDqBhdSBPUZ2UuMDOObsoo4WTwboYmgMDVt,iv:NVNAo32s2cv+5g8PjoWSH5x9t5bEYdaVjxmGU57e1VQ=,tag:bpivruexADC2cUtVG3KrZQ==,type:comment]
    #ENC[AES256_GCM,data:RU8zQKw2s/WXlQH6BIZfGX42CftYVFkaSJZwkE+ohUrwzELR0bwciosWludpEVG15Ffk7J3FUFX9M6Iy65gl0DJD,iv:Y+ZDXxvI3yJ+VOXJEjUxd+zfFZoUYf6yABUdd8Ubwhc=,tag:vjLIrlTu16Jl5u7WAbaPqA==,type:comment]
    square-access-token: ""
    square-application-id: ""
    square-location-id: ""
    #ENC[AES256_GCM,data:vLu/6uvMTgVC5deKXwynCI4uCBg0QeM63M2xYTV06Xyy+HAz8CRFsom9AvlOlV1UwUmzBAInIEEzqPLzoXEMv0PzpWoOAOsA6Du/4eQ=,iv:JSST5S0gKYVPv3fz+9XYccXCyNce0UF83WgdZD//6J8=,tag:vtQ5NjhA0WqrFkhDo9rnEQ==,type:comment]
    #ENC[AES256_GCM,data:pnExPrHQrF3wRPnAvmdYUcbyKp1wjlozb3cOLR6Nt9lIibe9TzrHLtKO9b8rWExGtbpPCnn60qQFfSHLHG8=,iv:LlNSRthI05WD+qOhfizTW8qei5n0h8xtF0XgvznlF5c=,tag:bk0JwFmo/HZlwSk4QU7+3A==,type:comment]
    spaces-access-key-id: ""
    spaces-secret-access-key: ""
    #ENC[AES256_GCM,data:IyFfCwffuNFIdgF4gCEuYx5+XIfw8t9myGFg5NRgAQAC/lll+8OZ6qgF1LUFbkQJfwZ6s316T9+Q3YgEqbOsX+M379u/pA==,iv:G/D1W/Ai7z0H5Dh0ivdLsg6jl0l2wYtYcPeJ5VtATqE=,tag:RyrYTcs91lrmqwu2Fp9fyg==,type:comment]
    smtp-host: ""
    smtp-port: ""
    smtp-username: ""
    smtp-password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNGJlL1ZNMlF4SkxJeFhJ
            NldXdlRzckNhWmZxcjZjWnFBOGNOaS95M0cwCld5c1dvYjg2bWpJQUNjZ2Y5NEZp
            MVRPcWxNT1EybktBQnA5Z0hYWnhhQ1EKLS0tIE5HVWJMZmVtcHcwVEdrVWZhOGNW
            NllhWExFcXBJbU1vKzgrSmxicnByRnMKfehK9xc7Y6A/iK2MymHkMEFczO+OJYck
            J5efvbMyWFwkvDfDW7oVXJ52Aq6OYjsFewSc3YJF4lSOYH9B1aLq6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T15:22:29Z"
    mac: ENC[AES256_GCM,data:j12Viyo85HIork91sVLDEjGY3c9gF7rFaZ7+EZys0YvVjuDpyFlh545Urr5/9Do0xZuQXipoj24i5vj3uihBTAcKaTBU7ZCN3FBzdVlaraD564uN5108+cCEPxhVJosAvyKZa3f6mJTRRDTonrfBQm0mZeKqeRa3NIqd5hEuBVU=,iv:iAa1dBa/oUrGolv75FlCuZflyb5TCCJPTbdhfLTbZ8o=,tag:n/pyJJBkJKCH7J9s1Uz1xg==,type:str]
    version: 3.13.0
