apiVersion: v1
kind: Secret
metadata:
    name: placemyparents-postgres-secret
    namespace: placemyparents-preview
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:mjHr5lPfnP7herOnlyU=,iv:TsMQhwcAPGE8ye8pAyoSDIQ0uOjFsmLn7/GVxbJOsOI=,tag:lf20deZ8VQZesOnSEizNvg==,type:str]
    password: ENC[AES256_GCM,data:32X87KX2FJfPwtq+J+a/n5oWnl2fyG8m3k8ndBFmr5sobDMZZKPLsBPMJES2nLtJ,iv:B8hZTEcXadoa8kCSadcLtYTDkel4puBQ4NuG86IxG4Q=,tag:QIyJTAKNgmKBIn+Q9c67sA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd1l3ZWdoZXBua1V3cDZT
            THFzb2hPcEtvRjVySTB1azVoVUFESXlyZVVvCkRibzFSNVpsZUVZZHhCQ0l5RGhD
            cDRrZllTRlMzby8zWEJWc1BtNkk2bmsKLS0tIHE3K1YrajZtbkJIS0ZHcmhpcWNV
            empHSW4xYXRxZjFwQ2VFMnRZZzZ5dDgK1byU2XcBN5118CuhvEZ0lUXC7eSNqN86
            PvMlJrs85bRIXmEhEp9nBx0cRHORMRYvMa7aL1qlYLt9goeajuh2Lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T16:52:15Z"
    mac: ENC[AES256_GCM,data:10ZVQgPqQP3fjuQyYYstT/8n4T0q1XBdtD8kjxrI9YNNrp6qf2Ob5g7Mh5QjB+MmY8qDa0bNyeGqtib7UCqMaShI8WDH/yfHzMU5amy1wIn8I42J0DdxLYNU9NB6fvCvP0D6nzA4Y57hN+F5E/excmNkvwinOUIq3dwvICNP//U=,iv:loURZ6mDK2jxA7n+SjQc14K9fd4YBJAW9GDRSr79jnI=,tag:+W9w+NxobbTi36vMwFaM8g==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: placemyparents-preview-secrets
    namespace: placemyparents-preview
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2tRIpoDv3dfCEK7lM3yige4yVXC+g7HU+dEQkkz35GAfi2AEDSnW0azBZ1VW82kioQsMGi++CmKw51UdHDoLXCs=,iv:ILVfqqWLj6qMc3CaE6B+aAjcnbxsH+7BRFeUBVCtfQ0=,tag:zV6Lx7I1+kxaM6kvFbWMvg==,type:comment]
    #ENC[AES256_GCM,data:mWPqnIVZbviG7EdGn6UTBOWvslcalC30AfTV08eHjmh91kTd/eIT0Iai6VT02jwIpjgBlr6qWfZAkChJd8yrHpsvcA==,iv:/P04whebbKe5jHpoOseQlVIuaA6WraeJdRj11IkvOrI=,tag:2bfOummEJLt8SRM331nWCA==,type:comment]
    database-url: ENC[AES256_GCM,data:jpOSlchlBglQ9CBofkXOHozRLSoXVSuk1+3/r49fJmXd0esPtstxBYJJElXdlYmRvZz5LXPjaaeoedszrQXczo6vJEX3dGhTfj9aWWul0gCO2pHUhPy82+5czcY10fKq3EUuEQgTPL1suKAY+n/Vo5T31tKlbqLCV/lUzfHbEqaLZp3RYu+pDkV2I/S2I0gS0xSTZx+5twypaWUVOGjGeG1/dovxc4pAGw==,iv:qpUbx1Ic5ithxOoyX/rBZvEH5/d3rI3oqYQ85QdnGq4=,tag:Jq2SsAcs6vniW4WT8yjlEg==,type:str]
    jwt-secret: ENC[AES256_GCM,data:vt5cYdzZt3pvWV9NVd8gTTPPrDPk37+dizzGO0GbdWMoTeM64Iwm1TL8+fWzE/a0PpP6s+X/p62AffGkcRET2w==,iv:R/LGm0XF692HkArezN2wPzuxtLcoUHu6EeNArJXMBTw=,tag:hODr1snOR3j8o6HFzz3TxQ==,type:str]
    #ENC[AES256_GCM,data:gNCCjf48xLo82mAIlsTkReN5xqHjq6BBAq+z2ADEbm/9BqjzrSLxNGN0NTSHH71WGc3tCZTv2umF7jPlKapFYgLQ2rqlgisD9JXY,iv:O6clJcfG9SBrEyWL6drr7P1gCpHUYtF0PV+McodBrb4=,tag:O6BCqNPsJq8SfbZaoCzfJA==,type:comment]
    #ENC[AES256_GCM,data:4ja7X6BjtPciWIQdWBKLbZWOPpdK2ApI2p4ZN9svZeWclCkL4Er8dLbF+JfcBr+XxClhUhNwrTCc7qIfTFnRfMdo,iv:NQHn/1pPqmtCSg5iq9qW+LoC7yqGnBMrPuWGXRPavgs=,tag:Y4LwfmoZXluwAZNjuI5mwA==,type:comment]
    square-access-token: ""
    square-application-id: ""
    square-location-id: ""
    #ENC[AES256_GCM,data:TWKBaUCQGagXiK1c2u2E06EVe4+FCtfO+GRF/K/zz4QX2/w1I6rxhnMBHBIS8f/NFpZSZsgCw/mmNfvXNyiJi1NycqC1DTMGyiTHOAE=,iv:EiSrLRvABHLKosw9Y0JpItR5IUy8mMHl/AQSxwWnrPI=,tag:W1lxv3KPaIRUZ+rqZ1cvxA==,type:comment]
    #ENC[AES256_GCM,data:/ZrzAz2fxOCDABd80626oq9KWU9bqeT5BOJrItCAAqA7+6G1ncgRLQ+8/bwYGhyRZEU9W15rlvPQK1IAYcg=,iv:0KFkV7ffQTnCOsiSO09hDohTp0ElmHx8XCgk9aZ3UhA=,tag:gKqoWWU7t/wXoUfhjuVxxQ==,type:comment]
    spaces-access-key-id: ""
    spaces-secret-access-key: ""
    #ENC[AES256_GCM,data:RN8qP9KZKWg6mF4ailvY8gZ2e/ltNUlUfLwDxFIsMszvzCxfqTvlWZrz5I+tSkA+gX0DNeyGiQFgcaWZFQb6Odi0WgaqBgs=,iv:OewQGfgymKzYU279dpmDYliJPgk4qEZi/OcF3uhq6EQ=,tag:j+tWfM31GFFTFyAfdLTdfQ==,type:comment]
    #ENC[AES256_GCM,data:PQFK2Z1Lxur54ekucNFOIFvw9ERm259fb3Daxlu6IY9axV0ETBVL8srOrigwzdNpsaqwYc4RPJLJCIHIDnhLiKW0XVZhtS2JWb1T,iv:blieEkdp3jYheGUXQVElshfT8M2SzaWhZ4LnFg/l22c=,tag:2eQUmfUlrTlXs62vC4ct5g==,type:comment]
    #ENC[AES256_GCM,data:hyDQdXaJht2IVCyLsbLx71+LJ9EimCelm76VGKAsLdPX9BstEsexBXqYv5vF3reTdCkNAiz+QYL9vnA7EObL812CgcDArNqTHDybudjF,iv:qpZyYRDJ0jcKcwlqZJrKaH28fFQ3tYC4P8zTBQngYrY=,tag:quMIPDiy4VhfooXuUsZX6Q==,type:comment]
    #ENC[AES256_GCM,data:yMEyyZVriDBYlxYY1NzjftzNruc3LctcpfJxutkN6e21RMvlHyPb7Hx1E8boMiXE5hWZ9N/8VE+keb/j4VScqAxZW+AhUrjgVJzCZQ==,iv:K+PmvcCBcWNQ1EqLbQGJhOfLAFvQrIuc/Tt7Bx5owE0=,tag:Si8gmWwbILRYlzO/K23tLA==,type:comment]
    google-client-id: ""
    google-client-secret: ""
    #ENC[AES256_GCM,data:zw2huidhA1TjslpEpqZn2z9ta5K1VguaZcdWZwzRQvZMj23XVn1KbQUgAxGXeYoc8i6su9gnCvaKdYL60SkBCWdrwRLNNA==,iv:+7O7My0U2u/pnp2Wf3Ey/AQphRHPDTx/w4eRjy2fTpc=,tag:nSGPeMz+2oG6ihr2PWkD0w==,type:comment]
    smtp-host: ""
    smtp-port: ""
    smtp-username: ""
    smtp-password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd1l3ZWdoZXBua1V3cDZT
            THFzb2hPcEtvRjVySTB1azVoVUFESXlyZVVvCkRibzFSNVpsZUVZZHhCQ0l5RGhD
            cDRrZllTRlMzby8zWEJWc1BtNkk2bmsKLS0tIHE3K1YrajZtbkJIS0ZHcmhpcWNV
            empHSW4xYXRxZjFwQ2VFMnRZZzZ5dDgK1byU2XcBN5118CuhvEZ0lUXC7eSNqN86
            PvMlJrs85bRIXmEhEp9nBx0cRHORMRYvMa7aL1qlYLt9goeajuh2Lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T16:52:15Z"
    mac: ENC[AES256_GCM,data:10ZVQgPqQP3fjuQyYYstT/8n4T0q1XBdtD8kjxrI9YNNrp6qf2Ob5g7Mh5QjB+MmY8qDa0bNyeGqtib7UCqMaShI8WDH/yfHzMU5amy1wIn8I42J0DdxLYNU9NB6fvCvP0D6nzA4Y57hN+F5E/excmNkvwinOUIq3dwvICNP//U=,iv:loURZ6mDK2jxA7n+SjQc14K9fd4YBJAW9GDRSr79jnI=,tag:+W9w+NxobbTi36vMwFaM8g==,type:str]
    version: 3.13.1
