apiVersion: v1
kind: Secret
metadata:
    name: backup-nas-credentials
    namespace: actual-budget
    labels:
        app.kubernetes.io/name: actual-budget
type: Opaque
stringData:
    smb-password: ENC[AES256_GCM,data:D5j8Z7voIXgnQ2CIWglj72P9i6QaASuFCsno+dHTKx8=,iv:qZyBCl74Yc295aef9YE6zyFLqHUnG195WCj142CwGB4=,tag:6lFOwabx6rooB8DlWbgSlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSGoxRGZUT3MwTVJJTEdn
            N05IYU04S0NWQWhyQnl4UDVHRkNVbVBSWkFjCnFaTkprYzdVbDBxdWIvTC93OExp
            REhrSkJyanlEdVNqYnRYSTcweUdGbkEKLS0tIGJJRDlTenJqTy96MTRyWVZwTTFq
            ZDJ5SStwOG8vc3o1SU9iRjdvL3BlcmsK+1rAhFmdQdoTFcBx/vSk7HHR5mcWJnPc
            tpNQS6CgvIP7wPCU6q7WhYGO1q1AQU5cdPYrIKW/VsnxDxfJCAgl4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T17:31:20Z"
    mac: ENC[AES256_GCM,data:2Qi9z1uQnK4x3DoQfh+0BN3gINH5TZlrjtH0kUjRVIh8TbK01jInJsESDrnJXIgh36YdQOIny+raa5CEq7a0ydABf5q37KNHh4RlwL2v70UU5GZo05YrBRFakTYXeJEsplS+hYAaFHvx6exiao9sIHQxPExRPsJ5/yNCl1fHAR8=,iv:mNbvEdSooPBG7/32OJ43/uC0wcT9nkH/JJhOcg5cYE8=,tag:yr3Gix1q0CDBsocMWqXAEQ==,type:str]
    version: 3.13.2
