apiVersion: v1
kind: Secret
metadata:
    name: backup-nas-credentials
    labels:
        app.kubernetes.io/name: adguard-home
type: Opaque
stringData:
    smb-password: ENC[AES256_GCM,data:oYf1vvkacSdPDp7OegOTgdV1pBzVRb5inQ==,iv:NeEYQ/G9Ybc9hID9vkIY8AHkXoBySvQsqlwDcwA8iBw=,tag:bujvPhFr+HcFZXdpwOKJQA==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TDZ2OENjK25TTWZrVWp5
            MnFXMzhUb25kb3psQ3RoOTBPUmJiQ1VBclNZCk1VQjNiOEppTml5bmFhd1NJRHpp
            dDA5b1dDUUFiL2ZPc3JFRmNFSUUzVEEKLS0tIE9Ybm96dWhvRFlya3R4K1B1Y1hH
            cjB4b2VaVzVobUZ0d003bVV6ZndvU3MKz/AxW12fqoqvHIej3XcBBukKf4s3YKnj
            kOqSJE9JgR8QcBxC5IHvJS9eyQsbraU9jbOKBUHP4KDtbZHgTfAvtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T16:05:28Z"
    mac: ENC[AES256_GCM,data:4w8TgITiUk64EzEG09eU9Br9VgQUYUxaIni3V/0Xz3+Wf8QNJe3reeFaqIboPqy1EtUKtM5PsQtxp8qTryVtz04HwSzowPMHImNMKcNy3ZLhCQZZE1uYgIiRQonJIEC4oINOXZu5Gr7+2C1vj9z3PzC+9ExxgZPFx0FtBq+nF6I=,iv:NCc6eyB/M36b0We72ffeTzt35xdeR/7giB7ulHlHzQw=,tag:kg3N4c3sQQ6nFHt+/FPBLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
