apiVersion: v1
kind: Secret
metadata:
    name: backup-nas-credentials
    labels:
        app.kubernetes.io/name: adguard-home
type: Opaque
stringData:
    smb-password: ENC[AES256_GCM,data:taCjPTW+/QGhhyYCDifASrphjQtzwmTM3hj85GV6E3Y=,iv:FPS0J2cE1f3L3cjpQvTqa1MFaj0Ql/B/vHrCDLtS6SM=,tag:R5d2jk40v0a0O0hHsElsZQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSWhqdEp6Mm1SZ1NUTEQy
            NkZJSHl3SGZrK2FtY2szRDgwdHVBRno1R1UwCnhlL0RwMVNvZEdPWDJNRytWVkVz
            bVNjWFZJTC9rU1hTZTk5QzBXQlZCQmcKLS0tIGl1ZUluRlhyQ29rWnNrOXhubklS
            T1pFY002LzlxeWwyaHFFRGlQMzhCR0EKszXJEdRb7EGVolnc5Jy1ylRuXFNiWgj1
            V3G4WXbPXKhlD0jhnv2KNbSfJIgsXj6Vjm2JdGgd2azk+e4xWUEVpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T00:37:51Z"
    mac: ENC[AES256_GCM,data:1KAYskXKpiY47IOxSv0MQzssBpxT6oSGz0fRIaUscWjI+nZKlU5awBBMyq5tlNE+iw9WsEJAYgnD9Lez8Om+Eif+ANwkbemDNOgqOnDe8s/0EIEhVjOegH2lsuRZKlQGG/EXYc5CCwILh1rDnwChCusl4ABzptBaYKt6GtlHfac=,iv:zA/kkd5/Cjv0O7h54Dr+w+iM6fmctchHeAgyPscvvbw=,tag:aNeieGzu6q5TfybGxvKzxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
