apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-home
  namespace: adguard-home
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  rules:
    - host: adguard.home.kennethblack.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-home-web
                port:
                  number: 80
  tls:
    - hosts:
        - adguard.home.kennethblack.me
      secretName: adguard-home-tls
