apiVersion: v1
data:
    github-token: ENC[AES256_GCM,data:XASUbXjZq3xQavTSyMsdgfpBWWwJheIXFNztQB2BZojdhcwhTsIcwgJ8hqRB17LEp+PugsyQDQ4hgaknOl3KKxZzxYMvrpoQKEy1Zch7Qqpqk7/yb5q5uI1plTLqRc50r98cO+tCLwxsLTIvAZn9B37AitqMp6hU6wp0KA==,iv:Wo6IU9j+hqJequx4V9H51/1m/FRR3PEgnhMgT93ZR/s=,tag:BSok9qgSejfAVtNyhZ1cnQ==,type:str]
kind: Secret
metadata:
    name: github-runner-exporter
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcEpUWnJwQURUOTJ1NDdz
            YWZBZXNvZW9uc1BqN3dUZ3RjQVpJc1lMdjE4CjVqUDdwVUM0WnVmU0hlSFZOOTdh
            djJZTjBVSDE2SG9hc2RiRWg5cHExY2sKLS0tIFhKbXNkRVRISUExc2hhK2JzWlEx
            NzBwWUZjVDRRMzFlODlocHloVWl2MzgKFbn7wM7qcfg/i8hvcLAGiz6ykeNVXGcJ
            o3xGRZ/Rr0+dFtvLcF2iWZaZtgOuEsJH5IdTf1Spo/c4K6tFd5TvDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T17:26:19Z"
    mac: ENC[AES256_GCM,data:fWyBFVfZOg9EurI+VBBtn18B06PTTqPkhifBM0AMo38KtIGIB/odK02ClmJdGo84Lrb5DWbrjozGUCml5yqyrITrB0B6KbBhtWW4zjas375p/14hJSfUhaDQhV5T7AWybo/r/OPR0t5jIotmHS2M57N6WlRjj4zkLb46iTox9Gc=,iv:2dPHZL/o8bYRsYgzRA/e/d46QZ6t87x2yDKz7Ihfr+o=,tag:TsK1X1umEK7lhKz7QjuURA==,type:str]
    version: 3.13.3
