apiVersion: v1
kind: Secret
metadata:
    name: headwind-mdm-secret
    namespace: headwind-mdm
type: Opaque
stringData:
    sql-pass: ENC[AES256_GCM,data:dvAXzGkglDH7JXWxP2xnphMOfyOJie9r4IKV8Q==,iv:1K7vKqzuNa/sme2H9QM+JQQOboPASscV0bjRUSDdk1w=,tag:BVMJGZxU/+Bz9aly86X50Q==,type:str]
    shared-secret: ENC[AES256_GCM,data:M9lCWSoGILY4Lu6nGYD9JLg+Bw97u0UmeLHP9tnBVKRqS01gBpWQGw==,iv:v9y59tdgT5s0KwkEgjVce9ZvAWEOcArXmhE9h3sbGxM=,tag:dJUlCcTxRIyFjJAHatZTMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQm40enN5YTdPcE4wZkw0
            LzhrYi9zZkJmRW9aM0tLaDdaQzQvbTY3SzF3CmpCdVpKWFZYclAzMHhqMDhaRURT
            aHFnWW14WFFCdkxjZy91ZlZ3UUVXOE0KLS0tIFVmWUJOMjRSc21USC85cUY2NTVX
            eC9JMHRHcnhiWSs3dGJGZ1hDUFZRUTAK4FIjHu2rvDeZ61vEcZLC31vNBD47LiDe
            0SKmKEXymCM1DfnfNWA3HpUogEdtcLY4FmlITrukQBB7K31spIs5Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T19:39:04Z"
    mac: ENC[AES256_GCM,data:VVMHpQGleLvaT1mWULNHoU1RnVjykl6paiMEFGZBMYg+Etn02yQ+GGBfH+DPhCge87DfDJQOSML9y2sFg7kEw3iJo+UUkyT0DV0C85Ij5dWcqEFHOXMFv6jGMqwv+gkLSjNvr3u1yNlsH9aPpUxKojtxfiidxmjx5VMprvAG0a0=,iv:TwiZNq6JMy8AgKuTeFbJ7yqugkQvQXj6r9mxTwCEwko=,tag:t6f+hzOFE637tB90xX8jMA==,type:str]
    version: 3.13.2
