apiVersion: v1
kind: Secret
metadata:
    name: backup-nas-credentials
    labels:
        app.kubernetes.io/name: litellm
type: Opaque
stringData:
    smb-password: ENC[AES256_GCM,data:n4fqdz4BXl0Gubg6q6i5FFqeKxw5lLki9A==,iv:SSHgsVsLNmpN20kBUjpxX6aHkAqC7k/CEAddCqTMCMg=,tag:mFgq0th4dz10GaGYgaOjvQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUUxjKytSNWp2MXo2S2h6
            VEF4MDZCanZCWVJzZE4wZzlEejhLcmpFeXpvClZRSFlGRjRtR2gwdXNMSE1kY0Iy
            VGtYNzAzaVVhQithN1l5bUpEY2NabmMKLS0tIEpJcG5yb3ZEN3MwVGJZd3ovekpx
            c21KeFZCbkcyL0U3a0krL2lFdWc5cW8KMi1XypQvQDCAKVCl8aH2ItrloUcPV0au
            4gY0O/iTBgu0zt2nI0WWw4Ys2mUiefPk+Sv90RzT4mRp1fUkSSAMng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T16:05:29Z"
    mac: ENC[AES256_GCM,data:5ucjmJnqD24CcXcGEpW97qWDkXT3AQL6pyLT+XfNF4wel6teb0GWuGy2Pvm4QhDZWhxpFEBqj0zFeHWJg/9z00XQyqXmriA847/RJN65xJqiJm02fT9XrKFsxEAGMR/kWe7wLt6SzyrCCAeJp8yGfmMpxyZLOSfDHNoSl4LM3Ao=,iv:3tpVf2gfqFOSaxwAmE1lg8JQho8zYbuG2/4y0bLaor4=,tag:hwycz8w2sCcQL2WxDDcftw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
