apiVersion: v1
kind: Secret
metadata:
    name: backup-nas-credentials
    labels:
        app.kubernetes.io/name: litellm
type: Opaque
stringData:
    smb-password: ENC[AES256_GCM,data:J9vkXHPxt/THCpkco9vh0Xj4GeVlhLPfsVn+VjsZN08=,iv:UXGyfioRdz4snOQ0eL5kDddTakSF0q3Dfp9SePnbghQ=,tag:WEEI9fyWQy5lAQoc/f/Qdg==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MWM2NFN6QlZHYnhodlgv
            UWo4czJSem9EV0hPZmsxbFJYVDZqZnhxSDBnCld6OUk0b3ZLR0dMVkp3d3BPWTE1
            aWtZNEVXRXhyUkZIMkhhMU5SZDRVRW8KLS0tIHQ3OFFQTWljb1BLaDBFYlozRXlu
            Y1JEb3Y4U1RSNUpoNW5EYVRZVGxXekUKr+YeA4kG0s/AuxZwmvuanynBnO07YT07
            PSNr7lusftUv28dXsutn2PvuEx2pFt6eVQoCiNgra53DFJPtZdeLKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T00:37:52Z"
    mac: ENC[AES256_GCM,data:b9IBRmNgHb3mZMtfzRgiOuMT7dWI6j95kK2pq1g22297W8J+19/KSIcLLIC9NqrsmHrpKsHj04JMa7hEHK4aB+2kVG0gEnh58HlInFO1mSo/l9Sp5izuqrihYbEQVzOpfFeTCHDFE67323RQQhZ+kp4NocfsJ8I6ao+ZzaZGKGg=,iv:RIR+hVZMZD/QrcFPsuoOBn2VmMCbeOQ58hqA1Nh8kKw=,tag:Yqh3o3l6waAnKhLuwHugCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
