apiVersion: v1
data:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:zFXjzsqog3DxWdAVjkb669t4axncqTODpP/DpNOwZwlT3ytJ5qR+5enLmLLDf4UGB30CZI947sKaPexhSM2lfQ==,iv:2I5rBQLNy2GspPVdnBmctIG5OgM8B4AgpaHTh6zw3pA=,tag:5uDJAcWzEmMLoOlZRs57ew==,type:str]
kind: Secret
metadata:
    name: litellm-secrets
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMlBHQUl2T0lZVWR0VXlp
            TUxWc3NHcTNoWU9nL29VV3JLVzZheXNST3pvClVJb0VsZ2ZPVXprZkZ4OUJRU0Ra
            RS8rb2RobTdZRmVnOW5qUXhJYTE0WFUKLS0tIHFFUHcwZWJWZ0pnQVFrazZsT2lG
            SlVIT2ZqMUhVc1lnUThhQUJkUDcvRzQKgPso8zMhAd/IkYChtO5phFQTXcRpyuIe
            vmLhY4umQwIM1mOjztC3httNqG7c2kUs1WujFEnynQafPlEOaXjhaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T20:32:07Z"
    mac: ENC[AES256_GCM,data:x5OKrn896u7Cnxp/DMj1XxBnbq3DuI5JcFMamGrmbxARTd83lnxUKmfQdNs1a+0z9Fbq267ZSRfyK33ZTjX5toj+xVTay3lDPfV3zyDnpyouIhTsntrWJQPJG1/SqfB+kCcffVLoWDP3MfPhQ474TqN/BfCg7LiUpZZew5CSOXs=,iv:ckzRlwKR4fMLFHhjV+ZtbZs7cl2D0fcm2k+UVf0aYO4=,tag:xyeZIo5sSE+eGJcoyb8pKw==,type:str]
    version: 3.13.1
