apiVersion: v1
kind: Secret
metadata:
    name: litellm-db-secrets
    namespace: ai-gateway
    labels:
        app.kubernetes.io/name: litellm
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:okxV4yNi+ipgoqRt8sWUhZD6btooy64Nnl6bqtOMLQC5n+bybdE9axvcrgnUPfnCIkhIGRJ9HByB6eEALHefOjAP5yU0DgNHUSfRzy9kjDxU+HkGcTRdIZOwb4RrliUXAa0FhWP5XQ==,iv:4lf2rMv4EhO/Nz8f6pxyQYM/p8zIWVxrZbTKXy8rkQ8=,tag:karZ6w0Rgm7eVPiOVnrdOA==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:J4vKXi+n3bLhpzsiuPBXxy1ROrzvKSskU4fkGsabl8ioTvs1mmMK3hoIV7nFNKyqPfqSy1nNlu4AEDi4lNLBJrtp1S19b4ae9xLiFD3ucyQ=,iv:wrGK+x784lUCeJ5Uy0UaZsMs9MBp3W0W0NUe4WSKApc=,tag:v7bQlHslxzeDKvp2Xg/LDw==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:zSZ9KbM=,iv:QTcpYqTSfXGZP3PpG6TEB06bQuPn53MJP8LirmQoSEU=,tag:PSZUj+RyoFpy1JKvU+lP8A==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:oODBHsU/XItFT78JyCzJXwQaAO5BoOhlaiJCqVzXWQ==,iv:USLpGWwaUQ5qxR4VSVe8A9bIp30D1goK0HMfqM2Ktf8=,tag:mHkvi1NuiKqV5LFy/BuS+A==,type:str]
    LAZER_API_KEY: ENC[AES256_GCM,data:b/6nUBxZGt7DO2Kv3wJ0WDW2je5A3uoC0Ma9qd/pct0K33Fw,iv:PsWLQcsqg2cmvQfVuUVamX5ZVrAJifX4SaBCWtY8YFw=,tag:cjPpzJlRX+35a9srNTky+Q==,type:str]
    STORE_MODEL_IN_DB: ENC[AES256_GCM,data:mfrFUfs=,iv:4DQpF7Y1ZyX6wmbB2PVmz5JCA0H1sYlEuN2wHRpoU6k=,tag:+mn6ogcGEvjwXE756S8gUg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:gdV+ZWcWXQ+HKkJiZpU3qSmtLlHgUB8Uo1R7Aa9KJEKZ2O4o/Z/K,iv:0WtI/pQCpX376l+gblfzoza59RsZut1IF69cY2GlLuI=,tag:IFZOcsxviYqd0SIYnyB6GA==,type:str]
    #ENC[AES256_GCM,data:rSNI/SWtl3SVFb1Pp5D4+OYVjoGSJIORa9CJ84cEDDuJdsbNMYNembxmFgCtG6e03qCENSSRh3IWdeCPf3jE,iv:QolHvI6FZF4E26extf/2pXknfr+QRT7y6lrTVUF6Vgs=,tag:8eK9gN3W9jgG6uvlMboW5w==,type:comment]
    #ENC[AES256_GCM,data:dt6MYLziN/vsvB8krMwLRYAEngTujAD4bTwWg+pU6MyuJO6DgmheqFTk1PTS0Ce3DbsaNLHOhxHuZTL162q75Z3j,iv:XfNvo0gC9W1xrEAvIxHksq9SvVYI5KmHzMQrZ0mpOSs=,tag:2YdXezIpVgZg4UoC7lWL3w==,type:comment]
    #ENC[AES256_GCM,data:uDTgpTr4Or8jIfCNpJfBc21RxbT0eVVbHzvYEjTwLNj1bB8h4w==,iv:aNZAvnyMnLh+jwQPz3yfymLZch3b6sgCRAJcwzglSGQ=,tag:OaPTRCarCV4F4b4uEmqQNA==,type:comment]
    GEMINI_API_KEY_FAMILY: ENC[AES256_GCM,data:f5vuDMlWKAqFJlVCPp/4X2Es/y32fVdIVJ2DO/uFcdwmy9C9QLoQ,iv:NfrhmZlxNTHClQfkDu2fbUQhXboaSYjfPSwaJWrg8w0=,tag:k6lbHaYOkfc9jVUoZG/F3Q==,type:str]
    LANGFUSE_PUBLIC_KEY: ENC[AES256_GCM,data:g9B5rGLXhffPgPYMAYOQudXqAaX/q3cUXMOMxcYXyAGXAH2m5UoHSRd1,iv:7fhaav7ekMVq+uPEkdSwjdxzhQOg0W6o03DAxG2XH9w=,tag:/zIVIAO7G9dR8F3DbAJ+Lw==,type:str]
    LANGFUSE_SECRET_KEY: ENC[AES256_GCM,data:/WcuUi73pjcylC6y2KXYqnlZGglgoYzzVqjR0zR7kBJuunB4KfE+0AYC,iv:u8+23QimJbU9rQpS207tVJ4zseJTnljKadXd6YXQloM=,tag:xAvyVrJd97CBCzXKQyLAfQ==,type:str]
    LANGFUSE_OTEL_HOST: ENC[AES256_GCM,data:FmRoV/H/rsplQEshVPnj3vSUIJzQpGs2Qg==,iv:pzNazn8Tzwxf0WKb+36e7tqrmvbS0XwBCqNbw9de0o0=,tag:pMUSfNgP+BWuhLXfdw3X7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeTlPbFk2aHprb241YXFG
            alM4U1I2S2JFdTZJcEcxd1RRZ00rTGF0U0JJCjVnMDJBaUc1MXVWT1d1SGhIOWMr
            WXAzMmRtdEZiU1RTVURORHV1dFpHVGMKLS0tIFJ5RXhxd0JBSFlkTU5pbm9iRFJE
            NFRWbWtBd3FoWTZLVFBDNEd6clQxL2sK1jt8xWUOhFXsmDIIMGPyNqFQ7UI04HDr
            OIqca20z4GqQHToch5dKapTUfxYo3WW3fPIhvtyroiOtiDhtlEfmIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T15:34:25Z"
    mac: ENC[AES256_GCM,data:MLD5bybswgtjj69yBs+duY9dMrHU5Qu1L8oySa7xkr+Av9JIwX5xkVNqTNuk4LheEf0CA6+VMbeyihNrYRJLlLd//B2zIcgZENdpRiQu3DtHnF7uiBjeykpLCJYS2GLOgguYNqoDP41vmuKaOx5yXV9HW4D165t9jYB/s69Q98g=,iv:qQGvvN6M45g5rfqvSziTSwspsv3vEFqksMHQXtVypz4=,tag:d9iuU7EYiTX7dm03zaEKjA==,type:str]
    version: 3.13.3
