apiVersion: v1
kind: Secret
metadata:
    name: litellm-db-secrets
    namespace: ai-gateway
    labels:
        app.kubernetes.io/name: litellm
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:NMimZVt8+hXSJ3lTUuBw1trIINCfJ+Q1Y3YHMWLn81xLYEKxbVAQuxZRg6bGZedDqx7x1T+YEJjoWkBctBB5809M0V8IQ7HRsJ6UMo+L0QJu8lmo3T+aRNl+SxGE2kkjTFVNHoAe2Q==,iv:DXGMXUo75JNpaTxvKiP6p4xxsVfVSOHKLS3vY3gCk5E=,tag:vhXWuUoK54mq3raeJY57Nw==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:x2vNnqSg0OrzvMkijpcTY6Hu/WJE4sU1O9o6jYwnx2Qa7ktB3griGATmJgJma8ifxOo3JKfo42BG/0xJ7COlQizcsQMgHGc+UsB/OXO1G1M=,iv:QZ8LjVObhFaTxLyKVXzcpa7h/wTv06ZOVVZ7ZXnx03g=,tag:ulh6Au3+0jzz4pKMT4gNmA==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:HpI7xYs=,iv:Ffh2BgFCJv9wn0QkWwAPHqGKnZm3dWh3/EbA87FysYI=,tag:vQOG1+x7qszdSojMRPN70w==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:QaMe86UDoZWYA3lxoswaXfUWPPw4lj/xWsGxpJD58w==,iv:2VegBd8kQYWUL/S0j+K3dkgswunHabTJy9U0aV1um2A=,tag:gBZIBPUK8qyI/vShGamYDA==,type:str]
    LAZER_API_KEY: ENC[AES256_GCM,data:yeZDBZLuOcbvI9OKHld3DnLs9JvTZxwfQTOGp6RPjNM8YHaZ,iv:zIeZh1BC8kHHFUWRJ7OT0GCkY113k5uT9nxACbglzHM=,tag:M5BoHlfyXO8YtkpxtyhsOQ==,type:str]
    STORE_MODEL_IN_DB: ENC[AES256_GCM,data:FcYGdOM=,iv:z5GHdxe/uMR6/7penYGV8KZcujhvm5uad91HPof6SVA=,tag:Quzhv81NGLMoEZfP1WyIpQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRHRPbzJPaTI5TlJ4d3Nv
            cFNYVEk1Nko3K2lqSzFSSXhwWXRYOVRIQ2djCitZdlh4NkE2Q1ZlT1gwTXhMZm9l
            U0poVHZ3ajVxVWovR1hBZW9IWUxqamcKLS0tIHJrcHpPVCtsVDNYZmx0L2U4WmZm
            UVdqanpqSVJpaVJKSEJXTEh1RGVsMDQKzHUdQHmy5XIbTmTc6Zj0Hkyl7hLeV6TF
            gLidkeKiL2qr1aEM8IuSofmRqldbVTTDWOpkQUBOi+c4BnIuumk+ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T03:41:32Z"
    mac: ENC[AES256_GCM,data:xmQ9PubAqCD8CJRuanlmn+MgPInLYQK+JHqItW7o/eMUA4+aB4pytA53CG0NdU60LN4kwsIcZja2hIWggbDpdKNRcpMw3lxK2tmh9K43K4mpa4lv8XMTJAYA8FXVynrYLoKhLyZ01e9Eb/oYQXD6Q5fV7ZGcxY8owvkCAFr9X20=,iv:IJhkwpJRx1RHOzJv/8trOB6urDvPWXzru9tZCmQUzZE=,tag:ffBsL0i6jVfc0W3FicsK6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
