apiVersion: v1
kind: Secret
metadata:
    name: litellm-db-secrets
    namespace: ai-gateway
    labels:
        app.kubernetes.io/name: litellm
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ZB5gbtKzSTso85oYEaP75vNlskCuiEKAnlx7SFkORD3TiaH0hzyzBG3H96vVEohd8mkP8zQVvRSH3thIvH8lldeEAnEgIi8y8VHznvU1eChLJog0nStWsm1NOfE0kD+/Akr0iC7MRw==,iv:q4TXzZUwJTolavb6EvpaGhsWqdshM9fQdlWxuxcUyNo=,tag:AXy4OgmTvRNpJiOkCiMHGw==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:r9PFl9a2caKlt3EUDgutQAg4BRlVd1kKShzANbjWezR1Uee/J+dXUJa55iClZUH2rxfm4OiyTgww+jW3oB8+CcNAMskL65PmzW+Mx9lOqoQ=,iv:4sxGsf31B+m7oHYi3T/6Z4S5cVc9kOBmuAymBOdu9q4=,tag:sXPCrx6mgkS/UQYQDlgLVw==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:O+d2BUM=,iv:WMEs/kJ1rdWkJBOpXsfFuJDhaizk3NzpeeXATa+eCsg=,tag:CjTY828XbCM5bNuevdJ+dg==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:wY92ag3k0NSgv1YeZwhBkdizm/JaT3+RPpqJhIjt1A==,iv:sLTrpyOPcNHMea54blQsMr0KocKJMO2AUHB3eRJUNCo=,tag:Q1eVeP0dnijJpzN8By3LFQ==,type:str]
    LAZER_API_KEY: ENC[AES256_GCM,data:LnwrqRWyZGzvYpavcU1yUWdHnF+/EnKhK3tJMoojlDPjfKK6,iv:BVmQxlq5km42n0cmpdC8/8KIx689lJe1VuGA848hj+I=,tag:DsC2qlS62pysrZoInNCgKg==,type:str]
    STORE_MODEL_IN_DB: ENC[AES256_GCM,data:gfIvFLQ=,iv:PtZ76QBmfRqAuv59zKJKNIzgvyPWF3mpCw3yV32HAHs=,tag:X001GwhZGfeuE2j+vA1tWQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:YfY+YaWqp3hB4J65OrNFTjvpqaB2LdNeRqElKpfX9mCEvGiZlCCu,iv:H0AHsjQ+W70Ha2LZYPkvFEgn1im6G/D85s2hrB2fxP0=,tag:rQCjeubnXAPxpaVnGmGUUw==,type:str]
    LANGFUSE_PUBLIC_KEY: ENC[AES256_GCM,data:z/S12YgfgYT7F/OijQqlHlXE37kzjhTU1nniXBwfPJp8pcw1l3BS664d,iv:DmuzeA17I0RAJ8G4K1XoGQRIakrcC897HZN0Wb090FM=,tag:nundBkigL8hkc2P2Ry3ZEw==,type:str]
    LANGFUSE_SECRET_KEY: ENC[AES256_GCM,data:/ZqnPmaOb6aNKVazyLNk7zQMj1VlJQybMLuILgb0ZSHo5E1u/ddvV6iC,iv:8eYDieOziDWiEZTS1QcslQfjxM8q1OE+NW+6vjm8IWM=,tag:gzrKh5mTfVPB9H/Be5fC3A==,type:str]
    LANGFUSE_OTEL_HOST: ENC[AES256_GCM,data:HwOiUFyRzt96sFimyDw/IOT50z+DPP1lPA==,iv:2oJuAA3teDjSlf7froqBo2+dOZqks+GpNovRaNC3YV0=,tag:M8LV6D8gyAoSrzltSC5PDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFblU4cUNVRFRWSG1MUEJZ
            RzJhQmNSQkRVbjUrcy9OU2E5WUsyRlBMSEJzCmhQYVhiWlM2SHZ1ZnlHa2tGZXlr
            QU9vNEdsV0k3V0taZHA0MzdINm1XbFEKLS0tIEFQaHJiZmxPNGVGZTJTb1o1endJ
            T1JCbzVXRWxpY2JUQ1kwZGY5Y0QrR3MKQEKMdPNePLhJGOGICShs3T6jQOg0jCcT
            AYMAPQBl0GbnGFfBzAqJthU6vhKGAcnhOcvX+4fwfFwwKhYDNPZRYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T14:51:51Z"
    mac: ENC[AES256_GCM,data:+4X6XrspR7Rghgl4nK8oZw32wO0Dwr9CJtCS2pLXe7eO9XMveseBnJRz3jj64twj/Dlzj/QK6LTinH4BATnbZa8Wpcpz4IVa5LDDQsOZehRMGCcQkm//lH22AwB8mwkmKu4GTZuVEhH7qveUS5xzT9gcW4x79dvqHFS6iTZ8hds=,iv:QhesIASFo/wu0Z7RLXLIij4cYXN5T+gOWbSSTtNGdG4=,tag:XkGy6pqGWlLYJX+qLvd7tg==,type:str]
    version: 3.13.2
