apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
  namespace: nginx-proxy-manager
  labels:
    app.kubernetes.io/name: nginx-proxy-manager
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx-proxy-manager
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager-admin
  namespace: nginx-proxy-manager
  labels:
    app.kubernetes.io/name: nginx-proxy-manager
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx-proxy-manager
  ports:
    - name: admin
      port: 81
      targetPort: 81
      protocol: TCP
