apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:DntGWnWzThyud3iKKAUzom5uRHkDoDXAaCPoBy8HXyNQjcWvoX/nzfwD,iv:Li9XlTyG/L0XilQmZgigNcAONFZbW2nW33p1YvY/taY=,tag:e/UM1vRdYrRPHuUB1n+wgA==,type:str]
    mcp-api-token: ENC[AES256_GCM,data:EWZcuROyl2DWWBaGK4mZ4Bh5H2DGJuomhAHZQF/faGVZr73CafiRbnJ2Lg==,iv:5elYHOfzMDz+buQN/9cuD+JoRbdpSVJY2KWRJCqIpno=,tag:2t7IGjpiXVeQRO9/I2tuiA==,type:str]
    admin-password: ENC[AES256_GCM,data:7KRBlTxF5fVVH8vBnZNUSVnvaQvPyvH57Ny9,iv:yAELejLYhB8BvZKvFayC/UcKjuN6Jrk9fyPorWdgH4w=,tag:QtBQ3pFXmYCya1hvT/UZJA==,type:str]
    admin-username: ENC[AES256_GCM,data:VHT3i9GnHA==,iv:6jYW+IkPRh/xZWTGJy0qy01F1Jb792l6vyIHuKqmuT0=,tag:hIq6KrDzFKvoQVJAnXqFnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb01jeXZGdWtWTkVUdzZY
            UjE5eEZObmliM1lJQnptakhWSzlSSkMrdGdrCkRqWE9HYVc1eHBKZVNWVE9LakFJ
            Vi9tSU9IeWhpUy81YVN6VzF3TW5JY2sKLS0tICt4UXhVeDVQY3lJQU5PcGlocllS
            OWd4NlpNSlhiQldqL2VManNCM0pXTWsKgH2zyNDBEobFLPfLUY6Ih/4ydwcmlbXx
            anmdyyiF3zH1hBW5DV6SAc1woLEisl9sX2mx32jnKmh4mVMgU2351w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T10:41:01Z"
    mac: ENC[AES256_GCM,data:cWEnadA5ZmCW0bU2AoX/Nkiuq//Fn2msIqAZbTbmkVcPH8eOEFo2YkAEdO0NddNZQyXqEe5ZCZuccx/6mrBdPaRx3euuvJXbbDLQvxSszUqhkGEFj/gOIMuiMBxy7zMkSnF1oiPwS1Gk56HyVldthbyVUrwmorOS0Z6tLdBaS9M=,iv:EWio7z8qnytTofZh03omxfMChE2L3iNZlFBnJQOhgR4=,tag:iV+ucsnJQG2jtixVMHTPOA==,type:str]
    version: 3.13.1
