apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:DntGWnWzThyud3iKKAUzom5uRHkDoDXAaCPoBy8HXyNQjcWvoX/nzfwD,iv:Li9XlTyG/L0XilQmZgigNcAONFZbW2nW33p1YvY/taY=,tag:e/UM1vRdYrRPHuUB1n+wgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb01jeXZGdWtWTkVUdzZY
            UjE5eEZObmliM1lJQnptakhWSzlSSkMrdGdrCkRqWE9HYVc1eHBKZVNWVE9LakFJ
            Vi9tSU9IeWhpUy81YVN6VzF3TW5JY2sKLS0tICt4UXhVeDVQY3lJQU5PcGlocllS
            OWd4NlpNSlhiQldqL2VManNCM0pXTWsKgH2zyNDBEobFLPfLUY6Ih/4ydwcmlbXx
            anmdyyiF3zH1hBW5DV6SAc1woLEisl9sX2mx32jnKmh4mVMgU2351w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T01:12:03Z"
    mac: ENC[AES256_GCM,data:8ZQtKpcykrdEFxDw4kXZJkI8CJBmnKcjCH+MqfpRKvz++pQnXUCb75ob7ktFN16DXF2jigNOmeXDlNj5MknqV51Lj8WmruKKpXVZAS6xTQCcnBNt2XwzS+rQ1RT0cBVI+Foca582gkxLmbZo8J+dleaOsuR7Kvy2Y6AWDWjF9Ks=,iv:Nq34dvkScsP0G3z8+n1YQzzzbXi88zano5MrXvCt4ck=,tag:hWv+ZwHiAO8OSHguVxJsTA==,type:str]
    version: 3.13.1
