apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secret
    namespace: karakeep
    labels:
        app.kubernetes.io/name: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:GAQ5WDCBqQSG5peoLQO3lc9KxuYUfM65MDWPQsCaFKqTJ7gmdZV5Tlhrbz+uuJlx8e+FsvNY9PeeYkr2RorqtQ==,iv:jf7+dr0qHOViB3DsCrp3U2wjUGkVlyjh2G7LX5uld3c=,tag:+yLRkmAmLv/M6iIiLz40Ew==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:kglNRGJ9nOlTeQpFJatAjKsaeCTbVn2m4gQLXF7A5TMpFjpOPBOEmMFKesmKbxm8S9WcD7I4K4bnDy21FCDZkQ==,iv:c9bUW4brguCLUhcJqW5RxiiCge+XcHoNx2le/TwiNa4=,tag:8DGKbFRknWMeiOKK3gDdZQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZWlkSUVLaGZpUFVLUXJH
            NDJvZGFhS0FFa0FiTDhqM3d3SjZMdm5Nem5VCmJoUEd2TllVaTFUa29NVEVtcVNa
            K0ZqWndwdk5mRkI2MjMrZEI5QS8yelUKLS0tIE05OFg1dk56bXhLWkdTdnFoN3B4
            Q0tLYjFsUzdqUmpyM0RQZ3RRcmNwTWMKA+kK8T5nCpWBjxNjbhMZYg/dpRvYKmLO
            XPeRsluPgEnKWPTQ7RsbTOXg8VUDgFna4dtES7n8GKJkiapwX6mihA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T20:33:15Z"
    mac: ENC[AES256_GCM,data:ogW9KGyKW8Bl7nZ11gvRLfadhcm9KA9uoSVcAD5OGJnlv0vB9kx5316QqaQT+6+43So7/d8UsadZYyXYD9eIgKqotQgTSzLAKaDQg/5rWNphynLIllGg72kKxuzTdXoWyFfXZA5NwEEWExUOfZCEtkF0/fJCzmCOkHxmYcbEE/0=,iv:qrrBvDAPWdOf6MuuYqwecOUnhp38TrAqD7AZhJ11mAg=,tag:IxsDu3/FA1VOvt590qrpAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
