apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secret
    namespace: karakeep
    labels:
        app.kubernetes.io/name: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:4SmUsptkjOra0bH2rIVabTlfvvS3TrNtt6fFuxSvv+mnGTMCbhoFeEJjhN+iqt8Y+rlJ5/MU73UIWDli0/RnNw==,iv:gCkB0eIkg4lkJVQ0zRGni9dpzM32ZRO0liigonDUobQ=,tag:ohljoVwCvQMUFHQ8llkwPg==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:KWFf/hT4E1Q5L9LP4cNM6quG4Jrsoftiq93VXcOCeThRq5S/kLsccG2aQBVqXi+pEZwNIGBwlXb6vZm76sPk5Q==,iv:JY0R7DJXmjMdMMGLBNHf9rvNogZAJg1d7PDNDMHqKec=,tag:lT8PgdlzycBrW2eSlCgm/Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:ImHeSJdHVpN4yvtANtQ/vuHSpyffHXAuF+ljDcp//GeCbzKhWUkATGpVj+jqr7nD,iv:dXvEZgq7ckIkt7skIIRuSb3JppFEU1N+WxIpkQTKsVU=,tag:M+N3zKy0itYtrP6yGj1GtA==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVDhxSlJvYUtQUDJ2QzBv
            aWpoWEZUWXo0QlhlSjdLaWZySXJiNEcrNFc4CkFPeUtNbHNJSjlWN1NUY2tjOTVa
            SER5OVEwSnlDdzNoeXc3b3FpaFpMZXMKLS0tIDNNck5mbHYvdCtGSmZZcThJUlMy
            WVFIVmZRQW1ZOEd4V0RmT3NKWGJiQncKT+O+RPw7MdgwBTmsHzx0V87J12O/Frpj
            ToEcZbEg58SFS2+U85PS9td3NmWdMP+Swq5VRCcA6V9q74t4zGNTqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T15:34:42Z"
    mac: ENC[AES256_GCM,data:OpGNqU3n2rKS4uUe87r7Gsg1WlEGXlROR9SDnaJkOVLq19A2N5EVDv58WyvMntH2/M5V4rYPR0L93Hs3PFNcJuM7c1l0ohW59Vt3WcAfZu1gIWRcZ5W1gKiqq4WBYwaZPhrePbKUampZHMs200ayR2FntJbr6WoTSoCgOTkgM4M=,iv:GXhPZI0zCNLQi5FSb8PYxK3lvKCx0MfOKV657OWBzDw=,tag:+tI8XRDW/diqQH7288fmEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
