apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secret
    namespace: karakeep
    labels:
        app.kubernetes.io/name: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:4SmUsptkjOra0bH2rIVabTlfvvS3TrNtt6fFuxSvv+mnGTMCbhoFeEJjhN+iqt8Y+rlJ5/MU73UIWDli0/RnNw==,iv:gCkB0eIkg4lkJVQ0zRGni9dpzM32ZRO0liigonDUobQ=,tag:ohljoVwCvQMUFHQ8llkwPg==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:KWFf/hT4E1Q5L9LP4cNM6quG4Jrsoftiq93VXcOCeThRq5S/kLsccG2aQBVqXi+pEZwNIGBwlXb6vZm76sPk5Q==,iv:JY0R7DJXmjMdMMGLBNHf9rvNogZAJg1d7PDNDMHqKec=,tag:lT8PgdlzycBrW2eSlCgm/Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:4WkTaKdTRP7Vsa2bziiNiwUTtF9WfivBRw==,iv:u/BKiqWHdNjFFf7j1j3AhZBs/E+85GxhsKLA6ZlVCAg=,tag:0eNq+QiKnwvDSLQMBkfk2w==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVDhxSlJvYUtQUDJ2QzBv
            aWpoWEZUWXo0QlhlSjdLaWZySXJiNEcrNFc4CkFPeUtNbHNJSjlWN1NUY2tjOTVa
            SER5OVEwSnlDdzNoeXc3b3FpaFpMZXMKLS0tIDNNck5mbHYvdCtGSmZZcThJUlMy
            WVFIVmZRQW1ZOEd4V0RmT3NKWGJiQncKT+O+RPw7MdgwBTmsHzx0V87J12O/Frpj
            ToEcZbEg58SFS2+U85PS9td3NmWdMP+Swq5VRCcA6V9q74t4zGNTqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T15:52:44Z"
    mac: ENC[AES256_GCM,data:6vzFjF2S+t8GbUWSloc4tbyQA9xSFTwasJqamqk1qUZDIBrX8nNdydNqvP32Qh3VRsZeJXefOkhaSciIjTub0jxmWuH7KfTgTKDtwO3Y6cYcSLotmMVTQMAee97/Q5Xr/kQjdEbUzxI7e7sQWH/dSpE5SJ/vgi4l9CZuoLkVgyo=,iv:cLHb+iSdYxkbUMgo6OBw3tibM+EL/4BoLo5TIOvpG7A=,tag:W+2qDNKTqj3hpTzQeJvLnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
