apiVersion: v1
kind: Secret
metadata:
    name: game-registry-token
    namespace: playground-server
type: Opaque
stringData:
    SERVER_TOKEN: ENC[AES256_GCM,data:nre8lp5HGJstK/Swl1bqSw/RPHMCWrbOWHgXXMWdBT6fJiJUfohgv6zRAEbk6+hn,iv:32ThRo6ota1k+bN2/io27e2OgCJqxnQ12uTh6PqRGGg=,tag:uq+H4493DuK4HdPBJKIoXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdTBVdmVpbHl6MnV5aU85
            ZklNbHg4L2x5MWhLbnZ0cUZpTjBwWVpCSGo0CmI1VThMVGVXdTlFSVM3cU52V241
            WDlGNXl0aFdqMXcwRlN4QWFaMFFhTWcKLS0tIG1uT0l1V3A4a3NvdCtFa2dFdmhi
            bHh5c0xoMVhmWXo2ZVdhalo1UytHa00KQMRXHjG3DSq2jAynJxhgOlbwvk8DZRKn
            fXR8X64pyecOHSZADgWgAzLmfwX/ORLedRs/aNgLiibDgE8NU6uf1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T16:50:08Z"
    mac: ENC[AES256_GCM,data:f/JODjfpAtyXxLT5wXWlUwqbYyZYMqv8KhiU+Hqyyx0PeqZBABwL7NmAB9671HvIncwYEcCll1/VBGEJRvHdtM+ghezsavaQUnXcw1v+AmiQ3G17oszjQGfeiJR/sGS6WlUMxk6TpzKcdI2hRVoPYV/rINxWT2/QT4auIHKM/jU=,iv:XkUAFaMAY3JbtYTdGs1+BCeMp3eR4JfxTFzdCe4eJhM=,tag:MkmVwgo+W0BzkZmOlFHttA==,type:str]
    version: 3.13.3
