apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: playground-server
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:sA+lZkb1Ej5reMyDwjXeXXwKwRRHt6Ju4wFIW7m6EcnqKs1eeLKbBK+TCYCr/xTN+JkvjOW/G62VZvN4mBywdXym5X+9c34CcEeSmi1YEY9ZSGhULnoG9JGCmy3pGJxIEzNR2WX43WEFSq8R2lIr/3VBR4GpYeZTlJ6QUvAgSSGDP8Hibn4LSMj7T1M3HkCKuF6HxS8RJpw0Qmh0ySgD6Ww0RmIdSSoCOaYs1wUJgTyODjC+wezWIg==,iv:l4F7xu5fnTTep+x1iH6ykcV207C3JJPKG19FPYGivQA=,tag:TR8Mq3KGhTNTr/X1tprkTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT2NuaDlJN2tiS1JNUzF4
            NWpiTjBhRkdGck5rY3hLSUp4blNmSXk0akY0Ck43WWtaMWl0M2FRNXQrWEN4YU8z
            dzVldDdqekh4TzRlNE1DUWcxWFprTFkKLS0tIG4yMmpkZ3dxWktqMnlyT3puWlNF
            L2VJZ0paL0JaNVpYMWJ2a0FSYTBydW8Kk9O1DxEkujNT+Rw01w9QSRvohM8dSv3y
            LsshVBomxpfVfc7f5c/UNPW0YOzvfOx5t/T3JZ1O3UEBearhukPMWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T21:14:44Z"
    mac: ENC[AES256_GCM,data:1NbAyyypnKlbDvauN9IPC15QY4DwVbfxSJEms4qm5fJ4qZb77tVNtRBFFm9FquJL9KrzMlkGRWxSGr+7gKMM4h1ugVNJGAPrlKTFLcCXdp+wyZvAmwMJzdXnqXGXnqXI1s7eYA24yay0qfpTXCPEh8ntKFd4IGeaAk4yevDHNZ8=,iv:powu+9k8PMCmYmqt9LbLDAswYzl9n+u8fm3/96KqXkc=,tag:mxqcjWG19KFoxuSxFCN8Cw==,type:str]
    version: 3.13.3
