apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: black-dev
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:xKWYuQZU3M45FwdlTkjtJ9PrJ3HbDGwu/HTtfo8AzGGXIJbcO0K6jyCPdo26z5Vt5CiWBvEffLgQDdKizCIJrzih4mXGl8dAZ3+L7DprRkLZ0QbaIQdu+PLj/oDNKU374+vSJP1g/cWx/+M/FEn41n72Ejjf/MJdbbDw+q+2R6AyJKkGSipXKGaJqU/CXRBF0+F7m5kHXPMYw4pE2Yq/tnsAyi6seBIJ/x9vls8t4PGZhInphkRBpQ==,iv:4M8tzRCjCtP/6KClLqukMwkwXaM3vTQUKRqLkec0+gY=,tag:vWrD/t181QwLF3LIRdoFkg==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKU3BIRVQ1UXlPZWZsUnZ3
            NWFFaEZrZENLQXBweWRPUGc0dVpDa0NGTDBnCk4vSmtHdWxyTFhRRzc0NTBvS3VM
            OUtBbXMvZHIwOHZJMTd5clRMK0I3V1kKLS0tIFA1bXI5dll1eXRFVmltaGdiTGhy
            enI0WCtmTDVIYXNoMWNZaDNrMVcxTzQKdfsKKpYeqBLR/EUKVoTkWd/iLeoFvV2f
            oWjcH/fAEV0YaZVpg6MEP+jo9lN/iWsIB+XDyqviM033wijP6QyVyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T13:31:37Z"
    mac: ENC[AES256_GCM,data:d3E8IJSNYE9ys3WJMqTie+NIkvHgE9MStdB9BGWGbGD/m8gVddMc/Xdls3sjFhp3ougGZz4Wj8DbtX85VYAiUJqaN5/WVKNdXfMoG1MBnapZ9WxV9ZrUKAtjBQWAytQUE4bK9uyZj5tbx+hEMsQD4KSkDbG3mVsFpIJD1bpoF5k=,iv:8eSV2kgrZ61mNo7qPYLBVRXYcA9xeBMhRHvBsn+kYYM=,tag:oOAIn9XtcsRdIaOrwDYeXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
