apiVersion: v1
kind: Secret
metadata:
    name: mem0-secrets
    namespace: memory
    labels:
        app.kubernetes.io/name: mem0
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Z0EDyy7oLGXLz0mpUUglFCXokokZJAXVPE61DYRx3mNXV3dhob20megSWq0=,iv:UThrmslUVae8lBV4m9TiurKoQUrDuoSG9JhkJ+U21mA=,tag:Mh5dK1xH2geYlk4uYorgCw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:qW7KJAk05vgaGmY5KyI741SPW3ZM/l9NJA==,iv:3dSX55mQIjZ9CH4cBQX/2yGOMebwH3lmqURsVkrm/tA=,tag:WnPQkLo0+4JsuYZmuBTRZA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:BhCBujimpjbd7eqSlLpuiuJlt2yfebYxp0m746m6PQyOJz6SXkA/txYjJhljtXXV4hO1tT8rlUN5h59XvmCGLQ==,iv:9tMbqvtUbvcB4X3CbinsbCC5jwLTPWjvdjpqobd/Tpw=,tag:1aQmhVXJOb8Ig9eAWPK4Fw==,type:str]
    ADMIN_API_KEY: ENC[AES256_GCM,data:o24msNpXNNu6GmMRhBwUQ0emLSZvec3TJG9xGwcD+gCu3/0isuQ5AVt9K3ceQb8vNS2RxGyw8UbKA0UTLeJdHQ==,iv:8QYxXSAjNFsza1Z3n1BewkPt05gF1xdTdbGajgVdexk=,tag:deArDdch/BcItkuxUrBzog==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNFlLVXVzTU5Gd0dZMThY
            cGsrVEY3OHV1NGRMV2RwR0FYa2ovYnB4M1Q4CnM4cndXNHRJNUU1QXhpZnVFLzdT
            cUJ5czR5aHhrWnpjNGMvU1NQczRaSGMKLS0tIFVlNmkwWDJheENyVzNENXhiVjNa
            V0UxVUM4aDIxVFF4elQweUdnTDFrSmsKXDSXn4z9QaD6BVdAW0UDuQy4c3bdgHkL
            G2HcAYFu9gc//33LfwRoze67fMJijzkIFUd5Uxhv2hzr24OjZ1ZH8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T00:01:47Z"
    mac: ENC[AES256_GCM,data:tJIqg7mwXuAsJsArZtMjv4iwtlCmMCt/ESGdeTwEEs8AyHYPyTPCKnTudcWp/ATUgMfXkKVauGzmfR/6r4ZxtS4SPUUlKnZnrnXPpRIogXVFtSV5w0wR7iDQF+TuA9lXY4OnAYfIq4x7dZxaw3oZWvPvIifLx+EtnjMzPutUokQ=,iv:uINIMGObydCLsI+AqbrRbMahXz90g1QzK6hJl7XWQRc=,tag:NHP/1A/GYR/1AX3bT4G8vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
