apiVersion: v1
kind: Secret
metadata:
    name: ansible-runner-secrets
    namespace: ansible-runner
type: Opaque
stringData:
    ssh-privkey: ENC[AES256_GCM,data:b112M9hd6gUxmnhoq1UbvujLVvqgTwfcdAGf8Xh3ZuI24ke2sgtEaHzu+iOEd7WA0FHf3RciSgCUlTd2Ybr2fs3uLed8UzmKsBPPXcrcU9YknCEkLGVfZ/TjW+QQbdMxVgzT2SgvxZWdRtxM13oR8EAexVzwpYlMph9v52HSQQ/SyM4dagEjBKUf7Lb1wAbfudsfgT4Qp0ebQvQSGQapE21naWJjmDP5YeIFvq8yL8/GlwHQLYpiJ3rIFYOIjYZtoytlbj1tzLn4TLUmNS0o77PDCRy1fi1ujC6UwhpgwnQ7S8H4p7uGRcmSm+Zo+1Jz0OEBkvVxSfjZRkUTwOs8BAhTtu7ufqPsmIY3qcfsHurx+B6r1FbqdobW+pQTEy2YjeUCahdabzuKx8nzppRrYxqtpYWJuMFVvckdwTD+nM7nDDXW1CCn1j/D22YCD5x+HCO5JP7Tar7lhvCC90gxzsHGubZ702l0VW8/QNeognM11wE19O5iu5XZazXcF5AdsfIsvaVX25/3wGXEu7G/dqmL+pihrudMgbxTnqMi33kCFcQ=,iv:BzrqMrw3HVyZbvRZFsIndoR8AXPKdHjJjJECz2m72Xo=,tag:SJmAzlYbc7qLqZ3Wf1Fk6g==,type:str]
    ansible-vault-pass: ENC[AES256_GCM,data:9ONVTDhYQMb+8wm7n9K/e7boUfL2ECJo9SMkDYX+Sos=,iv:+n9Oow6pLHzNYwWnMn2BKb9AX69FvJq5MbbBzG/bKJA=,tag:ODLXAVB9Ck5CRRMy15VUMQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aEFwN2x3NkdvMktXSkpH
            ZWxuNXdva2ltRWZrSjB0NUlhand1NFpjSDBJCkNiOEZwZUhFRXZhSFZuTnlnY2NN
            L28xaDMrYXQ2NHVEaHMvRnl6NFZTUUEKLS0tIEZhYkxDOXdNS29KcUZ0L2lMR0tV
            Qm56cVBTYlNCcm0vc1dkOFpuRnBWdFEKzT50o0NGKs2oHYJ/Hk+/N41UUy72H8cO
            Aro299Np4IXxoalXCLkWZHzcphW1ejY5wMiQv83nZtlGot1NG4FraQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T03:03:21Z"
    mac: ENC[AES256_GCM,data:WyQMRDsHgLiZ1XDMHgDBxKuM+g9fVul3W78VDd34n3GQ+dmcITsWVMymonsE4gETYRxS5/Me8Tjgr9+rAiGy1aEoaHrCYXwRBznCxcdeL4B6ylUZ964+Y0I2g4P7Knxhv6meEU0rFr98aO5h8QQL8kuH9EtKOtcmH8iX8AgmeAM=,iv:MJRYHL5ZUI1ptbgwl6zOD/aueK/twIW2p8hWlTbxtG4=,tag:OUgnW6+bbryIsRNCtapgxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
