apiVersion: v1
kind: Secret
metadata:
    name: backup-nas-credentials
    namespace: immich
    labels:
        app.kubernetes.io/name: immich
type: Opaque
stringData:
    smb-password: ENC[AES256_GCM,data:3A18R0Gvge1w12gLYY6qGuRbdMIgUXNpS/vpjPj4GII=,iv:fNGww/wtZj5iEwcokxYVaXduw+vCfiiJXm9CW9vzBkw=,tag:L8w6jSFKi3h69q5AUeJ+WQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNkxIYWltTkZ5U2dTMGpK
            aVBtRkF3NDdna3ZVbHlySVlzRmMra1hmZEhVCjlaS1VNaTdDdHFnekxrRE5OKzBt
            Snp3dW1HNnI2MUtJb1NPYzlDV3dQVjQKLS0tIEFiZGxKckNKMVd3R3pqLzNrUXBF
            cjJkcVBTYm1nSFFIbDRJcEtaZFlxazgKoCix6YFZTzpOY+fmu+wz2NbJKqT7NvtQ
            QotQ+bUOfTLGU/I3odyta3LmFHoP3TGDfB3MiXV4GNE9aM8YtnJc/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T05:52:57Z"
    mac: ENC[AES256_GCM,data:8Yy0FMAyd7mNWLU6+g8ClmynVPrde8PBxPDX7HixLaZSbVTA/5GPODpfRirvJmjeyUTa2KyoVxnZ9/WrNsqQvvr4BneEK0wZkZYiWAp6rKcR8VMuRQLmq+m5UA5KAywjmi9/KVgSOsfR/2+rkvrHuovV4SkKF4jMqqg328gJFUc=,iv:fxxsIdMwEoWhRwHLIk5do6wMXHVEKK9zU3QTijKJGX8=,tag:ZFgoGwkDkCutT5kAwujLmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
