apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
data:
  DB_HOSTNAME: immich-postgres
  DB_DATABASE_NAME: immich
  DB_PORT: "5432"
  REDIS_HOSTNAME: immich-redis
  REDIS_PORT: "6379"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-ml:3003"
  TZ: America/New_York
