apiVersion: v1
kind: Service
metadata:
  name: immich-ml
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: machine-learning
spec:
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: machine-learning
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP
