apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: redis
spec:
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
