apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
    labels:
        app.kubernetes.io/name: immich
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:FJWCl6Vs,iv:mz9bScsONqmsa70P+II5Lyjjuk0k6QtKQM/oKku+mHo=,tag:POVw4isNmZCXNqFKSx+k5w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:hZJYgClg0f4TDGIHtzlAXcEh0DDHsEbgPolhKmKmNV3UATCc/uHkhg8MlQiTxKZk2xAzCUgIoSyw8lqMrFX4Iw==,iv:znX0v27+as6sWZB6CCfwCfq9cZDBQxawSN9U6KKfPdc=,tag:UxtrPQFmva+ro1N3D3L7cQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QW5NS3lqYUMwRm5Ucm9C
            L3hoNGRtdEJ6SmhoNGZ6Um01Y2F2ZGFIRXhjCjJ3aHhYMFFhL2FxbnVibDVtNGtD
            Zld5NTZtZUh2VCtCWmJFRzdKM1JPSWcKLS0tIGVYZGg1aGw0OGRuTHZYV3ZPQjE0
            TFBFOGNyalZTbit1eFRkY0s0L0U3bEUKKLu56BZpK5ULvjPnSHeNpVG3SeTNnhJ6
            Bbc/u3R0UZX/wOiqXLzgv/B4SDcc1sAdznTaPdZnG1LFgBWXEuaa+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T05:52:39Z"
    mac: ENC[AES256_GCM,data:RGAeUyFieY63ISgxqDILzb0hyGp64T7c8ZdCta994sloqvU5qtuu4U6Wzcc2JoN63vpD+SZroN27Sc4J/IosI10NlmjoaKtJ5/GVcJR9lyHXTBVIW7kA06dv7STEipn3tEMz+Gch4qIs+bET8NiQ5TkyjZcr1xEaAL4Xj31Bd2c=,iv:Nok7Cs0y+BxeZCDmawfLfOVCuY3cerxYJeqBktei04E=,tag:KbaPMNdFRcdhqoMLvSwjMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
