apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
  ports:
    - port: 80
      targetPort: 2283
  type: ClusterIP
