apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: office-cup
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:kM7zKQJepD3Q/zIO9UQPA54LejlHop+OUH/1siH7QkilVtUBDwqfW0WMmyyhNyaK0eZizTH/r6yVugkaAw0oQz+LXlPMd0Fg6SZK5rVCVF8BeTcFzDvChuAd9P+Ug0sZTiGbLu79MxVrFRg1HiszmoFGgVw7aHI6aBky9SwAG9EN5jI0q+YSbm3UvkbNn0VyKO5IwlKT09hSyLpAH3mJ2OI8X1MIp7Hlf5DpuCsLRKcPb5ElccB7KA==,iv:xXdOVNvxdykn62POa0rLvX91CLjex3PpXRCBs1bWV7s=,tag:PdgBAmRK9QEqVRtQcJBYTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb2FJc2Z6Ri9JOHZTck1M
            SzZNME1MNVc5S1RwZm42djUvY0VMUXVQNzBVClpQQit0emRNRFVmMFJWMWE0eDZL
            UWtoM3FEWUxQYnhwTDJKcnNiN2N2dlEKLS0tIDJkNnhnSDRFQkJWMlV0S0pma3lQ
            LzNDdEJKZ29aN0Q4YU8xaWp4VDJIMGcKfMGXIXDhK/Ei1pQbuBxi22l+V8TZCu9q
            0bAhHdTY7/Ce3fVuzE5iITGgn6kNxn6nfQJQtPU8fXtWTTEYrv6ZWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T22:27:19Z"
    mac: ENC[AES256_GCM,data:XjXhyOZZAlmeO3RwBhEJ3escjgQHhkDlxJCKvUWYYq+99uNbJeD+E/BzauTZJSuCguFEF+XQ2OgDUyJ+t4XcAo35BNREMhXCrTc+Vn+OsIkK6iRpa/Cn/rD4BVOl1owvBTXs8g2+g1Yo1Fu5LtO+YNoxG/tOzAdoN7dpQAvSkeA=,iv:8YAsi0y6FDwpS9yyCkqFtQ9b5SHKnX4psGq/3HO1N0M=,tag:C3bH6GiMwxL51n3D9gferw==,type:str]
    version: 3.13.2
