apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: time-tangle
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:AGaW5qTHssOZ+Eig0vb/wLJsvYX5zlly7maHtVydR1RNRV+fnt3KZhmWZx+40Y4zZaG1HMDRWEp9ItLJhCZu0L9AhgO5NnkZR2Pk9c8/GucLVFixj8iF3NAupdGZQK9O+WzSJOFJj+lzx5GoYYcwqNXFistR4NIe9FlEl9ePJi1eKSdddPiJUy5HbohsShBkKFAS7eBztdU8lyNDKYpXQjTX/7BcS58ygh0Y86JKN+wT9U6tHGMDMA==,iv:GDQamjTy3bbmwfxyPTzUmXhZu2CKIM1HS+HI+vB4kwI=,tag:zwtMo3bri/LjzuAb+VPBkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTlN0MEZWTm5TaS9pajN2
            bGJPdEpEOTFhbmdOQWw5bjNQaE96enozcEVVCjBKa09Ba0pzbHMyYURnekhuL0VF
            RE03ZGFEREoycW1BMjZCZlZTVkhmSDQKLS0tIFBIT2JLWkdYQjZrQU1rb09lOUk3
            c05IcS95dkZ2VklmRFhwZlN1dThTYlUKDk35Lbl4j4GAastWjOKU5TcvB+gnqrZO
            kNQ/y5kxAWXAqwbe8o0E2Z5hW6KeC6lkogIzrR+/0N+DYRd2f/AnZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T03:54:42Z"
    mac: ENC[AES256_GCM,data:ANP9F+T/emefn/W8jiERI8Fuq4Sy5lVkEHTxm83MqcoajSv9EAomrh+xBo7vJiDmwXnp6Qb6ldv2rmBCKy6pcizXGmT8uUBS/uHeRqzfAn6atD89160hK4/BsoeiuZHrDx875yQaBfu+8eYukMCzLQmKYkGuwZlgUBfmxArDo/4=,iv:DPuIyAvLbdHl/fdoDD7NrcwIE+KhQPpcmQENqIvcXfY=,tag:M5p/2u3cw/lWZhUYNTEVjQ==,type:str]
    version: 3.13.2
