apiVersion: v1
kind: Secret
metadata:
    name: time-tangle-postgres-secret
    namespace: time-tangle
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6If3m3kyhw2CHfg=,iv:bXqrvh1Ryqy6soRj9ryP873P7ZlsjfP/r2+dGU6sSNg=,tag:wJbOJJEOMVoF+OW8v+gySQ==,type:str]
    password: ENC[AES256_GCM,data:8mH2Y3zhqwe4rmec2EHEVLewFTWW8dLq3kfRdYYs0iLzyVzRYfN7pH2E/cQb2VN9,iv:cshaRuUHhnELIelPrhQ1J5TCTcIf5pwguwMJ0ytK5SA=,tag:nPrAHoUy2ou3IX6rOufN3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVkRhcTAvK3IwNVJLK1hS
            SFhMVytjOHpsNXJuZmQrWjUwZTlVK0o3ckFjCjhwUHZObEUrUzlMTEhRSmJwY2J3
            a1RnbitmSng1MEV3Y3FWSGJyNjR4ZEUKLS0tIGExeHRTVVRBQ0NFVnZ3ZzI3K2dr
            SGIvT2U0Zndxcy9OQWU0RzNkZVFFMjgKLjOMwOkQ5KAmBJ4nXgantGFOzPOejKVe
            InjRgxhvgUvBoKymP3CyPHMEyaNVje3/o3sthoHvpRJH/GJ8A+XkPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T03:54:42Z"
    mac: ENC[AES256_GCM,data:Hgpnn8cXiqXBEFaaNa5tU/bjrj7gcumsjq1HJSywgPPL8/WPTeIQBEeEp7JL7aAlJNgLG0gf6KARcMAhkpeg4hj5tm4EAt+9mLH3C6+rL+zY7Z46WKaXNfKrrVaWLeHlB6SyYDZnSOGc2/PdvfS5LSo1pPTJ5UCDohrgUJPmTGE=,iv:bAhWIVF7SkbJT1cTiCgjaUy4zT+Pvb680+dBdxAYTd8=,tag:RpQl1HzAAW2fE26+IOYBew==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: time-tangle-api-secret
    namespace: time-tangle
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:/Ukeci5og4nqgaWYaZjPnL1VbIePqEHnU8YrTQMwR2M6TVN+kb/AUIaaI/QZWp5P4zTWVjPfDidKdoCBA0Rfe1jogtEbER0+jn8ZUyI+oyCA/zA3XrAK//srWuJIu09aWviUc6I4xfHLLWtOt4fhX3BYkerGd7j7h3FAtVXGaRljCPvIj6+2Yy4oBmT3,iv:9H2+xQZfZ/xUXDOfU/PxRrAzqxQo+hMix01XAwMSWvA=,tag:BDlwrRen/MbHCEGwyzqpBA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:hZEwVb0GQ2lYUfFESMhKxAJ7zZ1TJFZIVxHZx/7jYc4mFBRM/vpWvulwP2b17/4gYmwhRG5vYNAI6tlgMnAfY8Lv5hXj7RwT3pUgcNETtwDBIphi2oOi2jzJPsAUDS82,iv:OF62rlj+b68wbfgPjliQTAK4R2PJgydjS4zUYHTt4gQ=,tag:K6LumwFoQamF/7ioixKULA==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:rTAN1Oryv6h4Dl0Kl2nh+3btE9cueaO8tDVMqhqalNahy/nGZB5xk3EsvkN8yFvnHntNgtfyeE59xXD3JAuHkU315z5f14JsiQZl4DCae1gF0lYT/Ox+yOvO1/HG94yM,iv:fFcTmc4BqRLA1wFYVEswvAZz7I5j4L9hE5a1VERsOvk=,tag:+XOtNODWd+FR+b4SXT3Isw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVkRhcTAvK3IwNVJLK1hS
            SFhMVytjOHpsNXJuZmQrWjUwZTlVK0o3ckFjCjhwUHZObEUrUzlMTEhRSmJwY2J3
            a1RnbitmSng1MEV3Y3FWSGJyNjR4ZEUKLS0tIGExeHRTVVRBQ0NFVnZ3ZzI3K2dr
            SGIvT2U0Zndxcy9OQWU0RzNkZVFFMjgKLjOMwOkQ5KAmBJ4nXgantGFOzPOejKVe
            InjRgxhvgUvBoKymP3CyPHMEyaNVje3/o3sthoHvpRJH/GJ8A+XkPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T03:54:42Z"
    mac: ENC[AES256_GCM,data:Hgpnn8cXiqXBEFaaNa5tU/bjrj7gcumsjq1HJSywgPPL8/WPTeIQBEeEp7JL7aAlJNgLG0gf6KARcMAhkpeg4hj5tm4EAt+9mLH3C6+rL+zY7Z46WKaXNfKrrVaWLeHlB6SyYDZnSOGc2/PdvfS5LSo1pPTJ5UCDohrgUJPmTGE=,iv:bAhWIVF7SkbJT1cTiCgjaUy4zT+Pvb680+dBdxAYTd8=,tag:RpQl1HzAAW2fE26+IOYBew==,type:str]
    version: 3.13.2
