apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:dnuBkO6MPh0/SSZQFYE4JcRBpXT3i24TTWue4h4XWurRECoV/Y3HYmRC5IXnBbil8QvD18Reeag=,iv:OViTHTgQQG2KCZ1+MgGsetiWQ/JM+wH6g7PiF2lMkog=,tag:ABmL3BYze8398fw4hOfylg==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QjQyL2gxM05LL3NSa3lj
            SlNwL0NkWEpRSTBzYkUrN29DaHV5MlZrSG1nCno3Qk5IUWlVVEZRUlVkUWdWNDRY
            azVRZWx2R3pZSlBWd211MjE0aVU0bmsKLS0tIGZKdVBPRVRQWlh3VDN1bkVWbjBh
            dVFBRTdJK3krS1BKQy9Ba0p0QWgwZU0KoAicUGLZwjqBuTwJXA9Pa7Fhu5XM9kLm
            opJyCdZZsWVwwuURKgd0d/YKabyznrBaeSGDO5EUuzBuSI241ChjkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T17:41:13Z"
    mac: ENC[AES256_GCM,data:b4odBtS8AaH6EgHuYPCxlHm3J3jWSrA0+K1DCyjyR+Kc+xiT3MPwbG6xjlkifOL8H2lxQYpsjThrSoJFrkwhIKHASXEimgP5v/nCLRk+oIKpQFgEwERyEw1benHnzgTqplkA1+lBNWzPhMl/ETLgA6e0JTlqS9ZbMWduxdTTgq4=,iv:Oqnb3RrPTyFAcry5jNROvGoXXd+BBR+jiRLIa7A/M+c=,tag:QXcbglM42rgPGo3LjMO56g==,type:str]
    version: 3.13.1
