apiVersion: v1
kind: Secret
metadata:
    name: alloy-langfuse
    namespace: monitoring
    labels:
        app.kubernetes.io/name: alloy
type: Opaque
stringData:
    #ENC[AES256_GCM,data:aaf5uRH5Jq/DEOmh/RBg27fsKs2CQFwCpjGGNLJ6WINNftyn/uIHdDsKBIuGNddBHViemV49RPPAOMvJRmzXkOT412IM1tmABAGv,iv:mnjcx/RfBeJuT64YRUKJj3R7FtedMq+55zEsSZP5dIY=,tag:HVzhVdahOPjQOcPog1OFwQ==,type:comment]
    #ENC[AES256_GCM,data:mcWPJXk02BowYkU1nGzmEC6GV4UcEjyBK/14/UPU5jJnUbkxiUXJr3tLZmRJXdDAaijrHkCS2OieKs/zOKLCogWW1wk1,iv:EEXZy8L9Mq5+VJQjQqnRZj27mKueqZblL2d7tldjPro=,tag:1mwKLgn4x5yHCcM9UUvCGA==,type:comment]
    #ENC[AES256_GCM,data:qLM8fIx/+PRe/heOkdDPfFeOlSc/FdDPH0W6AilEAzUnofM6GKjV3j20m+GMq3Gk10jS/6l8aGVnnSbNA1f05dQrk9Sg,iv:THCeYKY4wBGcsXlEz2PS49jK0dlHA18jVExPWolRMe8=,tag:ZASWX9nK1FiAab+LWrt0jA==,type:comment]
    #ENC[AES256_GCM,data:1i7fu0iAwmpnMX+Sp+ShdPB7LmKrWro9lq7f0iFXcp2OrO9Kl1jAyvIkR1s6oJiE0VmLYw==,iv:7ZJVXONSb3agF8GpHMW4A5dcSjUjMaPtWsStGWJwHjs=,tag:SNxSSfeNCzFRVGKlH0SuwA==,type:comment]
    LANGFUSE_BASIC_AUTH: ENC[AES256_GCM,data:L+pcOnq78yXsJAxCS9VyXNmjcXu8J4cS/hBII7ulx6Q2pvZ8Vb2PxsldLpMZIwErkZxG2OhaSKcxPxbZpxe+5ZAyzoBVykecKG7aq89U8+0ZF4chbQG7cQC/pYRiMe0LKFWVt9N3U7vwy0aFb4T5rHNUGZw=,iv:Nnq5xZK76+Qj7SRXoKV4QbSb0KEj9d3pVMa7Jf6x0sM=,tag:pDIFjo5OhwHADiXHO2i6qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNFArZFZ6bkFhRDA4MEJ1
            Rkt2SlBsNFN2TktNQWYxZmp4eUFQa0U3VGlrCndaSUhQWTNPaGVCaHY3d2U3ay9J
            TW0yUmlLQ0lpVVdONlNkTkRHeFo2bDQKLS0tIElJaXRiUGpaQ0dIK3NiZGtVT3FM
            OEI0dFd1Y1lON0xybXVWYXBBMisxOGsKW5BOjfiG0ihrvIyKSZuKVRlJQij/7xMN
            ATMffQ6zrrNvwYWbXqPcwYBRyqyNuRUo+Dz24s6/CGZTGQEtS8zqKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T04:13:02Z"
    mac: ENC[AES256_GCM,data:0NtfjC5IRxJyQFBWb349lBw4ohYGMKEIlZVtzPP3ILm6I9HPXLQKexVBwA9JBPl+c8npwl67KHEyFo3uIm4iYCMHXtIYdpR296wsOXjjz+LDr3eonTQjMIrPZa2QGPLeRv3UF0WLvLQqzrhSdOGAGQJ8CYeyd9Dkn+y1ZkTiwCQ=,iv:/Vk9NAVcGWWMUdfLrO7TNIZ67Gx4QW6SyOu0A03AB3s=,tag:mSK2wWVnevdRvnXMyP5dpQ==,type:str]
    version: 3.13.3
