apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-public-data
  namespace: ntfy-public
  labels:
    app.kubernetes.io/name: ntfy-public
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
