apiVersion: v1
kind: Secret
metadata:
    name: ntfy-public-publisher
    namespace: ntfy-public
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+5NatBXU379f,iv:H/31qh17z+ZgEy1cXMmIzNAYdeyjX5rayKy4vyyVKEU=,tag:LGxdQRH2rebryRQKpGWUZw==,type:str]
    password: ENC[AES256_GCM,data:7NQx+CXRk43Phdky6xvT4I1nGGT8SlHU1E5NY5ZeNMs=,iv:T7GoYxpAPmh/YFYbTX+Zpme81I6pJnPeYEmcwFEp0Os=,tag:Q8LgYCytKoKcUYKvWrdjqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VThlYTBHVllIdGExUzdI
            T3gvSk9lUnhsYlZrVk5rSlBHWHI2SDFUV2tBCmJ3N05oeUoxVm1sT2FxckFzOHlN
            cGRLOG1zZlhIdTRrZ003VjJ2M2w4Zm8KLS0tIEFURlZjd3lIZUJVbU1ibjUvSmlL
            WDFteDFScFZkNWlwVXkydFRGenR5S3cKdDB2Cu/UJjBule3Mu60JApezoWzXQTza
            8E3nWjfaabM3aZL6qRDXIOlJvJBMJvWIENZrOdDTrCXsyAhxhVL/jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T22:31:51Z"
    mac: ENC[AES256_GCM,data:Fh3IthDhDlDDrUaALafzOcetZeMBE7/1weKve3EjTqWon7MgNc5wsQA4kRbTOihsNYStn0eQWBIl8TvyxiaUyyN7cFfKbTbUEXQRTYYxeHeVLYs7AkwhkwXy3OEtldY16RaTcZRn0GkGU3fEusoTfShR/cWtKyawwC5oD4Bw0Jg=,iv:JmTTGw3ydaDzvR8zJ5Njq6qpiS0cQTKylYHXtC/0xAk=,tag:XoTSs7MYqopOEUJUFdaM5g==,type:str]
    version: 3.13.1
