apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nas

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - sops-backup-rbac.yaml
  - sops-backup-cronjob.yaml
  - backup-cleanup-cronjob.yaml
  - backup-verify-cronjob.yaml
