default_config:

homeassistant:
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16
    - 10.43.0.0/16
    - 192.168.1.0/24

lovelace:
  mode: yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    homeassistant.components.rest: warning
