title: Homelab
views:
  - !include dashboards/launcher.yaml
  - !include dashboards/overview.yaml
  - !include dashboards/ops.yaml
  - !include dashboards/admin.yaml
  - !include dashboards/printing.yaml
  - !include dashboards/voice.yaml
