apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: binks-api

resources:
  - namespace.yaml
  - registry-secret.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - deployment.yaml
  - binks-chat-deployment.yaml
  - ingress.yaml
  - servicemonitor.yaml

images:
  - name: git.kblab.me/kblack0610/binks-api
    newTag: v1.0.0
