apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: binks-api
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:v5NUlLOIaydZb7/l3Pp5ixvpy6aERln3n5jdasHdH6msetlzYebXTpQZs4GGJmuOSGOOonXjGU8Lp+Nkw7nQj6VVJcINPC3KOk6pWh5HROa6HxEnDoG6Xl9FkzSRtLoxduRSYq1wGlhrHblbH9ptpb3sbhS99L0EglFiJ1cWu1CqNLcaB6mGCLqIz32UW1RjBRM0L+5EY3CywELrymYZ2fKax5ea7N0h+F+2fFsyj+MD176+ijHtuw==,iv:jawbivD/aIIFzdCCuO8x3pe7Z3QU9yH22EE9OBqJEGM=,tag:lYIz9otPQ2IVp517l1LTgw==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSTV0VEJLVEpWSXZTaGgw
            TnozRVdJb016cXZLUjN3L0t4cWR4cEoxaDNzCkpjeTZjTHBHVEhjTUZsbENrb3Ir
            dzk5WDFVR3lJaWs2Wk5VUkhlRzJiNWsKLS0tIDNmTTRKZEdiQitYTEdFR0tLWDlG
            S09naU5NK2g5cHdJeFNacmprTjJIWlUKXR5gtNFoTfGqlxzj6mHrJc47iqnjBDRs
            8zdEf8joTObBZgJjdYciyk0HdzN1ZT2XbcxKTZGCEXy7QSaA89vHxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T13:39:40Z"
    mac: ENC[AES256_GCM,data:gQwB/Bj16oQt751r2JgBr2AnirFijvwJmI5CL2kIMn9cud2Qo9hUL/zADzksjjTIIr0spUeramJPhzpTfTJhzAms21PJx99AkpX4U0VZlpTnUxb785UpJSKtxGiiCDgWbDCduhw+Tc71zhvYhY5ZlQjW2bCS+ITmBK2C08VHlHY=,iv:xxXEXUNgOVy5k7O0g5Zdfsto6E4MvAy2n/E++HdR4ZU=,tag:GivbSrEwMdSSVAZ/EfD+nQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
