apiVersion: v1
kind: Secret
metadata:
    name: binks-postgres-secret
    namespace: binks-api
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:A2Y74wI=,iv:mmb2QvByJW9AqnufyQT2dRRN8eShs9ZoJASyn79YWRw=,tag:g6DSWE8wyyRlghcaHz0npw==,type:str]
    password: ENC[AES256_GCM,data:PzFi89HllQO4hRZ7emvqnMYlagKHBLItIZKxV77qKj4=,iv:VX+VDM4GI/0/i+a8CWVS+Ibpl9EAA1VRIqxeW7Y9eWA=,tag:El7vLbSYABeDBY7+4Ara1w==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjek56Zkc1S2lCV3hUeXJt
            T01vU05iYThkWHJrN3Vyd0lndHByRENFQW1NCjk1OTU5MjJvMzJSWXQ3S3NLY0xs
            Z2pmTGREc25BV2t5UStZdTFoOGRCeGsKLS0tIGUrYzQzTWZyZ0RzNUF3dTZ1UXln
            bkRkbkZXMEhkSWYwQ1drOFArOTZKdjgKJiwVBo4a8D0RNYl7/eF/MtJdw3Oh5cDu
            qpzGEn6bCHqaBQDSa7HSKIWHlA+K3ZiXdiUs4gzNpowRY1jmFTOTQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T00:02:17Z"
    mac: ENC[AES256_GCM,data:XSJlxgD4PmpHHLgYMCkm7ohnGoUlyYuCRVGcw66oovT2zg6QugzBcqUN7e/3voRSOoDdOlK2yNUqDWt/g1IlCjfIiCq4PTxDdqc2E+ZIlmDaVn7BEwIeU07nvhxM6TrhYyAschjFJEigyKPpQfR3Uouybf2VvcxNo79C24/Ngyc=,iv:MpFWi7tFvLCndNcTSrS/wTqU4LFnzSbWEwsiUeBIiFk=,tag:W8h4rs/okRMe6POBotitTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: binks-api-secret
    namespace: binks-api
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:VEI3sw84E6DDasWWLrNriwtXdiWzzcirljJvDt88uQ0L7pAnTvOrdOGpjC/gKZ23YpnsF2AhJITIhhy/iUIPplj5kSAwH95tk+eLcpE=,iv:lrc2ZJ+Me73iSC7P9VJeknSuD9chyXZ5imeUZUim8Hw=,tag:JBXil8toNYaF194+rFtexA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:hH+9JysdDtcFfqEJ7GdvTXUSLhJXpXZ08rhUaQU1EKmbQ1mA2I/StuZxRnzWIji5aAMzIU1Nu951eqfM+6/U+A==,iv:grZNuznROJqWKmbHtf6E2h9aBx7uxpudwVya62yOjXU=,tag:RZcFhWH9WwB9sS81lMoJXA==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:Fp6vYtxlwduep7eVEjZiNMtPgL93bqVYpA==,iv:YdiXyouXe4+dfMZRzwA3Hh9bvYeukVO4A6OYSOgnLP0=,tag:ylEE1fPWvk3ZqRROzKygtA==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjek56Zkc1S2lCV3hUeXJt
            T01vU05iYThkWHJrN3Vyd0lndHByRENFQW1NCjk1OTU5MjJvMzJSWXQ3S3NLY0xs
            Z2pmTGREc25BV2t5UStZdTFoOGRCeGsKLS0tIGUrYzQzTWZyZ0RzNUF3dTZ1UXln
            bkRkbkZXMEhkSWYwQ1drOFArOTZKdjgKJiwVBo4a8D0RNYl7/eF/MtJdw3Oh5cDu
            qpzGEn6bCHqaBQDSa7HSKIWHlA+K3ZiXdiUs4gzNpowRY1jmFTOTQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T00:02:17Z"
    mac: ENC[AES256_GCM,data:XSJlxgD4PmpHHLgYMCkm7ohnGoUlyYuCRVGcw66oovT2zg6QugzBcqUN7e/3voRSOoDdOlK2yNUqDWt/g1IlCjfIiCq4PTxDdqc2E+ZIlmDaVn7BEwIeU07nvhxM6TrhYyAschjFJEigyKPpQfR3Uouybf2VvcxNo79C24/Ngyc=,iv:MpFWi7tFvLCndNcTSrS/wTqU4LFnzSbWEwsiUeBIiFk=,tag:W8h4rs/okRMe6POBotitTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
