apiVersion: v1
kind: Secret
metadata:
    name: binks-postgres-secret
    namespace: binks-api
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:lPGLuhQ=,iv:xtlOboe5jK2w2lQkBPkZ3ilb5rBiVSVVH4yq50PgTUo=,tag:aswi/de8iDEZepNpZH89HA==,type:str]
    password: ENC[AES256_GCM,data:YefrWCMMTKKasw8k5uya0efpnP/wNJU/9yKIw7OmeWs=,iv:Cl3jJe5MqLnKcQC1M4W6c/Rk7mrfAgU2WIFG00eKCDM=,tag:E/yBkkv7+TRq+8kvf/dBXA==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZmhUeWFYZXdzaDdJRVpY
            bnpCYkRRYU5WdGF1QVU5MmZTTXJaMDdEa0ZVCktTL3J2bHBUbnpuWHNnK2hRdVJC
            N3YySHQ0ZHFwSHNDRFZPRmFicnFCV1UKLS0tIFVOdzRpU0ViUGxoVXYyajNPamM3
            ZFo5ekNac1hEOFMyaEkwYldRMnQ5TlUKZawWd51pI3KBeutCLIoDlXDaHc9rTU+H
            10OL1LNytQNdXCFtarnMkpcX3Do8ntn+mri5MpR0U+I7fJe0AFn8uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T13:39:52Z"
    mac: ENC[AES256_GCM,data:99vi6qzHIB2YzNU5lJY4h3uO50vO1y0mHuOKk4XQVkEqTk4WYzrQOniUOSGPaMmTjO4JyItDhY44BY8yCOGZBGui2lUY04TBa6pVHf3asr9sikdBI8iviPljFTDfFUeJDoRL/vL+ibRX+x4WATNBZQwL2YDsP+UBtFSWS1Sy99k=,iv:WxNUaqJOc3f45h7Fz2Sib10zfwR51OSaZgD2Zav/97U=,tag:AnjHWyuVNre/hUFDBEcQ5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: binks-api-secret
    namespace: binks-api
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:lvvM3iOZT1jChixfWozTCcgOdS6CXQcx8Fz7OIsYHW47gSk+rNXJ9ccJZDCxw8X7//uBojuJVLCn5m2EgGUR+eLeumtUGb8cPR1uS7c=,iv:QsBn7RhnTgd3Cwq19XtvX4m0vptGE3w65oX90pLs3tI=,tag:PM8vUsmR/NX6DMhfF/ZRcg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:6FHlnc9loiQKtaviLIdUEepobO8pJQuM2JEkzQ8wmRe+tTslDopKQ814+Mi7UywY63fRc0Bgjej+sK2Dgze4ig==,iv:2lOe98hkN0GUl1dxtDmXpYCl2DD/szPWv/7dujnO/PU=,tag:bsgTjW0HIL9xQjYUuW4LJA==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:g3y1oX/BapGJ+0qfoX6Ki5JGo4JaQTKxMVttWNJWj/vtWq8fll9obyUt3XCyA0fk,iv:XlfqwQeRejvrpyXbd9lJTgKrNrBFeRSn35Hltao8+bo=,tag:LqTE9BPKgolGLoKKp5hcbQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZmhUeWFYZXdzaDdJRVpY
            bnpCYkRRYU5WdGF1QVU5MmZTTXJaMDdEa0ZVCktTL3J2bHBUbnpuWHNnK2hRdVJC
            N3YySHQ0ZHFwSHNDRFZPRmFicnFCV1UKLS0tIFVOdzRpU0ViUGxoVXYyajNPamM3
            ZFo5ekNac1hEOFMyaEkwYldRMnQ5TlUKZawWd51pI3KBeutCLIoDlXDaHc9rTU+H
            10OL1LNytQNdXCFtarnMkpcX3Do8ntn+mri5MpR0U+I7fJe0AFn8uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T13:39:52Z"
    mac: ENC[AES256_GCM,data:99vi6qzHIB2YzNU5lJY4h3uO50vO1y0mHuOKk4XQVkEqTk4WYzrQOniUOSGPaMmTjO4JyItDhY44BY8yCOGZBGui2lUY04TBa6pVHf3asr9sikdBI8iviPljFTDfFUeJDoRL/vL+ibRX+x4WATNBZQwL2YDsP+UBtFSWS1Sy99k=,iv:WxNUaqJOc3f45h7Fz2Sib10zfwR51OSaZgD2Zav/97U=,tag:AnjHWyuVNre/hUFDBEcQ5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
