apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bnb-studios

resources:
  - namespace.yaml
  - registry-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: git.kblab.me/kblack0610/bnb-studios
    newTag: v1.0.1
