apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: bnb-studios
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:cbzHyUxP0led0QEt74Bo9YgpJOv7C1/lj2Aqd8EIZapHvqflLe6bEuuUjHZQx0b7v90rV0AlBZr28S89b0bF+lJBBXgmOqqrPlNjYmXL8+BqAxjtY5Jn4IZLu6asGpViu9KEz/PK9AWAQWEVgRYkEJD2SdxptAbN6TeL8rI0Ex13HqPxoBZH8iBB7nBk0FOzhrUlahIPku5g2Yq8CpxGXjtwaWqZNcdTyuuHn9W6BrjOamU/5x5JBA==,iv:2upDo84zjYL+rPguSKoQ18e0ZCtWYjAFpPrcfj4SUhI=,tag:+1kacp6nF0qLxAJ6n6fHjg==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MFNuVWY5MlNEYW9OR2wx
            TlBWeUlGbHJsQUtGVTk0WTZOdk1zN2V3eG1jCjZYRWJlTkRUbEN4dVpoQ0Q1U3Ft
            TG9VUHdnMjg1S0lkYm9naUI5WTFqQkkKLS0tIDZzUWVxK1FpenovZ0s3SjNqL3dk
            SHhJY2dYSlVSMzArWk9iaFZtZHpvR2cKQbOAqQ/kenWpEybKSyOhMJU8KUyte2Sq
            6c8hCskLS2UwD8xhVuVq5tE+sibWFlVERAVFy4lZA/sfBwMlrtHNcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T13:31:37Z"
    mac: ENC[AES256_GCM,data:gxm1wUAkk0sf4tZDet0sAhnXzh93FaM72gHSseG5LyMQuiDYkTJXkzRoVvip0rqbzzGUDZAvxNB9T6WthtZQu7cpuAs4H6qy5vhzDmoq/qraqLLxRJe8DrzEZJRwYJuDdKCMAOdIbgGbidR05y1kZYQF4uQZZNMoZc/Aht7Yyec=,iv:+gy6fwh8v0WYl127WzExZHwbLcydmfAeLHX1AbREwgw=,tag:LsjIJgv91DyRVtgHfvZCOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
