apiVersion: v1
kind: Secret
metadata:
    name: hmdm-db-secret
    namespace: databases
type: Opaque
stringData:
    hmdm-db-pass: ENC[AES256_GCM,data:QnkfzmQc2sYk9Hp4b/fRngdEOWpEed3YluEJXA==,iv:emtv+6ZEd7Ssk5sHBdMf/3GImFkkyWhgdAaG4tP6rRU=,tag:Xakz0uuaW7uvr1r6bQWUkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVmJWUnhCU01mTlFJR08y
            Mnp0RjdTMnpkeVB3NzdYVW5tV280QVZlQnk4CldCdlpORlNZOFJrRVBmdDBQamhL
            cXNhOXd1bHJIR2dVajdqakRWSm9WYW8KLS0tIHltTjdjK2o3dnVpWmtBc01DaTh1
            LzdrUXhKaUlFY3hPQVBmQVh0cTVhNG8KPsuuQxgoKASskd/pxZgNDa0sbPVS5tgP
            WqgVxggOuk3ZkJuMel2k51eTlktWDiNpztUZYsxCEJ+TMfCbY9vfYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T19:39:04Z"
    mac: ENC[AES256_GCM,data:2Or8CN8G9wkx9XH1JJftZpMq+ZWs0nFcw+N2ZA8WOWPk5pDzdUnGdxTvsRkmjIlr8LVqmliUFpdq+iOMTMus48wsy4Lv+mC5y0PGO6e8aOMhMpVl9NQWNZFq0e90fM0sp1NgKcfWPbqLQjA7lLMp5Tm2lre95ZyaFTPOXG0agdc=,iv:lf2z/scBkoYgwezFVe1cXIT6L5la+G2XbAamkGeAb1o=,tag:HudZwGZe4Os9fvpxMKkC1g==,type:str]
    version: 3.13.2
