apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: databases
    labels:
        app.kubernetes.io/name: postgres
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YOJJuxZ/DEbfLoCua31MQbDOvzE4DOiyoWwwWdIKWow4eQRc3FyAewmE4Zg=,iv:5fdxuazXydqPXGdfUq22hf4H9Tt5smVrhl9egK1SISU=,tag:/pma9AqaSIxYCc+jtFzyNA==,type:str]
    POSTGRES_MEM0_PASSWORD: ENC[AES256_GCM,data:qGwtSzFGETVURMJNDTLdGbqBkvCUSRv/sbubmF8R/GYyh55H22fjfXPAHwo=,iv:IBvmPfL5FGEDQfO9YgGykTR+cjWD0zTqGv/NsKJ9EkI=,tag:jnc8kGOGO+H4xeZN7gm21g==,type:str]
    POSTGRES_LITELLM_PASSWORD: ENC[AES256_GCM,data:77JObmubCf/hE8o9U/vzcW9QHjAsCP6zZk5evq9UmWA=,iv:9gGANek+C7+mnhPSdlbgpcMTPMJT4O589OfRpg0B6h8=,tag:D7NjRjBS+ZnZj/OTJMuyOg==,type:str]
    POSTGRES_LANGFUSE_PASSWORD: ENC[AES256_GCM,data:OPeXrqKeZShmFU+4dABS1E0+nSrjyyKfxHCceDwF,iv:SIz0T6hglLDwy+fLpW+QgAuKozLGtqSZfy62zMpqqA4=,tag:K2a9b2rDGBSewyX8CMOWcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MWIrc1dVZU9lWWdhRndZ
            Z3FrUExhTHpLdTJSNXRybU9UNWhGRDN0cnpNCjJTNUlGT3l4K2FoSGRHMy9qcGJz
            WWJBU0xZNjFIWVdaOThGRG5ZQ2plVUUKLS0tIEk2d1lIemhyeHdxT0JSNlJESVVF
            NnVnOVI3NnlYVEplK1lUL1pPbTJVVGMKFNG5GttOYRTW6SBELl+SIf5uEJu9oO5W
            QUszm7+JQSoYtBms/Qj9Vp+EKj4ZeVdrHwfENxBrMKwUultJrheKpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T14:17:50Z"
    mac: ENC[AES256_GCM,data:D4TlmHqTYrum4RaVMaQ7A8WZThmYJE7Wfcz7YjnWKfZQ/1UVbGz1iwFKX/ELcIE7xb747JspJDySgt6vvQbQ1Eos7inJ+MT/uVto0MxQSc0wEYeebqEJoJJTh2H6uQ7lG9nZ2A3ObdKPLkczGkINCGbJJTmdFYVic1e1Cw5cE0Y=,iv:IIr4+YfSwKaf3tP68zFn6X+WYyLDGLylKLZ1/E0K9oU=,tag:ECLYBE8EwD5/BEccEtX7xw==,type:str]
    version: 3.12.2
