apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: databases
    labels:
        app.kubernetes.io/name: postgres
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YOJJuxZ/DEbfLoCua31MQbDOvzE4DOiyoWwwWdIKWow4eQRc3FyAewmE4Zg=,iv:5fdxuazXydqPXGdfUq22hf4H9Tt5smVrhl9egK1SISU=,tag:/pma9AqaSIxYCc+jtFzyNA==,type:str]
    POSTGRES_MEM0_PASSWORD: ENC[AES256_GCM,data:qGwtSzFGETVURMJNDTLdGbqBkvCUSRv/sbubmF8R/GYyh55H22fjfXPAHwo=,iv:IBvmPfL5FGEDQfO9YgGykTR+cjWD0zTqGv/NsKJ9EkI=,tag:jnc8kGOGO+H4xeZN7gm21g==,type:str]
    POSTGRES_LITELLM_PASSWORD: ENC[AES256_GCM,data:77JObmubCf/hE8o9U/vzcW9QHjAsCP6zZk5evq9UmWA=,iv:9gGANek+C7+mnhPSdlbgpcMTPMJT4O589OfRpg0B6h8=,tag:D7NjRjBS+ZnZj/OTJMuyOg==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MWIrc1dVZU9lWWdhRndZ
            Z3FrUExhTHpLdTJSNXRybU9UNWhGRDN0cnpNCjJTNUlGT3l4K2FoSGRHMy9qcGJz
            WWJBU0xZNjFIWVdaOThGRG5ZQ2plVUUKLS0tIEk2d1lIemhyeHdxT0JSNlJESVVF
            NnVnOVI3NnlYVEplK1lUL1pPbTJVVGMKFNG5GttOYRTW6SBELl+SIf5uEJu9oO5W
            QUszm7+JQSoYtBms/Qj9Vp+EKj4ZeVdrHwfENxBrMKwUultJrheKpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T03:38:00Z"
    mac: ENC[AES256_GCM,data:14I9Tg4UVGb8qfUpmuqvnuI+ctrkcYi3tEVEqTcUZBSZCv8PP8GpzIdtxfs3JKqxsufClDMHaDpbfpLG81Rug4fclm44l0/Pcu/yzL0cBZF7grWURndnzD7aqT3a4fFzdeQkZ5LTa8WG2vSIx24Aa2H9MGQ6k3PkhLECbfYt2XE=,iv:xeJ+KKqI3d+SX0fUKsFKYQKk6LpHC5N9KDSaJWn1r5U=,tag:DFzQ7kHL6cspawTzs+Wv5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
