apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: databases
    labels:
        app.kubernetes.io/name: postgres
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YOJJuxZ/DEbfLoCua31MQbDOvzE4DOiyoWwwWdIKWow4eQRc3FyAewmE4Zg=,iv:5fdxuazXydqPXGdfUq22hf4H9Tt5smVrhl9egK1SISU=,tag:/pma9AqaSIxYCc+jtFzyNA==,type:str]
    POSTGRES_MEM0_PASSWORD: ENC[AES256_GCM,data:qGwtSzFGETVURMJNDTLdGbqBkvCUSRv/sbubmF8R/GYyh55H22fjfXPAHwo=,iv:IBvmPfL5FGEDQfO9YgGykTR+cjWD0zTqGv/NsKJ9EkI=,tag:jnc8kGOGO+H4xeZN7gm21g==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MWIrc1dVZU9lWWdhRndZ
            Z3FrUExhTHpLdTJSNXRybU9UNWhGRDN0cnpNCjJTNUlGT3l4K2FoSGRHMy9qcGJz
            WWJBU0xZNjFIWVdaOThGRG5ZQ2plVUUKLS0tIEk2d1lIemhyeHdxT0JSNlJESVVF
            NnVnOVI3NnlYVEplK1lUL1pPbTJVVGMKFNG5GttOYRTW6SBELl+SIf5uEJu9oO5W
            QUszm7+JQSoYtBms/Qj9Vp+EKj4ZeVdrHwfENxBrMKwUultJrheKpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T00:49:26Z"
    mac: ENC[AES256_GCM,data:OlJ/ROTefumu5pcAczQAnMT066NrQ5sXf0KX2ZrtbVkUhs8bZtAEEH4mHw6M6nGadpGuaRQ4l8iyh5xlVkRbyhv4oaKLUV/HopTffwsx6jCCmY2htdBWj43nVmqzvYbQrwVMB1JYd4MMa/xIUm4mmtSiVTnuHfVRSwLjqJAVv2o=,iv:RPn582C8MGIOz5PJuBTQxOyWa8yCExsNqw7D4irhyNg=,tag:w76VnJMohWu0X7q7rUpGnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
