apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orcaslicer

resources:
  - namespace.yaml
  - configmap-profiles.yaml
  - deployment.yaml
  - service.yaml
  - tlsoption.yaml
  - ingress.yaml
