apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service-http.yaml
  - service-ssh.yaml
  - ingress.yaml
  - backup-cronjob.yaml
  - runner-config-cm.yaml
  - runner-secret.yaml
  - runner-deployment.yaml
