apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo-runner
data:
  config.yaml: |
    log:
      level: info
    runner:
      file: .runner
      capacity: 2
      timeout: 3h
      labels:
        - "docker:docker://docker:27"
        - "linux-amd64:host"
    container:
      network: host
      privileged: false
      docker_host: tcp://localhost:2375
      options:
      valid_volumes: []
    host:
      workdir_parent: /data/actions
