apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
    labels:
        app.kubernetes.io/name: forgejo-runner
type: Opaque
stringData:
    FORGEJO_RUNNER_REGISTRATION_TOKEN: ENC[AES256_GCM,data:kY+rGP5qYXBs5hu/pBia5u3PTkyEZzGEsPkx/6rMLZVXKS6+SCV/Tq2JzA==,iv:7Y5XHn7sjKzRmuQbVvlJ9WTL/RUcoNv3uOX09lWKEIY=,tag:QlHENziT/h+lUfZg9VNX9Q==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYTFMNWN5djgwN3AvcU9m
            QzY1OTBGdGFibWJUVHkvcWh0RlJseEhJTEVzCk15cGNLa2pYaXpnRnFpU1NEMnFB
            Y2NMWXA4dU1WUW1rb09pc1RXcFA0M2cKLS0tIEFuOFJDTlVmMzFMNEU4bHRycVJZ
            RUZlUXZnRXZ5NThFY1pSYVRBcXZHd1UK2G5mKZmVGMRMWJaM3dJss2dmDxqcQ2zL
            ZRzTCXs+Okhny3ZLYfODTLL9sK1cAEIUqP7FNVJKU1qGyVdZMRtBFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T18:27:04Z"
    mac: ENC[AES256_GCM,data:yjyKwynqIjxPVohHP3m2dryxxiV10sCze0UpAMqVNFXjTeuDKuJ7LyZ3MMg/r4AMkdosHWevoCMjnWL6DgQQibGp41UC2n0BQIAlQpX01ASXl0sZ/UoRwF9aY6VwzqQHu6JpJxLWmWXxPeZIV5O2aDEbQr0Ou+9iSDPjxfEeXbo=,iv:X0NybtwR7mc0QuF7LjiRJhKtu7K79hx8eCIe/8Wmt7w=,tag:+8MvaS2V8N3jh/GA9Yv6vQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
