apiVersion: v1
kind: Secret
metadata:
    name: gatus-fleet-token
    namespace: gatus-fleet
type: Opaque
stringData:
    FLEET_TOKEN: ENC[AES256_GCM,data:A9dxONq+n53FFifXNT/wvIbBLBe790p6kvo8AW71XfFtZQljBjBxHw==,iv:N11X1YoF22bPo/xZ70iRSX6RK/gBM3H5vFyNWKZ4B74=,tag:fpqR8HTK5xM77cA9teDNJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL0VIWTh5ZUE2THBUL05n
            Z004aGRFcWtYeWhwelVJRzY4bFh5Q1phUUhFCjRzVEtkWFdKblZpSXRSaE5KUG1x
            RG5sK05Ndmx6dmlmY1lwZkZIa2J4ajQKLS0tICtRUHgzL2I3Wk56U2xXT2I5K21E
            QVJnYjhoemZQNGIwaE5TWmdsQXRnVjQKXcjzqqAgnIP0/4IETqKD8lcu7xFKUVlQ
            oacKk1j6uxVxgP2N+oLSLVJi6sataRl6EHWZn7hnSvJXYMjAbsO7eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T22:48:57Z"
    mac: ENC[AES256_GCM,data:9JP1PkKFwWNXfdSZSTVVIDoBTfAjw79oEAxHqK1VpK/lRwscxc3vrMeQuTHtYi9qRiTfqG5cDPEgglRIyw0WBvTcUKDHHGwRiqgp3ShUoqVhl+5h7zKo/CT2iev3Q7twrZhywkdWt/JaqKWRHLpD6P24Jr+e6+vyGdvJZblg6Nk=,iv:VrXbVp7KqKbmDAjaJFqGgY1fw6H23Sx5GzFjCH3arDQ=,tag:PEQCHE2I+5IhsqeRz1Sebg==,type:str]
    version: 3.13.2
