apiVersion: v1
kind: Service
metadata:
  name: gatus-fleet
  namespace: gatus-fleet
  labels:
    app.kubernetes.io/name: gatus-fleet
spec:
  selector:
    app.kubernetes.io/name: gatus-fleet
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
