apiVersion: v1
kind: Secret
metadata:
    name: backup-nas-credentials
    labels:
        app.kubernetes.io/name: home-assistant
type: Opaque
stringData:
    smb-password: ENC[AES256_GCM,data:P8DZ8UQjPAUrwOL3LrwlwJjxyq5Vclm4ktBVIEbSTa8=,iv:4KNNDkgcRXLXs8jQUKWK8jFmIMUPNURGtBc4wT5Bf4g=,tag:nwJrrLM1L8HAHTAm4RZ4Hw==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUzk4MmY4TFVXMW9McXFh
            M1BIU214WDBDYXFGWHZxcGRLeDdwN3E3M0UwCk1zTWtQcU5SNVRFQlVpbEhITkpC
            WEp5MHpvSVl5UVd0cE8rdXVQcmRuWUEKLS0tIFFDaHhuZHdudDRHNTM0MlByTmVX
            VUtDUFd5RXZNbXREUHFBb2tlWjNET3cKfCGaweXHSGpdFoXLIczLPl0tj1Z82aSd
            l5FWhSQmqwe6VNEsOhr6mvFKgm6KMjiX7LFa+Tzeo9Om/ZMaMwkIVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T00:37:50Z"
    mac: ENC[AES256_GCM,data:skGWbgrBv7n5xCwuyRNDG+IxJGrZr4wZfZPqY/EjWH2f9hEArHMhb9s8PKHYeNdNksa5sznA8Mq9iPzuIxPSYSA3Nsf0xHfns/7J0Gi3i9zYdavo89MaISQ0pezOJHDUSlhwHxE/YAp9JXCK3lAMGRK0+cnYJ1KWVnZydtnf1fk=,iv:ufmJJqyVg4Q6t2F2R+SBrCVd3Ll8pB1FH14PN+GZE9M=,tag:vWF6jNivpl99WXxyBHLgxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
