apiVersion: v1
kind: Secret
metadata:
    name: backup-nas-credentials
    labels:
        app.kubernetes.io/name: home-assistant
type: Opaque
stringData:
    smb-password: ENC[AES256_GCM,data:jdB8NO7MZn5959jUsQxQUcRwdGMpMkbG/g==,iv:yulqYVUMs5pqxsCUAkkTtTum0szqW91iTdz8i0mDsy4=,tag:DO7cocCxpRE6lBQr5uiJoQ==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVFpDWDlEZmRwNTJPc200
            c25Wc0MzMVVObEpQWTBqMHpHZ2wwMEU2WVZJCjVET0RnRXJmYjVldlNjZ0pLbmFo
            R2JuWTR6ZmsyOTlnK3RvbGJWMmpqYW8KLS0tIHdleThhRkxrWVZUNERQU1lFR1R4
            a3dub2dJSldyRCs0eHVhRkJ6S1hha2MKgJEPrEIScF4KgaoDFs+934xXTPcXYdmj
            By11Vorg9tNJmXabbdxJZa5gXPlvNb6D3nEx+xVne0xZMJs+o0isfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T16:05:27Z"
    mac: ENC[AES256_GCM,data:UbEOYgDNRxNoPePYpFYLHQA0+F+Szrx+vibv52XtrIJnNmV/rcVNzs2IdwTtbwlg+Vi3f9EuVr2wlG9aidKhDHF+4a6sBtMNuCSS27ROD/4neMNuYMRj0tKsBFhEEzAHdaSJcfzMdvToC7jDYWd7X9VGR69CiIfgSkIKqHIUA/0=,iv:luTUVipcs0eQKNs9qH8v5XSgOcxyIlt67ymvlvCDZ/A=,tag:NJFcV3uaLSwv6CP2Tt4OKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
