apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-calendars
    namespace: home-assistant
    labels:
        app.kubernetes.io/name: home-assistant
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7OjF5R5jY3lC9+xQJ0xoEpucbJeKd5XZQD6xjiFjto43+pLEF5CGzSyhr1cMfC8To/YL2x5Ud5aOtWCBTr8Wp1hlU586gzEiRTA=,iv:77jhQpSJlmHynMr6tZROzs99fo8+yUp7Dh6nJX3d2BA=,tag:TzjOTKA4FPjG0nTJcelsYg==,type:comment]
    #ENC[AES256_GCM,data:gSftM2cwW1Qh+izN4Ou3FW6cFmsqjwCN9bemaxTEScLweFFU4wyCWKeEdgFnpKbCyi+JExkL3cSc0cDR1py3NguU9cG2CBI8c7fZUhU=,iv:UD1wfbNx8wQVOHTvWqt4YwAfXV0+yWOVpjW3uP3YVAk=,tag:L23ih+vHPyCUkSEnPD6f5g==,type:comment]
    #ENC[AES256_GCM,data:DTb7eE2HlmRwlGCkX6Cep3C9RSy9w/ZB1x8ISKONOyCTIqYqB0TU6SSInFB59gWd5KIHeFSCKPuO8C2Mc7XXGJ1KlUlZFtgzgS42+r0=,iv:Gb6jfmmMLB+I/P9oILm46ExyoCVNbLRcKYAETZyOezc=,tag:JNAAsjzBZps1vFeE8rLd/g==,type:comment]
    feeds-json: ENC[AES256_GCM,data:e84dEw1j5M+t7u3EFlrVO6XqqH2xLRuu1TQcgKDkVOafJ38y8Z61t4p9IVgCWWz9iX0aDgGYikywGZwOTPmu+q94EKiNbGt7bMv9AKoSYcTP/XrV3u1VtnpQVS5pqbjDWsj9AySO6SuDbBsuKSJ/CjXTwHsX7NTJEq7r,iv:IhNB7Hun9+FZOzI6sXxDOs6Wf8KBQGkKC3MhznpFDZE=,tag:oPWEx6eKZnGhB/Lpni6Pbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU3g2WGRMYWgxeGdMRnhZ
            dVd4RE9yak53ZnIrVW9mdHR3L1RjMXdhbVJZCldsY1U3QkE4cEN5N0pzVEx2UHRG
            ZlZNNElQaHM3UVFITTAwQisvcUNUZTQKLS0tIGNmQnpXVDNuR2RtTWJ1eExpRzZ4
            OWswTy9ic2xWcGFRU3ZUclFuUkYzVGMKdjiMn3bGfYCDVmNOsLfg5VPQVYgU1SnU
            ts2DlfLxJi5JQ4ZFr9AVeo0ItYuSblD99OMcntf3IxWcaZRRhCybuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T16:30:51Z"
    mac: ENC[AES256_GCM,data:3R7VbWE+oOC9ONdkIh9ZL3OSosSU6PJKUfaEpz5DYfvwsGAbgpfcdOUtYpMW0YfvBG1UVbDFVxNBJvg1VAziiGC24yZvP8vsA4TzWd+HdNUi3XlV3bwYp+3Glt1lBpfc6/gCF63WZSdgsJjO4oleLyC0xqe2+bzHUvzN0yTEzIk=,iv:jXz3sM2XKkLQLlU3/si+7D0xwSGMf53GcJGhMCBWXF4=,tag:dCmpMnBQblNPNT49AQzFmg==,type:str]
    version: 3.13.2
