apiVersion: v1
kind: Secret
metadata:
    name: litellm-assist-credentials
    namespace: home-assistant
    labels:
        app.kubernetes.io/name: home-assistant
type: Opaque
stringData:
    #ENC[AES256_GCM,data:y1YTxeOyYDMwU3Y3JAv/6MJ958yBmrL0Xl21riAaIzFBc4zJqQP0gwt+Ru/9NMCyVfsNXBXJlvq8xXiESOX8WdsI4g==,iv:uEokzniD/yBJHq4ar5UrB/nlVTKi1XDen+8pkuiHXyw=,tag:dxuN7cwELGbVkWN5bUTBFA==,type:comment]
    #ENC[AES256_GCM,data:kwPA/+UPshZAOK4DYgNPIxgTi1nSSjB1z57Vx10FMh7h89hmEvE+/alwL1+OIsIRFnDbNgDHMrvSxEbviVotqyMQEICYEG7DwIBOR6sGu1N6Zjd4Sxospw==,iv:unKPhI6yvN4L//WGedViPEHyqfGSl+Ji3eBs/jwHPFY=,tag:o1eoTbHFRiQGxZor+7uPNA==,type:comment]
    #ENC[AES256_GCM,data:awFWryQ9zx+6bPGI0S6AAFu2tYAY4N+iqYLoFRS3lCxaaHKNF1uaGH4m4AZxBTXj/KrkxTohRZkwoYB78tHxdlbfOIygeXI=,iv:kV0ofD4hRb1/9RUDnse1OPd5awCZEYu2Mkb2ecqldxs=,tag:Np31z8J03a2LXE/yQmbYuw==,type:comment]
    #ENC[AES256_GCM,data:Lo+AmXSYPHNiKowirkP5wARH+E9WFlckmo3x0NpY15ibQ59jIjUF1/jrAxKxgGw35Us3SAkXcwcMZyAPDaz6ikpWQn47594kFA==,iv:xtnyQso+p6bUHDfJFtfI0brHV8rTjua4L63djOJSe/w=,tag:6aMO6cp6QLH19aHXM2ge1g==,type:comment]
    #ENC[AES256_GCM,data:lPe5VlzZCJ8IsJvR4Ih/7jm1pTeqpB/MkQOdgwHrPXxjuTcthJT9lexun0g2fHkHpQC5yTHjC2CdIiPPV9Xg9PX4vVQCw7UW,iv:kxJmP9g0ULz9zZc70nnJ+CBybW/eZtc5f8ddOGvwEHw=,tag:+7K8H/l5gsFwv2pjfUP4vA==,type:comment]
    api-key: ENC[AES256_GCM,data:DQFloO1HX75VCLrZXiK4tF1Pe3rE52tRTQ==,iv:sFO/NXhLKicQWH91w7yR0WS1FUvFgcGPY0jowV+yfqA=,tag:evBS04hyXooMIyJIjqnPmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z01ZNFVqTi9uUU85Sklw
            c1psbHpFd0lCVC8rd3pldzUreVdOWjNRMkJVCmtNdjdvVnViYzl6c0tmWS92VHFB
            YldwZlYzYW1HVG1ldmVHTzJacU5WL28KLS0tIEpaMTJYWjU1dHhXYWFlWmNZOTU0
            SHRwY1prdkdKTjk2d2IyNm0xYk1QZDgKxnk/WJzQVhM480Sso4RteW5z/OEf97LL
            FjNLMypRxRLXKDo25T+udi1LQ2X74Tp0pK41otndn9qGHAvty1XtxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T15:34:44Z"
    mac: ENC[AES256_GCM,data:b/2T56f3p7Qsh2l10d7pGq5nntsCvryFTn79sU1J0pOcH5Lly+N5KN6XRi8z+eEyGNrC6KJ/W82lbdUdxdjSUDvS55l4HtHdbcJZGC6CMA4Op3XSguDH3FYqUIlVxmIWUbHNJ8Brf2+CXW7iPXqqMCOD6E8qUxZqZlQMxj1sFa0=,iv:OMMyArS78AdujtqGzNZAzd4AziMaZQWdvR+Y5XLBsxc=,tag:/A5HNDgFg6TqOg4tn6SWIw==,type:str]
    version: 3.13.3
