apiVersion: v1
kind: Secret
metadata:
    name: litellm-assist-credentials
    namespace: home-assistant
    labels:
        app.kubernetes.io/name: home-assistant
type: Opaque
stringData:
    #ENC[AES256_GCM,data:zJBY4AmekyHcWUXxqM9EM0Z+Re6dchxaudiv78uK9itZAOGOM0wYZsOaKfHaEWUhqaWrS0g/ktOXqIT8kACXPduWxw==,iv:UEHTDaKEC9mO20GHsFoBmyTXdlY66Ha/zWzuUxmzr00=,tag:GJJNpezn6ZZwYaehiShesg==,type:comment]
    #ENC[AES256_GCM,data:swITqje5ty+18Wu9WLk+GsjttnFGdiHte/VBSRWdlaqfRo+0q91/kCGRrD0nYBiBZWIe8R0gjSih3+GtXSV7b4Y=,iv:ymRr4w5OLQ8NcZ3Y5USxbUbq9FkJoAZxJ1MJvXgI1Go=,tag:9C0VrY6BMOl12kLiXp70Jg==,type:comment]
    #ENC[AES256_GCM,data:aG77JQmadOtv8GhafdqboQJ/zVAaylDPZWqwiz05PYr00i04MQfPiMO0pdLqKvxdhGH6F6/2CmstCdpTtJ74omU=,iv:x5sbFBrWsPoVQFU5ZxyR5YRMTg27ogbgU9p+JWfkzik=,tag:tLDJMeI/oxYTggtI1CBJ2A==,type:comment]
    api-key: ENC[AES256_GCM,data:rOOI8td0sZIG9shskOtTBUuh9/Ifr5sz5Q==,iv:KzoRNW3IUROefkuP8ZcyCAEZFLTpwktYjktMSxrbNu8=,tag:T2kHjWdtnfOuhYAU351EQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WFdBK3hzVHR4YmdubTNq
            QlE1ZER5TEZmUEFWUjJNQnNjUmtwSGZLWEdnCjBKZHFEdjlYdXNLYVhHeUI1NS9v
            UC8xY1RvY2R6YnRrbXdDT2lPOXZWNTQKLS0tIHd5YzZ6TW1sbEtZa0w0QzhZQmxC
            T0s0ZmI5azh3d2YyVjh3b0ZWbUhlYTgKa0mpfnlyFmETkPJNQ8FIKj4wYUFvA2BR
            Vf6j0/5clMAfXXcE4ePKRy1qWF9o1uBftHiPOLkvAqdQ5Xhnt//dHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T16:38:30Z"
    mac: ENC[AES256_GCM,data:jdYLVPusOZHEQoplQVdSBl+mFgw43fvFlVlqq9L2nLN+aBqt5Smc8grylJsohIAZ8+n9uDaEaD51Bn2OyOrmXcOP7w2QKnQ8PjcakY+y0xkSBqvW7DlVcjNwJJN3RQM8jfegJfNYFGDWmvNt9JinV0+zF1iNvNWQPPxIYlGLOWE=,iv:QUMSQLHHTCwRSD/RaUuY5rzQFHGrxN09RcyGp4EkeVA=,tag:vsSg2MMi8ukzLg1OutRikQ==,type:str]
    version: 3.13.2
