apiVersion: v1
kind: Secret
metadata:
    name: localtuya-litterbox-credentials
    namespace: home-assistant
    labels:
        app.kubernetes.io/name: home-assistant
type: Opaque
stringData:
    device-id: ENC[AES256_GCM,data:/gjHyjT53iosTHyC9ZGZZOoJosCfMQ==,iv:KW9k05t2XU4Ct1N2GWLZYKuNK36cihG3M/SeWtWCAtU=,tag:zSkKR1ojQuVqo6TB1+REyg==,type:str]
    local-key: ENC[AES256_GCM,data:9Ggo3epfr31Yq0vSsPOi5g==,iv:69+MzkUWPLZoILupwOTTYfOoScMQqom8kZ4ovcobElU=,tag:gZhr8ddWcUuAqv4zWWvyvg==,type:str]
    host: ENC[AES256_GCM,data:1KvIbuZJjcg4kLgP7w==,iv:SzLQNzP3qRrbBNmL/KUihY9YYz7/3PBLrjvShndO6Dw=,tag:XnGycpIHheRwZwnuq7aqEA==,type:str]
    protocol-version: ENC[AES256_GCM,data:VIPK,iv:RuCVLuKRDTXvEb2q1+BLvlTRnsa/IgIeogaZEBTXhdY=,tag:Gx9Us6mVB9yKnTxd4xqTRg==,type:str]
    friendly-name: ENC[AES256_GCM,data:K+JpPs6GsbtRN11pYkQ=,iv:9a7i2quAZXF1nQppH0XSpRD2LRd+kHBGjC2Tii6Nbcg=,tag:TiIrjsh+Qr9tzNz9Rg/FQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZGJqUUFJZnlLVG5sejYy
            UC83elozT2pxSHBmSEJZWFZ1MlMyZ2ZCeVI4ClhNRHBvYkpDR1NOV1dSQzhnam80
            ZCt3S2owanNkM0g3RzdpM3BqaG1rU1kKLS0tIHJrb3ZlK241S0N1L2h5cThvaTcv
            cWxqWGhEVWs0c2lFcXRibDFxYno4TUEKk5LFW+r4DJKpbtNlQ1oXLh+dq+SCiIW0
            G1AKbulUCcND8oe5kngVgsJM5880pkKTZM0KwtyC+TWF9pigBW/teg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T00:36:48Z"
    mac: ENC[AES256_GCM,data:zeB3jqm2g1GRqrFxx+MdnakSeoiDBLSOX1+NVySCEq4ed4Q6McFUEGGhrwd6/8V/HzCsJYzDGdUj5jUc0hJ+YnN4muTVusQ1WKxCVNxncZKQkwn9aVzPHFqqVT7OtrZBvzmFbx1W9vW5Mwu7L58Uv05wCLbFDaGY0e3jb533ZEk=,iv:ogVAwFhhuq1ZvJNkEApNt9wBQUacoidEwtptgpt2pbE=,tag:RDOiHzSP5tmJQLRy6Bo+OA==,type:str]
    version: 3.13.2
