apiVersion: v1
kind: Secret
metadata:
    name: tapo-rv30-credentials
    namespace: home-assistant
    labels:
        app.kubernetes.io/name: home-assistant
type: Opaque
stringData:
    #ENC[AES256_GCM,data:dH53yU2poJURz8vL+PC5Eh1XPxZX+HwSDFvVoWe69a0VWE42ofR9bgP54JONexzaOv0HZ8/2zxKrQWbTmh+GVd69dHliHFglw/o=,iv:UPDt651bxVg0dMqUApzrAzWQ8VxSUBbES8IaGPlWZmw=,tag:CJSZPGzTnTbHiiEso1mHSg==,type:comment]
    #ENC[AES256_GCM,data:Wiedlopn0dAVRiiZgD2gOyb610cuwETZ/SU46weyq9e1HuwuDn3+nmtGZeZSnhnj3VIqePQ81YStapFtAiLRYbrhC6p43CIfYELO,iv:Fy2N7rF7h+b41qqX/FQ/Dpzfq0kIK7DASa5GI7xp+m4=,tag:C5kqgzvLGColxUF+W02Eyw==,type:comment]
    #ENC[AES256_GCM,data:RBGa6+LDMALGz74jMINuizNZjv+mejom9Q8P+DxKwRDMqVNDoyXTHkKPWHe34hOkP7ujles7i9EnA6IpveAyTJ4QCQpMOWWf/fM=,iv:e1Y+y+NNUdBe402Vt79E9nfvXlHkzWKaImXclhe2rCY=,tag:bnkYD+2MGhkSi6Kz9osFBQ==,type:comment]
    #ENC[AES256_GCM,data:ws3J6ZvnHUc3Mloq3uvCq/iNTwpPxJR4eatwZddm316GfYH33Gp5N2r+DPpl/v+irmNBnEF6mBL97H3utp6bVcm4bluJjw==,iv:KnOGqjg3f7k4USgMSKzEsoCTrNRB6RGK7RT4ZiZFXSU=,tag:CIgHWyhRXr+GfR8V1kOt3w==,type:comment]
    #ENC[AES256_GCM,data:SEtAnC2uHYu1BdOigPzDueTHJjwPWX+ij2xsuXM+n593pDgbUfhI1QQceHfRZ7vSaH6JfbeXeBt+IIVXRjl1Xrzk4feDszyR/SWRPt5rWHYkpkTc/iJ6aYgX7WaIJw==,iv:oPMDoWqUkvnes9TGElAKqQObZR12W5K4ZbF3lmALBi4=,tag:+om//y8OFA3O4hkdw2C6/Q==,type:comment]
    #ENC[AES256_GCM,data:nQaiAOIK6ogsU8HHmntwUWPmj1HlLlNDH+xEadqSseYbbDod9iZZFrUPdl+0PUWzN+yh6KfetYADeahB//WGpI8TX9CdnTXbA3CQueXBX2jdV19a6ws+3++4NdF9G2Se+U4XWn1W,iv:84E2C9gQHe1Bdhxe8tswxuLIiSZnC7ZOX0dh7BYt0nk=,tag:Atr7id2qEYVAHeDAu/HhZQ==,type:comment]
    #ENC[AES256_GCM,data:qHa7WTB9kWn/mdt2TKOhi/bdHhmPh/5f4df2xb6KZrHyTqPzu1xEuCkWGzTzwahpNSUhVyFJx2Z/Ylca5c6g2lUKJZIsGGXg2UrMTEE7b40XqwxDsfzf1jGr,iv:pisvZa+BSNpmcPDpH0wu8dbC9wR3rTeJhxKayd/Eio0=,tag:bQfXDimXRn/m7//trBRA2w==,type:comment]
    host: ENC[AES256_GCM,data:VSExyf1n2Euz6b8p,iv:VvgupNzqPszEk9YJj3qtDXwjh4g2UlQunEcbwvbOD7I=,tag:xPyfKyKCTG7cqToctmtc0Q==,type:str]
    username: ENC[AES256_GCM,data:9P/0PpKYSMkJVje8ad3eCKa6tHw=,iv:g6HVOpKKxJFR+GOzBrWp4bB0ZrNtzTmFZy73WLJMc1k=,tag:3NztyG0TqGEkJ36kFKSHRQ==,type:str]
    password: ENC[AES256_GCM,data:Gn9INnp3m4NCGMwNyQ==,iv:Snt+iK3Gte9pzprZ0fkeGkXp3Y4HOtVv3/mnYO9WmDI=,tag:0OWlC/pT4ZR/4RehWkWLSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdEE5YUVreWJmcnNMRklS
            QXQ5VU1iT0hsaGYxYnRmY2FDUVNRa2hIaG5zCnBYaWNiVjlZb3VqdmN2SmhMeXpi
            dGhlUVRGV2E3dkgrM1czT1JLK1FnYnMKLS0tIERlWDA0Q0l2d2w1UHludTV3emtG
            a3lZaGZiZ1VxZnJjcm9reHFhZmhiVncKXi2DRCta91/XGTVr+tcR0KrjMG5d44LO
            hmcvezWIqghKzcqmkXXQYwbm2CAheyqNzRqeZ8mPthqaC8cme7/EGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T13:30:35Z"
    mac: ENC[AES256_GCM,data:y/OX4crSiO4nDb6PokmEu5fUdJD8cPWWJkuwxYtmG7wvcEx0FMRhiQHm7fMm938w8+DN72RDMhM67tCgJNsHLlprY3QPuEVL/Hdh1HgM7P8K+Ss5Qcgt7nwOMneHfSAPFVPtrTUMnbZaFHmpPhP4283p4VNPtDfiqykyv4KEY20=,iv:g5OHziRg9G7WmgVnwKDQHBGtahhd36RbFjCpob9LMpM=,tag:zIqcEc2I2z6dhZznjp/uZQ==,type:str]
    version: 3.13.1
