#!/usr/bin/env bash
# audit-orphans.sh — find cluster resources not owned by Flux, Helm, or a
# controller, after filtering out auto-generated runtime state.
#
# Usage: ./scripts/audit-orphans.sh [--context home-k3s]
#
# Prints one line per orphan in the form:
#   <namespace> <kind>/<name> (<type>)
# Exits non-zero if any orphans are found (useful for CI / CronJob alerting).
#
# Allowlist sources (documented runtime-managed resources):
#   - kube-root-ca.crt  ─ auto-generated by kubelet in every ns
#   - sh.helm.release.* ─ Helm 3 release storage
#   - *-tls / *-ca / *account-key ─ cert-manager auto-issued certs
#   - tailscale-state ─ headscale runtime state
#   - cert-manager-webhook-ca ─ admission webhook rotation
#   - kube-prometheus-stack-* ─ prometheus-operator runtime
#   - alertmanager-* / prometheus-* (operator config secrets)
#
# Full rationale: docs/excluded-from-flux.md (Runtime-managed secrets section).

set -euo pipefail

CONTEXT="${1:---context=home-k3s}"

exec python3 - "$CONTEXT" <<'PY'
import json, re, subprocess, sys

context = sys.argv[1]

ALLOWLIST_NAME = re.compile(
    r'^('
    r'kube-root-ca\.crt'
    r'|sh\.helm\.release\..*'
    r'|.*-tls'
    r'|.*-ca'
    r'|.*account-key'
    r'|tailscale-state'
    r'|cert-manager-webhook-ca'
    r'|.*kube-prometheus-stack-.*'
    r'|alertmanager-.*'
    r'|prometheus-.*'
    # StatefulSet volumeClaimTemplates create PVCs named `<vct-name>-<sts>-<ord>`;
    # they don't carry ownerReferences but are functionally Flux-managed via the
    # parent StatefulSet. Common pattern across this cluster:
    # data-binks-postgres-0, data-placemyparents-postgres-0, etc.
    r'|data-.*-[0-9]+'
    r')$'
)
ALLOWLIST_TYPE = {
    'kubernetes.io/tls',
    'kubernetes.io/service-account-token',
    'helm.sh/release.v1',
}
ALLOWLIST_NS = {
    'kube-system', 'kube-public', 'kube-node-lease', 'flux-system', 'default',
}

def kget(kind):
    out = subprocess.run(
        ['kubectl', context, 'get', kind, '-A', '-o', 'json'],
        capture_output=True, text=True, check=True,
    )
    return json.loads(out.stdout).get('items', [])

orphans = []
for kind in ('deployment', 'statefulset', 'daemonset', 'service', 'ingress',
             'configmap', 'secret', 'persistentvolumeclaim', 'cronjob'):
    for r in kget(kind):
        md = r['metadata']
        name = md['name']
        ns = md.get('namespace', '')
        if ALLOWLIST_NAME.match(name): continue
        if r.get('type') in ALLOWLIST_TYPE: continue
        if ns in ALLOWLIST_NS: continue
        if md.get('ownerReferences'): continue
        labels = md.get('labels') or {}
        if labels.get('kustomize.toolkit.fluxcd.io/name'): continue
        if labels.get('helm.toolkit.fluxcd.io/name'): continue
        orphans.append((ns, kind, name, r.get('type', '')))

for ns, kind, name, typ in sorted(orphans):
    extra = f' ({typ})' if typ else ''
    print(f'{ns:25} {kind}/{name}{extra}')

if orphans:
    print(f'\nTotal orphans: {len(orphans)}', file=sys.stderr)
    sys.exit(1)
sys.exit(0)
PY
