apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microbin-data
  namespace: microbin
  labels:
    app.kubernetes.io/name: microbin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
