apiVersion: v1
kind: Secret
metadata:
    name: minio-root-secret
    namespace: minio
    labels:
        app.kubernetes.io/name: minio
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:Douh7NPLIwuN9Gvk2glI,iv:bg2lsKCb3LOoC7lZnDtlhpb3Bx4eg+0GXj76aFfGsEs=,tag:GrDehLUmNY/Df2lqYzEBNA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:g2hBeQg/6rIS2nPVKLWVRhjRLb+Vo2kLZ5Y+mkhWxGw19BQ6eC4VeQ==,iv:gcBIKzsHtV3GnOSyQikpJ8Jl6635OR1JOos5SCsnYAM=,tag:QNmoj3noSUpyRzBneyO0mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSFpxZGprQS9KZ0xOdnJ2
            RlJQWWdTUDNSK3RUaUMvWDZBbWVzM1RhSkh3CncwS0Yrbno0dVJtU2hhdmxVWm92
            blBNV2dzTTFaa2lyZ1J3UmtRQ3QxcU0KLS0tIEhCcnlMZVRzaXZ2ejBieFBCc2NH
            VkVNWHdBQWM2N3J0SWNUc2ErQmhiSlUK7Ee9oNAlRYY3cbkSImHrLPGZvWZQ0G0P
            dRNmC7serdewDJjOGewfZkMpGe7xYEeu/ugRLliTV2hT/oG27PAAaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T12:45:57Z"
    mac: ENC[AES256_GCM,data:X6BN6B/lNzmFkNnOJcmO/srcyB5gu1bu3khCTMag2KWfvE2ls01ekXcCetXGADMPyYPJ7RXHUeAmrNzch+/tQ8BVjqbTNIkWrXsV+wB+/aXLPnqahgglk2HZTXMyPkXDptYvgfWFRujZEO4XH6s9pUjAEQ22gU4w4Nasx7TOEBI=,iv:tz3beaByIHTchRa8PPejomfoLwoRWtZ9Y0AxtK5OjE8=,tag:9GHNNLnLfeWkoLNWa2gbBg==,type:str]
    version: 3.13.1
