apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: game-registry
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Avba6bkTsqZB8alaEPodU7kl6Xabdh6K1O7nglyD8FWQQGroMZUsKy0zST1aW16PHBSaZs9cQWuczXimoOaC0aZbgUjLxKT+vUehd5BSqm8w7IBrZGFH7caQneBTE0QxihSZ5C5yaZfKAa+gagzs9X04ZewxG73D41T0/WUgNxQDB/0jR+2qFoViyaLtrI0hO/80Po26abIJ23OmKfrE+w/sPsVvLaPIAsXcFIKzZtmzEz+fua6wug==,iv:BjBVryQGNxcCRXRkxZZ5WmMmOW0g5c7qHG2/n3wGyD8=,tag:2EM/CigL1zirswqxdVWO6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTWVIUlRYdG1ZbXl2OTkx
            WGtzc2V3L0ZiTUhxcWpWVmM1NFA1OXhnRUJvCjhrNytWNDJ4RFRvZlhwcnhuL2kx
            aWNxbWlxWDJNZWRDd2VUbU4xdzl4elEKLS0tIEd1S0VtaDlkRWJmVlkwYkdlT25G
            MGF1dW5HYnVzTU1ZZUU4bTNTUkJJRkEKk6c1sAD1DhKDCMc/RWXLqQQwmqLaxidF
            e373q14mZx7gG60BSr25WflnnzFw2K43/KLSUcYIRQLit9w9ijcB8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T16:49:53Z"
    mac: ENC[AES256_GCM,data:YG50goUysCyi1ILWneSsb67WKXE0BKQBg7caz+a9kMa9rsq0caRbVcRha5Z73RIm3D6KhfhU63NreBovID9obo8i+VKLmEmfsXBovlJWoXswwSVJadtq7tUHKEQVUXYuvUHHqUambsIKaDYjgGwRGMdmyc57wgEtZ6t5sogXNo8=,iv:ftMqgmTkqwnyzyOpgwM4p9nWiR7VBkLLbvulYRI6K+0=,tag:2G0H2zN9apxRKylCxBPTVg==,type:str]
    version: 3.13.3
