apiVersion: v1
kind: Secret
metadata:
    name: game-registry-tokens
    namespace: game-registry
type: Opaque
stringData:
    SERVER_TOKEN: ENC[AES256_GCM,data:WC1Dgmc5OSDzQdrQw90WJWqLiU+O/RpZ/ehIbaX6KtbSmoI6qQ5vnDn7hyYz1FRQ,iv:HKdAR3DsRiYTaQpEEUQuPHU3G13077wNnxQhh1SK86s=,tag:JNQbz3X1gSblTiPHy3nlvw==,type:str]
    HOST_TOKEN: ENC[AES256_GCM,data:UvAAgkIWsuG52YBwWn/0deg1spxtc4ITvcP5i7eQA9d8eSY/SZyw8A1LKJTWUEag,iv:0AcIAGZFIMlg6pWC7tQkZOwqW7BIIDY3L50hRqn5Tz0=,tag:pVjJjJMyLt5lwaz6nGhxHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYUd2ZklCTGZYSWg1K2xS
            MFljMUQrV1l2eTU5REJTajFzMnIvendqeVFnCmNWaFg5MGpHb3U4NE1LYXlwS3Ez
            TGpHOWxQK0tDVzM2aC9OWVNpZGZIMVkKLS0tIDkvbldIUEJSMkpIbG8ybzVOTGZP
            UkVHTGxrRnBUTGpHTURHZ3B4ckFGUXcKAgzfFJpPvKA0ipZicp99q9J45cmQk2qz
            baNKm5wy9x1mt1twrkbSrBHv12QtkV2HzkTQOlL7TNBHG3oZJMfuJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T16:49:53Z"
    mac: ENC[AES256_GCM,data:lssMjbqdLqjXWK6kEMwYTkx17HrU1KrrXOticWUCz9ot6R21ELc7XuftxZ6gayC3eOkhNgdwVdRsiGw68NKQ4mk8cF3fA6GvGnAj+jp2GwGtjbgmFPJSLHzWEKD9t4PnYllCjlScrkj6r/9mrqoSD4WyzGRXs17lFMZmsvUzNZY=,iv:hepvWLKG21k9BlAI3HIdk5aANb2/esmoBpqdOKGqmu4=,tag:EL7cvpJ0LgOGOLg6SrRY7Q==,type:str]
    version: 3.13.3
