apiVersion: v1
kind: Service
metadata:
  name: mqtt2prom
  namespace: mqtt2prom
  labels:
    app.kubernetes.io/name: mqtt2prom
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mqtt2prom
  ports:
    - name: metrics
      port: 9201
      targetPort: 9201
      protocol: TCP
