apiVersion: v1
kind: Secret
metadata:
    name: immich-kiosk-secret
    namespace: immich-kiosk
type: Opaque
stringData:
    #ENC[AES256_GCM,data:A+b3Ibeo1C6EImhW7QLu03Rk/TFXaOTuj/CWWDH5sl0wnofuQkibz3r/+FYuPQGt0Bk/3w==,iv:B4oL3NPZBtTCshztv4mmdQRfX430Q0EwkyoakvDUs0E=,tag:KCwOpmfpibbn2MRmgLdyNA==,type:comment]
    #ENC[AES256_GCM,data:o+O4PQBrTs8CLjBmZEf0pGB9Pj/YGBtzcVcGsncbl9setfk66YSgROtGsQOpnrgHxgxhyEn9LJvC4Jk8ExQ=,iv:lRlmtklUZraEbs9uTZ5lR5oNFc8FGpd+z+gQWsioWD8=,tag:9WTsLTpYLXD0eBPTGMYgww==,type:comment]
    #ENC[AES256_GCM,data:q+bIculmH0H6vRvQSeTf0QQWMFWeDC5MMRMO/N4ilnOi1hrgWgq419dHye/PAZvIQyRJkytyqb2IE33qw0ygx78d8UV8nMF+IyOOy4yAKgrV8BbMObGtcXeSWSpjD46H6e+nxrKyiqwG,iv:JdNhSTz4HtOth7S8BWKDoCMJ3Zf+vLDcQpOeSEqhzC0=,tag:SCXpHFoyJMhH/Wtety++ig==,type:comment]
    api-key: ENC[AES256_GCM,data:aR9lkfeyUZJQ7uRJ6Ugbal5+TQFqY01EiA==,iv:H2xc/AwaOo48CblCkY9h1ZPVG92ZiM3fH/LbvkWPUE4=,tag:1OAzi+xjbp5W6vhzMXNAwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Ui84b3lVR2lLSzBUL2I2
            Q2xPY0t5TmF5ejFYclFVOUQwV2ZiVzFvWWhNCk80Y2MvZVFpUnhLUzNuV3ZJSWRU
            WTNjNnZUSXJGM2xZZlVuNnVQOFZvNjAKLS0tIG56eVI2cThaRE9kYjRSUnNyeWFO
            T2gycXorT1BFVUZSa0lBSGJXSStwV28Kg6j99tD5un3TdUWOKAkMh8fLMZfLfpjS
            6m/VSh2kHh5of6h/2Ktx4VIQPaOO/o01jeg+RVK2DFMDVDd013mEkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T19:12:17Z"
    mac: ENC[AES256_GCM,data:2ohv5e9jFs+wDoEBHtin2jY+xbP1yi59XkanD9JE1uOwf7TkQznR36whXANWhw/vnVOw9NUuefg6exqkCe+/PKdzJ8o4sulxwqxbTb+mG2pUYjcJpnB5ndk/zf+vG8nYY3i/TrBYHxd0KdCFDfmg/QMW2B7HFSrySeS34nDnZzc=,iv:mXvuKDj4hy74SAUuMhUPU/Ly4/zWzU7dubL+4+wDGs8=,tag:T+XqpUrJoZWBZ1gDCbxCoQ==,type:str]
    version: 3.13.1
