apiVersion: v1
kind: Secret
metadata:
    name: immich-kiosk-secret
    namespace: immich-kiosk
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rJww75WmCbEzCYa4299EIe/6ey27Uv8MISbGSTZq2Vc33T4yN36dRHk6qET9l3xP1d1Qhg4hzj3lwdZDht5jb3jE,iv:Ewj8b2uBZ5y1xs8CuOw/HpRUKhaX2Ipdf1NCpsmzYIs=,tag:dXXnpdrXE+REgxFMZ0b+bg==,type:comment]
    #ENC[AES256_GCM,data:4IPbzn7v9lO66PuUEBOV1H7qGItbjZLIYlgpDuoVkqJLWVLmF4B14RiS+XdRcokElVrGtkdYa2xL523xFZjSzKV8/cHCSW9O+lpWCVJd+L2ehQ==,iv:oVAIwvl0YWXnnUDzAQyrUASPHiq/T1iZllyNnwNgE4I=,tag:egW5JArXo1wOrMu32d3f8w==,type:comment]
    api-key: ENC[AES256_GCM,data:++OilOgusiTAur3cOo9Y/lMOEkw28LzvWkFN6aUC4DyijuuJB1nllH4=,iv:3OBPxJzMMQVi+C7ZvSJkFmejwih3xKjs1U0mwqEQXtA=,tag:NGwdUFEgVKMMKEbKqyWd3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMytKdFhUWlRHNVEvdnJ2
            L3ZYSkV3Wkcxc3VUMi9BVXJTbWFDSm11Vmw4CldvVXVtSGZ2cjFYUE5sZG1sTkVk
            Q1E4dXdyUzhKUlNBYjVSRTJzRytnUW8KLS0tIFVCM1VXUnZuWnA3OGRoQmdkRmFs
            RE91SzhzaWx4ci9Bb1BsaGRJcklSSWsKnCa1Rz808lpD2FR4iOmjPS0KoOIo5Ycz
            l6F9ZWCOePvvuug0a3hpqjpyBvZqz8Q+haeyVuwYplfXgIDEKRp8rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T22:46:18Z"
    mac: ENC[AES256_GCM,data:YXfmP2ctIRvaE1nHK7ePeooXvcy31ol8MKZWQelWSwcpbLO4Jma+H7Kiadvg1i1m1R/LbMgFEWamI2ACUXAttR2tPm2PXpIusfhvhK1ZtZbjRGXjMt2DO9yNMLoF5SS1zQjii2X2Dmro9cSE4MSt8Y99mst98cFPXipOq5rdkHc=,iv:3EiSeu/dOjRi7g+lkFhwKJ4ClSMo9gSCGn9FmLK+7Ao=,tag:3MZ2xFvLFtkMFWzUkj1eag==,type:str]
    version: 3.13.1
