apiVersion: v1
kind: Secret
metadata:
    name: semaphore-secrets
    namespace: semaphore
type: Opaque
stringData:
    SEMAPHORE_ADMIN_PASSWORD: ENC[AES256_GCM,data:9tP+cgposIY=,iv:TuiYTDLdIst8zPR1ZH9kvFel0jYb4SFwfBnPkTyTaBw=,tag:AWvx7jiot7MR2gIoGiHxIQ==,type:str]
    SEMAPHORE_ADMIN_EMAIL: ENC[AES256_GCM,data:7QC8tKIqez+9AyXzxDC0EC01V6U=,iv:uSZ1ifeOviZNtfPYs11kGNEtiNaVx2GwbOilwRNC2/k=,tag:avlwO2iroUnoHBTpHHXZ+Q==,type:str]
    SEMAPHORE_ACCESS_KEY_ENCRYPTION: ENC[AES256_GCM,data:Cga6onl7/bBfNfEki0ftw4GRxkFi/S/Uenp8GFVFp6ho8ti11Y5HyURabvk=,iv:cJWo1q2GZv3Frib3M2Q+teukLBtQfaxUBE7QyrWuPsc=,tag:jgs62noXfmau5XfA+AgG6Q==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MFFuYk1qUVhLQ1BYZGhu
            U0xKelpDbEhGTXFLK2dqVGVXcllOVHlyWXc4CnhrZ0FNRmpvMVFheGhKUitha053
            a2l2dkp4bk82TVRyV0ZMVWxVdXNRaVUKLS0tIHVXUGFLeFU3YW9ZcTh0VHhyVnJY
            N0c1K1o5UkY0QXgzcjY1ZFFDV05JWncKRphqhaMdhRN3ihqQunDKNS4+G42PF7Gp
            5v6GbLXc4hohl4tZWEJmHjYnNtDdXdcEc/oYpRxK5LC5sBCF9lmj5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T17:17:44Z"
    mac: ENC[AES256_GCM,data:hdZleHucW0dcFLAphsITvrANzwPqXgmet1gStkoCCnfSe853inzcxMc7WTkWhUgl56WHLIjkVmCv4PLnxsPO5p3DmH0bks4iYgyf5pagMpAXk6Wl2BoWgUAsdgOKZoKYQIh4PHJDnis0EMQii32UjGtsUzU7eNBWDGFV8gd2/bw=,iv:izgwZXCsiqLeNBiDpi/eK2K1C0oTkgtTZZmK2fMzrQo=,tag:Ns2/CH53zqi6nX/A4V1xOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
