apiVersion: v1
kind: Secret
metadata:
    name: forgejo-registry
    namespace: portfolio
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:WCJb6NY8mpxFkum1TVvcpuASkjz5lRF71qz/tdEDUFanUETJgcwhabeLGo673I4mLM4IrdAuobsSPi7BR/F3bfKRn/uhX3KjsT+GvM9JmO70F/G4RZqUpiS5HFEQRRVKw7kS8Ki/qrpTZF8dAqW9PQZdFgECfZ/PHv0PKW922tYgraKrAbY4GvJ/zX7sVMW1XIFTFHkO4ZKEnYGkDawvWpuz+L2r8UEBIjKX1y1zysXcekf0m5aJaw==,iv:RyiQY8gNA42YcbprXSaiYiTmR+65JuOTiX4UBBcn70U=,tag:73w+mvj/kCjwksGG5xQN6Q==,type:str]
sops:
    age:
        - recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSTlOYytlNkRIY09USDQv
            Z2drVlhTRjRJSElBcnBscW03bUpxZndzdFR3Cmx4ZllmQXFTdXV4L3prckYxbitr
            YmRGK1puZjJBc3NaenpobkdKZ0k1Rk0KLS0tIDMyQTNtZm0vL2FNM1Vqa1ZpY0xt
            L3pvTkp2L1JySjFSRERrZ2xWYWxBWWMKvAQ9u3yQdpp3PZCmjSBTlZmj+FKu72Uk
            d97vhGDSI80rUCMdQNbPs0efR8Oc7t8M19DMtLkXlMMAGdrGWqgkVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T13:31:37Z"
    mac: ENC[AES256_GCM,data:efA4mutK2rZXFKi8tJBHk1isfSFHqvdnk8Z8dbewjM6l0Dc9FeH66Zkx2Qb7Tqs6KpxbhY0obF2mKjdcPbpi7bs09xmwnWRYy7ziKjGGMeQp/C5+e+joUwEDavN5IgCP3QZfBKo9MmV9SHywtGT+/L3bHwRS/AUevO2haM0h+Yo=,iv:FMQITKWfjfmrG+kex7WktJnYa7vOVb5PLGeXplSrcFg=,tag:YpUim3ldq0gm/61Qvavgzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
