apiVersion: v1
kind: Service
metadata:
  name: fleet-mysql
  namespace: fleet
  labels:
    app.kubernetes.io/name: fleet
    app.kubernetes.io/component: mysql
spec:
  selector:
    app.kubernetes.io/name: fleet
    app.kubernetes.io/component: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
