apiVersion: v1
kind: Secret
metadata:
    name: fleet-secret
    namespace: fleet
type: Opaque
stringData:
    #ENC[AES256_GCM,data:h1Ro72ADyAkKp+leFaCKKdPSiTlZHTmvhOfswhJ04Hf7q4KFKW0ScNpK+li+25BMq0xmBjYTljeBvlwpBVMYJP6n3hZ5N8Yxww==,iv:TCWRNu/5vGO/i9V1sdS9m4u+IUE3+I84iyJF3hO1V5Q=,tag:svTFVAdGnsrcPzlOhXm2ig==,type:comment]
    mysql-password: ENC[AES256_GCM,data:w8EmfHV3r1FdPPyllQR5BN3kJNYUX0rOHDiMRk7LKNe0kHgRy7Zc1g==,iv:rXQKJklVnaxchsJO13g20xQgUWYALEh39ihyRrAO1+Q=,tag:Mya+M1UPFPU3cLo5oMvFUQ==,type:str]
    #ENC[AES256_GCM,data:hMdsR/NSXSWTS4E5U92iLC5RCnO/rNNeLP1YheT5bh38y6HKPpG4SqapxK9QTQ0H/kBArp4w0X/d2+soaBpfA6PhGx9t,iv:QYorwpLFCjC2C/aNCV00H9jV9DVkT8DLU9WhocKhpyI=,tag:DfK8e/B9jEdcQ7ns/2uaIA==,type:comment]
    mysql-root-password: ENC[AES256_GCM,data:FIx8KroaxQAH1ESMqk6GvCZgbY4by6M5kijh3xUQXinjV34A/2hbow==,iv:XwnCcaHRp/RI6sdyrzjDNX9fReMWt6lwQVZRWzQS5+Q=,tag:BrRlctzPRa3t5ojr1gu4Sw==,type:str]
    #ENC[AES256_GCM,data:jIgl2jIxo5IuLa41fIy/KkSYtbUis9nnoB5V5qoDNW2RMUDW0GoFD6r+WvqJ2tAMhK08WoBjH9PwNxMbE574JAg/lO9bRsEx7Pal,iv:DuzliwrZMFn2ba7KkY2Pwd4rBa7vyHf1FbhnFgBaCYM=,tag:VfwfB5lFOEaWGAcD2PvS+w==,type:comment]
    #ENC[AES256_GCM,data:vTJJNH6RuKD8Fa4F3MqIQwGEp9zHM2QrkXhDGMuP4Fc4KSVLaiE7EBUb5YX1Fts6siRxxGazo6smn3EPji7xDYuj7P3Bv74bxSoGrA==,iv:jMZyxeXz4p/M68LZ72TTvBPY7DI5q/6VOx9Q16XQcR8=,tag:RplQCdctwXTbmE2fFFeNPA==,type:comment]
    #ENC[AES256_GCM,data:kFdSIs9c48a4U2k+48g1aoambFgsdlzC3V2S9WjQouRYiVNkV8DCbMzQbwAN3emQ6lwcbUNGfNip,iv:J+zSCJkpS2oKV9odAAFCbkcbnwPZD7J6rf0Bqpz4bCU=,tag:Kvob1FsQufYSCOHtAqsMYQ==,type:comment]
    fleet-server-private-key: ENC[AES256_GCM,data:vn3sYE+a5zQLy4zrdBgSaZgUCJ7k4EBdtLqWpGNjEaEKXLhqPpaZSc8k3/0=,iv:IpkwxQQXb2DTwHTWl/AQ/LAsKpZhj1E5MPuDLO1fqXc=,tag:7lsFTk+6lmiAOfatW81MYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwc0FnVWI4OWp0TVp6eWll
            RldCMkVyUGJPV3FnZzZnVG01dTVOcnBZdm5zCks2UXU0bzI2ci9EVlVCRFEyNkRH
            SjJ2TDIzL2NDT1RYWE5RQU1hZ1h0Z2sKLS0tIDNMUUxxeHdlc25wSFVPYThlVFdr
            elpwaWJTbi96Q1RNKzh4Z2t1dFVtalUKoo74UZ06w0369EPbLItnp9OuQGCGQKpw
            oBLP5saDgkbOwaIT34OVijUbATgoaj/Ps7wmeOnqtuKFHS0BD7Mh5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138x34tdqulknsj967wjv9urg9ucxtpkep2apzjmthta3xtjgvpgsm8k3a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T01:45:04Z"
    mac: ENC[AES256_GCM,data:FyZcIXcyK3hyi+A1X1rPybBEAnbLGAbAeolRgfqPgYmYrdNQ/3g3PseFXd4YcQsTzd9q+pAzUf4W7+KW1YFRe1CIGYsPANZGBt34qfsIV5kyBe9Cf1jtOJrNg9H5isnXcEUKmcHz23uwxKYDhXyhz34x1Rm29QoDyo/giYRpYuA=,iv:/pyDnzlIVBI8QSgVHyCjYBgoBRZIPAKA8cNPoLt93XE=,tag:79dblkHqdFg/1GFvIt23Wg==,type:str]
    version: 3.13.2
